export interface NavItem { label: string; href: string; hint: string }
export interface NavGroup { title: string; items: NavItem[] }

export const NAV_GROUPS: NavGroup[] = [
  {
    title: "Onboarding & CDD",
    items: [
      { label: "🛡️ Grievances", href: "/governance/grievances-whistleblowing", hint: "Whistleblowing & grievance management" },
      { label: "🔄 pKYC Monitor", href: "/pkyc", hint: "Perpetual KYC — continuous CDD lifecycle management" },
      { label: "🪄 Onboarding Wizard", href: "/operations/onboard", hint: "Guided new-customer flow" },
      { label: "🪪 Client Portal", href: "/client-portal", hint: "Entity KYC + AI risk assessment" },
      { label: "👥 UBO Declaration", href: "/ubo-declaration", hint: "Beneficial ownership form + AI risk" },
      { label: "👤 PEP Profiles", href: "/pep-profile", hint: "PEP tier · SOW · network map · EDD measures" },
      { label: "🌱 ESG Risk", href: "/esg-risk", hint: "ESG scoring · ML risk overlay · regulatory exposure" },
      { label: "🤝 Supplier DD", href: "/vendor-dd", hint: "Third-party due diligence + AI risk" },
      { label: "📋 CDD Review", href: "/cdd-review", hint: "Periodic re-KYC + AI adequacy check" },
      { label: "✅ Data Quality", href: "/data-quality", hint: "CDD completeness + AI remediation plan" },
      { label: "🏢 Ownership Explorer", href: "/ownership", hint: "UBO mapping · shell risk · jurisdiction layering" },
      { label: "🧑‍💼 Employees", href: "/employees", hint: "HR registry · doc expiry · AI risk scan" },
      { label: "🎓 Training", href: "/training", hint: "AML/CFT training tracker · completion records · mandatory deadlines" },
      { label: "✅ Approvals", href: "/approvals", hint: "Entity approval tracker — status, risk score, country destinations" },
    ],
  },
  {
    title: "Risk & AML Ops",
    items: [
      { label: "🔎 Screening", href: "/screening", hint: "Sanctions, PEP & adverse-media screening" },
      { label: "💸 Transaction Monitor", href: "/transaction-monitor", hint: "Real-time transaction monitoring & alerting" },
      { label: "👁️ Ongoing Monitor", href: "/ongoing-monitor", hint: "Continuous subject monitoring & re-screening" },
      { label: "🗂️ Cases", href: "/cases", hint: "Case management — investigations, dispositions & audit trail" },
      { label: "📊 EWRA / BWRA", href: "/ewra", hint: "Enterprise-wide risk assessment + AI board report" },
      { label: "📋 STR/SAR Filing Suite", href: "/sar-qa", hint: "Four-eyes quality review + goAML XML export wizard" },
      { label: "📤 goAML Export", href: "/goaml-export", hint: "goAML XML export for FIU submission · CBUAE Notice 2021/8" },
      { label: "🔗 Supply Chain & Responsible Sourcing", href: "/supply-chain", hint: "Geographic risk · CSDDD · UFLPA · RMI/RMAP · OECD 5-step DDG · MD 68/2024" },
      { label: "📋 Reg Changes", href: "/reg-change", hint: "Regulatory change roadmap · AI implementation calendar" },
      { label: "📦 Shipments", href: "/shipments", hint: "Bullion chain-of-custody + AI TBML scan" },
      { label: "🇦🇪 EOCN", href: "/eocn", hint: "UAE targeted financial sanctions + NAS/ARS registration + control list" },
      { label: "🚨 Sanctions Alerts & Name Match", href: "/tfs-alerts", hint: "EOCN subscription alerts · CNMR filing · Gmail monitor · Asana compliance tasks" },
      { label: "📝 CNMR", href: "/cnmr", hint: "Consolidated Name Match Report filing · EOCN" },
      { label: "📋 PNMR Queue", href: "/pnmr", hint: "Positive Name Match Report queue · EOCN" },
      { label: "💵 DPMSR", href: "/dpmsr", hint: "DPMS cash reporting ≥ AED 55,000 · CR134/2025 Art.3" },
      { label: "📋 MoE Survey", href: "/moe-survey", hint: "Mandatory AML/CFT survey MOET/AML/001/2026 · all DNFBPs" },
      { label: "👮 Enforcement", href: "/enforcement", hint: "Regulatory deadlines & action tracker" },
      { label: "⚖️ Oversight", href: "/oversight", hint: "Board & management sign-off · minutes" },
      { label: "🎯 FP Optimizer", href: "/fp-optimizer", hint: "ML false positive pattern analysis · threshold tuning" },
    ],
  },
  {
    title: "Governance & Audit",
    items: [
      { label: "🧠 MLRO Advisor", href: "/mlro-advisor", hint: "AI-powered MLRO decision support & guidance" },
      { label: "🤖 Responsible AI", href: "/responsible-ai", hint: "UNESCO AI ethics compliance · human oversight" },
      { label: "🏛️ Inspection Room", href: "/governance/inspection-room", hint: "Regulator-ready evidence pack" },
      { label: "📜 Regulatory Library", href: "/regulatory", hint: "Searchable UAE/FATF regulatory library" },
      { label: "📑 Policies & SOPs", href: "/policies", hint: "AML programme charter & procedures" },
      { label: "📚 Typology Library", href: "/typology-library", hint: "500+ ML typologies · AI search · UAE-specific localised content" },
      { label: "📖 Playbook", href: "/playbook", hint: "Step-by-step AML/CFT compliance playbooks" },
      { label: "✏️ Corrections", href: "/corrections", hint: "Data-subject access & correction requests" },
      { label: "🤖 AI Incident Playbook", href: "/ai-incident-playbook", hint: "UAE FDL 10/2025 — AI failure response: hallucination, bias spike, data poisoning, prompt injection" },
      { label: "👁️ Shadow AI Register", href: "/shadow-ai", hint: "Unauthorized AI tool detection & remediation · No-DPA vendors · Data classification risk" },
      { label: "🏢 Vendor AI Audit", href: "/vendor-ai-audit", hint: "AI vendor due diligence · DPA · model card · penetration testing · SLAs · CBUAE audit trail" },
    ],
  },
  {
    title: "KYC Tools",
    items: [
      { label: "🌐 OSINT", href: "/osint", hint: "Open-source intelligence — domain & username harvest" },
      { label: "🆔 GLEIF / LEI", href: "/gleif", hint: "Legal Entity Identifier lookup & name search" },
      { label: "🕸️ Entity Graph", href: "/entity-graph", hint: "Relationship & ownership network graph" },
      { label: "🌍 Domain Intel", href: "/domain-intel", hint: "Domain & web infrastructure intelligence" },
      { label: "₿ Crypto Risk", href: "/crypto-risk", hint: "Wallet & crypto exposure risk" },
      { label: "🚢 Vessel Check", href: "/vessel-check", hint: "Vessel sanctions & dark-fleet screening" },
      { label: "🔢 Benford Analysis", href: "/benford", hint: "Benford's-law statistical anomaly test" },
      { label: "🕵️ Investigation", href: "/investigation", hint: "Case investigation workbench" },
      { label: "📍 Single Country", href: "/country-risk?tab=single", hint: "Single-country risk brief" },
      { label: "🚫 Sanctions Evasion", href: "/sanctions-evasion", hint: "Sanctions evasion typology detection" },
      { label: "🏢 UBO Walker", href: "/governance/intelligence-tools?tab=ubo", hint: "Beneficial-ownership chain walker" },
      { label: "🧪 Intelligence Tools", href: "/governance/intelligence-tools", hint: "UBO walker · crypto exposure · synthetic ID" },
      { label: "🔒 Audit Trail", href: "/audit-trail", hint: "Immutable decision audit trail" },
    ],
  },
  {
    title: "Intelligence",
    items: [
      { label: "🛰️ Live Intelligence Feed", href: "/intel", hint: "Live regulatory & 7-language adverse-media feed · unified intelligence hub" },
      { label: "🧠 Brain Intel", href: "/intelligence-hub?tab=brain", hint: "Brain faculty intelligence & reasoning-mode insight" },
      { label: "🔧 Workbench", href: "/intelligence-hub?tab=workbench", hint: "Analyst cognitive workbench" },
      { label: "📡 Telemetry", href: "/intelligence-hub?tab=telemetry", hint: "Live system telemetry & metrics" },
      { label: "🥷 Red-Team", href: "/intelligence-hub?tab=red-team", hint: "Adversarial red-team probe console" },
      { label: "🛡️ Security", href: "/intelligence-hub?tab=security-audit", hint: "Security audit dashboard" },
      { label: "💚 Status", href: "/intelligence-hub?tab=status", hint: "Live service status & health" },
      { label: "📘 API Docs", href: "/intelligence-hub?tab=api-docs", hint: "API reference documentation" },
      { label: "📋 System Card", href: "/system-card", hint: "Model system card & governance disclosures" },
      { label: "🛡️ Security Scan", href: "/security-scan", hint: "Dependency & code security scan" },
      { label: "👁️ Analyst Behavior", href: "/analyst-behavior", hint: "Analyst behavior monitoring" },
      { label: "🎯 Board Dashboard", href: "/board-dashboard", hint: "Board-level compliance dashboard" },
      { label: "📊 KRI Dashboard", href: "/kri-dashboard", hint: "Key risk indicator dashboard" },
      { label: "🔐 Access Control", href: "/access-control", hint: "User roles, sessions & permissions" },
    ],
  },
];
