"use client";

import { useEffect, useState } from "react";
import { ModuleLayout } from "@/components/layout/ModuleLayout";
import { BarChart, Donut } from "@/components/ui/Charts";

interface Manifest {
  product: string;
  version: string;
  generatedAt: string;
  charter: {
    prohibitions: Array<{ id: string; label: string }>;
    matchConfidence: string[];
    outputStructure: string[];
    regulatoryAnchors: string[];
    authoritativeLists: string[];
  };
  cognitiveCatalogue: {
    faculties: Array<{
      id: string;
      displayName: string;
      describes: string;
      synonyms?: string[];
      modeCount: number;
    }>;
    reasoningModes: {
      total: number;
      byCategory: Record<string, number>;
      byWave?: { wave1: number; wave2: number };
    };
    adverseMedia: {
      categories: Array<{ id: string; displayName: string; keywordCount: number }>;
      totalKeywords: number;
      queryLength?: number;
    };
    doctrines: {
      total: number;
      mandatoryInUAE: number;
      byAuthority: Record<string, number>;
    };
    redFlags: {
      total: number;
      bySeverity?: { low: number; medium: number; high: number };
      byTypology: Record<string, number>;
    };
    typologies: { total: number; ids: string[] };
    matching?: { methods: string[] };
    sanctionRegimes: {
      total: number;
      mandatoryInUAE: number;
      byAuthority: Record<string, number>;
    };
    jurisdictions: { total: number; byFatfStatus?: Record<string, number> };
    dpmsKpis: { total: number; byCluster?: Record<string, number> };
    cahra: { total: number; activeCount?: number };
    thresholds: { total: number; ids: string[] };
    playbooks: { total: number; ids: string[] };
    redlines: { total: number; ids: string[] };
    fatf: { total: number; ids: string[] };
    dispositions: { total: number; ids: string[] };
    skills: {
      total: number;
      byLayer?: Record<string, number>;
      byDomain?: Record<string, number>;
    };
    amplifier: {
      version: string;
      percent: number;
      factor: number;
      directives: string[];
    };
    metaCognition: {
      total: number;
      byCategory?: Record<string, number>;
      ids?: string[];
    };
  };
  integrity: {
    charterHash: string;
    catalogueHash: string;
  };
}

interface Integrity {
  charterHash: string;
  catalogueHash: string;
  compositeHash?: string;
}

interface Enhanced {
  extended: {
    taxonomy: Record<string, number>;
    regulatory: Record<string, number>;
    expertise: Record<string, number>;
  };
  crossReferences: {
    redFlagsByTypology: Array<{ typology: string; count: number }>;
    jurisdictionsByRegion: Array<{ region: string; count: number }>;
    typologyCount: number;
    topTypologies: Array<{ id: string; title: string }>;
  };
  totals: {
    catalogues: number;
    enhancedCatalogues: number;
    regulatoryRecords: number;
    taxonomyRecords: number;
    skillsRecords: number;
    totalRecords: number;
  };
}

interface Response {
  ok: boolean;
  manifest?: Manifest;
  integrity?: Integrity;
  enhanced?: Enhanced;
  error?: string;
  detail?: string;
}

export default function WeaponizedBrainPage() {
  const [state, setState] = useState<
    | { status: "loading" }
    | {
        status: "ready";
        data: {
          manifest: Manifest;
          integrity: Integrity;
          enhanced: Enhanced | null;
        };
      }
    | { status: "error"; error: string }
  >({ status: "loading" });

  useEffect(() => {
    // Static JSON generated by scripts/gen-weaponized-brain.cjs at build
    // time. Falls back to the API route only if the static asset is
    // missing (e.g. local dev without the root build).
    fetch("/weaponized-brain.json")
      .then((r) => (r.ok ? r : fetch("/api/weaponized-brain")))
      .then((r) => r.json() as Promise<Response>)
      .then((r) => {
        if (r.ok && r.manifest && r.integrity) {
          setState({
            status: "ready",
            data: {
              manifest: r.manifest,
              integrity: r.integrity,
              enhanced: r.enhanced ?? null,
            },
          });
        } else {
          setState({ status: "error", error: r.detail ?? r.error ?? "unknown" });
        }
      })
      .catch((e: unknown) =>
        setState({ status: "error", error: e instanceof Error ? e.message : String(e) }),
      );
  }, []);

  return (
    <ModuleLayout>
      <div>
        <div className="mb-8">
          <div className="font-mono text-11 tracking-wide-8 uppercase text-ink-2 mb-2">
            MODULE 06 · WEAPONIZED BRAIN
          </div>
          <h1 className="font-display font-normal text-48 leading-[1.1] tracking-tightest m-0 mb-2 text-ink-0">
            The full <em className="italic text-brand">arsenal.</em>
          </h1>
          <p className="max-w-[72ch] text-ink-1 text-13.5 leading-[1.6] m-0 mt-3 border-l-2 border-brand pl-3.5">
            <strong>One signed contract · 19 catalogues · every screening inherits it.</strong>{" "}
            The weaponized brain fuses the charter, faculties, reasoning modes, doctrines,
            red flags, typologies, sanction regimes, jurisdictions, DPMS KPIs, CAHRA seed,
            thresholds, playbooks, redlines, FATF recommendations, dispositions, skills,
            cognitive amplifiers and meta-cognition into a single policy document every
            downstream integration imports verbatim.
          </p>
        </div>

        {state.status === "loading" && (
          <div className="text-12 text-ink-2">Loading weaponized manifest…</div>
        )}
        {state.status === "error" && (
          <div className="text-12 text-red bg-red-dim rounded px-3 py-2.5">
            Failed to load: {state.error}
          </div>
        )}
        {state.status === "ready" && <BrainDashboard {...state.data} />}
      </div>
    </ModuleLayout>
  );
}

function BrainDashboard({
  manifest,
  integrity,
  enhanced,
}: {
  manifest: Manifest;
  integrity: Integrity;
  enhanced: Enhanced | null;
}) {
  const c = manifest.cognitiveCatalogue;
  const cataloguesFused = Object.keys(c).length;
  return (
    <>
      {/* Top signature strip */}
      <div className="bg-ink-0 text-bg-0 rounded-lg px-4 py-2.5 mb-6 flex flex-wrap gap-5 items-center">
        <div>
          <div className="text-9 uppercase tracking-wide-4 text-bg-0/50">Product</div>
          <div className="text-13 font-semibold leading-tight">{manifest.product}</div>
        </div>
        <div>
          <div className="text-9 uppercase tracking-wide-4 text-bg-0/50">Version</div>
          <div className="text-12 font-mono leading-tight">{manifest.version}</div>
        </div>
        <div>
          <div className="text-9 uppercase tracking-wide-4 text-bg-0/50">Generated</div>
          <div className="text-12 font-mono leading-tight">{new Date(manifest.generatedAt).toLocaleString()}</div>
        </div>
        <div className="ml-auto flex gap-5">
          <Stat label="Charter directives" value={manifest.charter.prohibitions.length} />
          <Stat label="Catalogues fused" value={cataloguesFused} />
        </div>
      </div>

      {/* Charter */}
      <Section title="Charter">
        <Grid>
          <Card title="Absolute prohibitions" count={manifest.charter.prohibitions.length}>
            {manifest.charter.prohibitions.slice(0, 6).map((p) => (
              <LineItem key={p.id} primary={p.label} secondary={p.id} />
            ))}
          </Card>
          <Card
            title="Match-confidence levels"
            count={manifest.charter.matchConfidence.length}
          >
            {manifest.charter.matchConfidence.map((m) => (
              <Tag key={m}>{m}</Tag>
            ))}
          </Card>
          <Card title="Output structure" count={manifest.charter.outputStructure.length}>
            {manifest.charter.outputStructure.map((o) => (
              <LineItem key={o} primary={o} />
            ))}
          </Card>
          <Card title="Regulatory anchors" count={manifest.charter.regulatoryAnchors.length}>
            {manifest.charter.regulatoryAnchors.slice(0, 8).map((a) => (
              <Tag key={a} tone="violet">
                {a}
              </Tag>
            ))}
          </Card>
          <Card title="Main authoritative lists" count={manifest.charter.authoritativeLists.length}>
            {manifest.charter.authoritativeLists.slice(0, 8).map((a) => (
              <LineItem key={a} primary={a} />
            ))}
          </Card>
        </Grid>
      </Section>

      {/* Cognitive catalogue */}
      <Section title="Cognitive catalogue">
        <Grid>
          <Card title="Faculties" count={c.faculties.length}>
            {c.faculties.map((f) => (
              <LineItem
                key={f.id}
                primary={f.displayName}
                secondary={`${f.modeCount} modes`}
              />
            ))}
          </Card>
          <Card title="Reasoning modes" count={c.reasoningModes.total}>
            {Object.entries(c.reasoningModes.byCategory ?? {})
              .slice(0, 8)
              .map(([k, n]) => (
                <LineItem key={k} primary={k} secondary={`${n}`} />
              ))}
          </Card>
          <Card title="Skills" count={c.skills.total}>
            {Object.entries(c.skills.byDomain ?? {})
              .slice(0, 10)
              .map(([k, n]) => (
                <LineItem key={k} primary={k} secondary={`${n}`} />
              ))}
          </Card>
          <Card
            title="Doctrines"
            count={c.doctrines.total}
            badge={`${c.doctrines.mandatoryInUAE} mandatory in UAE`}
          >
            {Object.entries(c.doctrines.byAuthority ?? {}).map(([auth, n]) => (
              <LineItem key={auth} primary={auth} secondary={`${n}`} />
            ))}
          </Card>
          <Card title="Adverse media" count={c.adverseMedia.categories.length}>
            {c.adverseMedia.categories.map((a) => (
              <LineItem
                key={a.id}
                primary={a.displayName}
                secondary={`${a.keywordCount} kw`}
              />
            ))}
          </Card>
          <Card title="Typologies" count={c.typologies.total}>
            {c.typologies.ids.slice(0, 20).map((id) => (
              <Tag key={id}>{id}</Tag>
            ))}
          </Card>
          <Card title="Red flags" count={c.redFlags.total}>
            {Object.entries(c.redFlags.byTypology ?? {}).map(([k, n]) => (
              <LineItem key={k} primary={k} secondary={`${n}`} />
            ))}
          </Card>
          <Card
            title="Sanction regimes"
            count={c.sanctionRegimes.total}
            badge={`${c.sanctionRegimes.mandatoryInUAE} UAE-mandatory`}
          >
            {Object.entries(c.sanctionRegimes.byAuthority ?? {})
              .slice(0, 8)
              .map(([auth, n]) => (
                <LineItem key={auth} primary={auth} secondary={`${n}`} />
              ))}
          </Card>
          <Card title="Playbooks" count={c.playbooks.total}>
            {c.playbooks.ids.slice(0, 8).map((id) => (
              <Tag key={id}>{id}</Tag>
            ))}
          </Card>
          <Card title="FATF" count={c.fatf.total}>
            {c.fatf.ids.slice(0, 8).map((id) => (
              <Tag key={id} tone="violet">
                {id}
              </Tag>
            ))}
          </Card>
          <Card title="Dispositions" count={c.dispositions.total}>
            {c.dispositions.ids.slice(0, 8).map((id) => (
              <Tag key={id}>{id}</Tag>
            ))}
          </Card>
          <Card title="Thresholds" count={c.thresholds.total}>
            {c.thresholds.ids.slice(0, 8).map((id) => (
              <Tag key={id}>{id}</Tag>
            ))}
          </Card>
          <Card title="Jurisdictions" count={c.jurisdictions.total}>
            {Object.entries(c.jurisdictions.byFatfStatus ?? {}).map(([k, n]) => (
              <LineItem key={k} primary={k} secondary={`${n}`} />
            ))}
          </Card>
          <Card
            title="CAHRA"
            count={c.cahra.total}
            badge={
              c.cahra.activeCount !== undefined
                ? `${c.cahra.activeCount} active`
                : undefined
            }
          />
          <Card title="DPMS KPIs" count={c.dpmsKpis.total}>
            {Object.entries(c.dpmsKpis.byCluster ?? {}).map(([k, n]) => (
              <LineItem key={k} primary={k} secondary={`${n}`} />
            ))}
          </Card>
          <Card title="Redlines" count={c.redlines.total}>
            {c.redlines.ids.slice(0, 8).map((id) => (
              <Tag key={id} tone="violet">
                {id}
              </Tag>
            ))}
          </Card>
          <Card
            title="Cognitive amplifier"
            count={c.amplifier.directives.length}
            badge={`${c.amplifier.version} · ×${c.amplifier.factor.toLocaleString()}`}
          />
          <Card title="Meta-cognition" count={c.metaCognition.total}>
            {Object.entries(c.metaCognition.byCategory ?? {}).map(([k, n]) => (
              <LineItem key={k} primary={k} secondary={`${n}`} />
            ))}
          </Card>
        </Grid>
      </Section>

      {enhanced && (
        <>
          {/* Top-line enhanced totals */}
          <Section title="Enhanced totals">
            <div className="bg-ink-0 text-bg-0 rounded-xl p-5 flex flex-wrap gap-8 items-end">
              <Stat label="Catalogues (core)" value={enhanced.totals?.catalogues} />
              <Stat label="Extended catalogues" value={enhanced.totals?.enhancedCatalogues} />
              <Stat label="Taxonomy records" value={enhanced.totals?.taxonomyRecords} />
              <Stat label="Regulatory records" value={enhanced.totals?.regulatoryRecords} />
              <Stat label="Skills records" value={enhanced.totals?.skillsRecords} />
              <Stat label="Total records" value={enhanced.totals?.totalRecords} />
            </div>
          </Section>

          {/* Catalogue size chart */}
          <Section title="Catalogue sizes">
            <div className="bg-bg-panel border border-hair-2 rounded-xl p-5">
              <BarChart
                data={([
                  { label: "Skills", value: enhanced.extended?.expertise?.skills ?? 0, tone: "brand" },
                  { label: "Jurisdictions (full)", value: enhanced.extended?.regulatory?.jurisdictionsFull ?? 0, tone: "violet" },
                  { label: "Reasoning modes", value: manifest.cognitiveCatalogue?.reasoningModes?.total ?? 0, tone: "brand" },
                  { label: "Red flags (extended)", value: enhanced.extended?.taxonomy?.redFlagsExtended ?? 0, tone: "red" },
                  { label: "Typologies", value: enhanced.extended?.taxonomy?.typologies ?? 0, tone: "red" },
                  { label: "FATF recommendations", value: enhanced.extended?.regulatory?.fatfRecommendations ?? 0, tone: "violet" },
                  { label: "Question templates", value: enhanced.extended?.taxonomy?.questionTemplates ?? 0, tone: "blue" },
                  { label: "Policies", value: enhanced.extended?.regulatory?.policies ?? 0, tone: "green" },
                  { label: "UAE free zones", value: enhanced.extended?.regulatory?.uaeFreeZones ?? 0, tone: "amber" },
                  { label: "DPMS KPIs", value: enhanced.extended?.regulatory?.dpmsKpis ?? 0, tone: "amber" },
                  { label: "Scenarios", value: enhanced.extended?.taxonomy?.scenarios ?? 0, tone: "blue" },
                  { label: "Meta-cognition", value: enhanced.extended?.taxonomy?.metaCognition ?? 0, tone: "violet" },
                  { label: "Sanction regimes", value: enhanced.extended?.regulatory?.sanctionRegimes ?? 0, tone: "red" },
                  { label: "Risk appetite", value: enhanced.extended?.regulatory?.riskAppetite ?? 0, tone: "green" },
                  { label: "CAHRA seed", value: enhanced.extended?.regulatory?.cahraSeed ?? 0, tone: "red" },
                  { label: "Dispositions", value: enhanced.extended?.regulatory?.dispositions ?? 0, tone: "green" },
                  { label: "Redlines", value: enhanced.extended?.regulatory?.redlines ?? 0, tone: "red" },
                  { label: "Sector rubrics", value: enhanced.extended?.taxonomy?.sectorRubrics ?? 0, tone: "blue" },
                  { label: "Cognitive amplifier", value: enhanced.extended?.expertise?.cognitiveAmplifier ?? 0, tone: "brand" },
                  { label: "Adverse-media cats", value: enhanced.extended?.taxonomy?.adverseMediaCategories ?? 0, tone: "red" },
                ] as const).filter((d) => d.value > 0).map((d) => ({...d}))}
              />
            </div>
          </Section>

          {/* Jurisdictions-by-region donut */}
          {(enhanced.crossReferences?.jurisdictionsByRegion?.length ?? 0) > 0 && (
            <Section title="Jurisdictional coverage · by region">
              <div className="bg-bg-panel border border-hair-2 rounded-xl p-5 flex flex-wrap items-center justify-around gap-6">
                <Donut
                  size={240}
                  stroke={30}
                  centerValue={String(
                    (enhanced.crossReferences?.jurisdictionsByRegion ?? []).reduce(
                      (a, b) => a + b.count,
                      0,
                    ),
                  )}
                  centerLabel="Jurisdictions"
                  segments={(enhanced.crossReferences?.jurisdictionsByRegion ?? []).map((r, i) => ({
                    label: r.region,
                    value: r.count,
                    tone: (
                      ["brand", "violet", "amber", "green", "blue", "red"] as const
                    )[i % 6],
                  }))}
                />
                <div className="flex-1 min-w-[260px]">
                  <BarChart
                    compact
                    data={(enhanced.crossReferences?.redFlagsByTypology ?? []).slice(0, 10).map((r) => ({
                      label: r.typology,
                      value: r.count,
                      tone: "red",
                    }))}
                  />
                  <div className="text-10 font-mono tracking-wide-3 uppercase text-ink-3 mt-2 text-center">
                    Red flags · top 10 typologies
                  </div>
                </div>
              </div>
            </Section>
          )}

          {/* Extended catalogues — never surfaced before */}
          <Section title="Extended · Taxonomy">
            <Grid>
              {Object.entries(enhanced.extended?.taxonomy ?? {}).map(([k, v]) => (
                <Card key={k} title={humanize(k)} count={v} />
              ))}
            </Grid>
          </Section>

          <Section title="Extended · Regulatory">
            <Grid>
              {Object.entries(enhanced.extended?.regulatory ?? {}).map(([k, v]) => (
                <Card key={k} title={humanize(k)} count={v} />
              ))}
            </Grid>
          </Section>

          <Section title="Extended · Expertise">
            <Grid>
              {Object.entries(enhanced.extended?.expertise ?? {}).map(([k, v]) => (
                <Card key={k} title={humanize(k)} count={v} />
              ))}
            </Grid>
          </Section>

          {/* Cross-references */}
          <Section title="Cross-references">
            <Grid>
              <Card
                title="Typologies"
                count={(enhanced.crossReferences?.typologyCount ?? 0)}
              >
                {(enhanced.crossReferences?.topTypologies ?? []).map((t) => (
                  <LineItem key={t.id} primary={t.title || t.id} secondary={t.id} />
                ))}
              </Card>
              <Card
                title="Red flags by typology"
                count={(enhanced.crossReferences?.redFlagsByTypology ?? []).reduce(
                  (a, b) => a + b.count,
                  0,
                )}
              >
                {(enhanced.crossReferences?.redFlagsByTypology ?? [])
                  .slice(0, 12)
                  .map((r) => (
                    <LineItem
                      key={r.typology}
                      primary={r.typology}
                      secondary={`${r.count}`}
                    />
                  ))}
              </Card>
              <Card
                title="Jurisdictions by region"
                count={(enhanced.crossReferences?.jurisdictionsByRegion ?? []).reduce(
                  (a, b) => a + b.count,
                  0,
                )}
              >
                {(enhanced.crossReferences?.jurisdictionsByRegion ?? []).map((j) => (
                  <LineItem
                    key={j.region}
                    primary={j.region}
                    secondary={`${j.count}`}
                  />
                ))}
              </Card>
            </Grid>
          </Section>
        </>
      )}

      {/* Integrity signature */}
      <Section title="Integrity signature">
        <div className="bg-bg-panel border border-hair-2 rounded-xl p-4">
          <table className="w-full text-12">
            <tbody>
              <IntegrityRow label="Charter hash" value={integrity.charterHash} />
              <IntegrityRow label="Catalogue hash" value={integrity.catalogueHash} />
              {integrity.compositeHash && (
                <IntegrityRow label="Composite hash" value={integrity.compositeHash} />
              )}
            </tbody>
          </table>
        </div>
      </Section>
    </>
  );
}

function IntegrityRow({ label, value }: { label: string; value: string }) {
  return (
    <tr className="border-b border-hair last:border-0">
      <td className="py-1.5 pr-4 text-ink-2 font-medium uppercase tracking-wide-2 text-10.5">
        {label}
      </td>
      <td className="py-1.5 font-mono text-ink-0">{value}</td>
    </tr>
  );
}

function humanize(key: string): string {
  return key
    .replace(/([A-Z])/g, " $1")
    .replace(/^./, (m) => m.toUpperCase())
    .trim();
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-10">
      <div className="text-11 font-semibold tracking-wide-4 uppercase text-ink-2 mb-3">
        {title}
      </div>
      {children}
    </div>
  );
}

function Grid({ children }: { children: React.ReactNode }) {
  return (
    <div className="grid gap-3" style={{ gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))" }}>
      {children}
    </div>
  );
}

function Card({
  title,
  count,
  badge,
  children,
}: {
  title: string;
  count: number;
  badge?: string | undefined;
  children?: React.ReactNode;
}) {
  return (
    <div className="bg-bg-panel border border-hair-2 rounded-lg p-3">
      <div className="flex justify-between items-baseline mb-2">
        <div className="text-10.5 font-semibold uppercase tracking-wide-3 text-ink-2">
          {title}
        </div>
        <div className="font-mono text-16 font-semibold text-brand">{count}</div>
      </div>
      {badge && (
        <div className="text-10 font-mono text-ink-3 mb-1.5">{badge}</div>
      )}
      {children && <div className="flex flex-wrap gap-1.5 pt-1 border-t border-hair">{children}</div>}
    </div>
  );
}

function LineItem({ primary, secondary }: { primary: string; secondary?: string }) {
  return (
    <div className="w-full flex justify-between items-baseline text-11 py-0.5">
      <span className="text-ink-0 truncate mr-2">{primary}</span>
      {secondary && (
        <span className="font-mono text-10.5 text-ink-3 shrink-0">{secondary}</span>
      )}
    </div>
  );
}

function Tag({ children, tone }: { children: React.ReactNode; tone?: "violet" }) {
  const cls = tone === "violet" ? "bg-violet-dim text-violet" : "bg-bg-2 text-ink-1";
  return (
    <span className={`inline-flex items-center px-1.5 py-px rounded-sm font-mono text-10 ${cls}`}>
      {children}
    </span>
  );
}

function Stat({ label, value }: { label: string; value: number | undefined }) {
  return (
    <div>
      <div className="text-10 uppercase tracking-wide-4 text-bg-0/50">{label}</div>
      <div className="text-18 font-mono font-semibold text-brand">{value ?? "—"}</div>
    </div>
  );
}
