// Hawkeye Sterling — incident archetype library.
// Structured incident classifications the MLRO / control function draws on
// when an operational or compliance incident occurs. Each archetype carries
// severity, required notifications, minimum remediation tasks, and
// regulatory anchors.

export type IncidentSeverity = 'low' | 'medium' | 'high' | 'critical';

export interface Incident {
  id: string;
  title: string;
  severity: IncidentSeverity;
  description: string;
  notify: Array<'mlro' | 'senior_management' | 'board' | 'regulator' | 'fiu' | 'data_protection_officer'>;
  minimumRemediation: string[];
  regulatoryAnchors: string[];
}

export const INCIDENTS: Incident[] = [
  { id: 'inc_tipping_off_intercepted', title: 'Tipping-off egress intercepted', severity: 'high', description: 'Outbound communication with tipping-off indicators was blocked by the guard before transmission.', notify: ['mlro'], minimumRemediation: ['Preserve the blocked draft + audit-chain entry.', 'Substitute with neutral offboarding / status-only language.', 'Root-cause review: training gap vs process gap.'], regulatoryAnchors: ['FDL No.10/2025 Art.25', 'Charter P4'] },
  { id: 'inc_confirmed_sanctions_freeze', title: 'Confirmed sanctions freeze executed', severity: 'critical', description: 'Subject matched UN / OFAC / EU / UK / UAE EOCN list with two strong identifiers; assets frozen.', notify: ['mlro', 'senior_management', 'fiu', 'regulator'], minimumRemediation: ['Submit FFR via goAML within 5 business days.', 'Preserve reasoning chain + evidence in audit chain.', 'Confirm no tipping-off risk in subsequent customer comms.'], regulatoryAnchors: ['CR 74/2020 Art.4-7', 'UNSCR 1267/1373/1988'] },
  { id: 'inc_partial_match_unresolved', title: 'Partial match unresolved (PNMR)', severity: 'high', description: 'Partial name match could not be ruled out; PNMR filed.', notify: ['mlro'], minimumRemediation: ['File PNMR via goAML within 5 business days.', 'Capture disambiguation attempts in audit chain.'], regulatoryAnchors: ['CR 74/2020'] },
  { id: 'inc_str_filed', title: 'Suspicious transaction report filed', severity: 'high', description: 'STR filed against a customer or transaction.', notify: ['mlro'], minimumRemediation: ['Preserve supporting evidence.', 'No tipping-off in subsequent interactions.'], regulatoryAnchors: ['FATF R.20'] },
  { id: 'inc_four_eyes_violation', title: 'Four-eyes / separation-of-duties violation', severity: 'high', description: 'Submitter and approver (or two approvers) were the same user.', notify: ['mlro', 'senior_management'], minimumRemediation: ['Roll back the impacted disposition; re-submit under valid SoD.', 'Control testing uplift for next review cycle.'], regulatoryAnchors: ['CR 134/2025 Art.19', 'Charter structural'] },
  { id: 'inc_data_breach_subject_record', title: 'Data breach — subject record disclosed', severity: 'critical', description: 'Subject personal data disclosed to unauthorised party.', notify: ['mlro', 'data_protection_officer', 'senior_management'], minimumRemediation: ['Contain: access revocation, key rotation.', 'Notify UAE Data Office per PDPL timelines.', 'Evaluate notification to affected data subjects.', 'Incident report + lessons-learned.'], regulatoryAnchors: ['FDL 45/2021 (PDPL)'] },
  { id: 'inc_stale_sanctions_feed', title: 'Sanctions feed stale > 24h', severity: 'high', description: 'Sanctions list freshness SLA breached for more than 24 hours.', notify: ['mlro'], minimumRemediation: ['Stand up fallback feed or manual import.', 'Re-screen all onboarded and monitored customers against the refreshed list.', 'Root-cause review.'], regulatoryAnchors: ['Charter P8'] },
  { id: 'inc_screening_miss_root_cause', title: 'Screening miss identified in lookback', severity: 'high', description: 'Lookback review identified a subject who should have been flagged earlier.', notify: ['mlro', 'senior_management'], minimumRemediation: ['Remediate the specific case.', 'Update rule / model to catch the class.', 'Board-level reporting.'], regulatoryAnchors: ['FATF R.20'] },
  { id: 'inc_regulator_enquiry', title: 'Regulator enquiry received', severity: 'medium', description: 'Enquiry received from MoE / FIU / foreign FIU.', notify: ['mlro', 'senior_management'], minimumRemediation: ['Acknowledge within stated SLA.', 'Preserve and produce responsive records.'], regulatoryAnchors: ['CR 134/2025'] },
  { id: 'inc_insider_access_review_failed', title: 'Insider access review failed', severity: 'medium', description: 'Quarterly privileged-access review identifies entitlement creep or gap.', notify: ['mlro', 'senior_management'], minimumRemediation: ['Revoke stale entitlements.', 'Re-review with independent approver.'], regulatoryAnchors: ['Three Lines Model'] },
  { id: 'inc_vendor_outage_screening', title: 'Screening-vendor outage', severity: 'high', description: 'Primary screening vendor unavailable for longer than SLA.', notify: ['mlro', 'senior_management'], minimumRemediation: ['Invoke contingency / fallback vendor.', 'Operational continuity review.'], regulatoryAnchors: [] },
  { id: 'inc_false_positive_surge', title: 'False-positive surge', severity: 'medium', description: 'False-positive rate spikes material percentage above baseline.', notify: ['mlro'], minimumRemediation: ['Recalibrate matching thresholds.', 'Peer-group benchmark comparison.'], regulatoryAnchors: [] },
  { id: 'inc_audit_finding_repeat', title: 'Repeat audit finding', severity: 'high', description: 'Internal / external audit finding repeats from a prior cycle.', notify: ['mlro', 'senior_management', 'board'], minimumRemediation: ['Root-cause analysis; escalate to board committee.', 'Revised remediation plan with owner + due dates.'], regulatoryAnchors: ['Three Lines Model'] },
  { id: 'inc_sanction_regime_change', title: 'Sanction regime change', severity: 'medium', description: 'Material change (new EO, delisting, amendment) to a sanctions regime.', notify: ['mlro'], minimumRemediation: ['Refresh lists + re-screen affected portfolio.', 'Update policy references.'], regulatoryAnchors: [] },
  { id: 'inc_regulatory_deadline_missed', title: 'Regulatory deadline missed', severity: 'critical', description: 'Mandatory filing deadline missed (e.g. 5-business-day PNMR/FFR).', notify: ['mlro', 'senior_management', 'board'], minimumRemediation: ['Self-disclose where required.', 'Root-cause analysis.', 'Process hardening + automation review.'], regulatoryAnchors: ['CR 74/2020', 'FDL 10/2025'] },
  { id: 'inc_phishing_campaign_against_staff', title: 'Phishing campaign against staff', severity: 'medium', description: 'Credential-harvesting attempt targeting compliance / MLRO users.', notify: ['mlro', 'data_protection_officer'], minimumRemediation: ['Reset affected credentials; revoke active sessions.', 'Security awareness training refresh.'], regulatoryAnchors: [] },
  { id: 'inc_ubo_material_change', title: 'Material UBO change not disclosed', severity: 'medium', description: 'Material change in UBO discovered by subsequent review.', notify: ['mlro'], minimumRemediation: ['Re-run UBO resolver; update record.', 'Assess EDD uplift.'], regulatoryAnchors: ['FATF R.24'] },
  { id: 'inc_cahra_input_without_docs', title: 'CAHRA input accepted without OECD docs', severity: 'critical', description: 'Refinery accepted CAHRA-origin input without OECD Annex II evidence.', notify: ['mlro', 'senior_management', 'board'], minimumRemediation: ['Quarantine the input lot.', 'Remediate supply-chain diligence control.', 'Board-level reporting.'], regulatoryAnchors: ['OECD DDG Annex II', 'LBMA RGG'] },
  { id: 'inc_consultant_report_adverse', title: 'Adverse consultant / audit report', severity: 'high', description: 'External consultant or audit report identifies material control deficiency.', notify: ['mlro', 'senior_management', 'board'], minimumRemediation: ['Remediation plan with owner + date.', 'Interim mitigation where possible.'], regulatoryAnchors: [] },
  { id: 'inc_training_gap_exposed', title: 'Training gap exposed by incident', severity: 'low', description: 'Incident root-cause traces to staff lacking specific AML/CFT training.', notify: ['mlro'], minimumRemediation: ['Targeted refresher training.', 'Competency test before return to disposition duties.'], regulatoryAnchors: ['FATF R.18'] },

  // ── Wave 4 — AI governance & AI failure incidents ───────────────────
  { id: 'inc_ai_serious_incident_eu_72h', title: 'AI serious incident — EU AI Act 72h escalation', severity: 'critical', description: 'A high-risk AI system caused or threatens serious harm (rights, safety, property); EU AI Act requires reporting to the competent authority within 72 hours.', notify: ['mlro', 'senior_management', 'regulator', 'board'], minimumRemediation: ['File serious-incident notification within 72h.', 'Preserve decision logs, training-data manifest, model card.', 'Invoke kill-switch / rollback; stand up human-in-the-loop.', 'Root-cause analysis + post-mortem with drift / red-team evidence.'], regulatoryAnchors: ['EU AI Act Art.73', 'NIST AI RMF Manage'] },
  { id: 'inc_ai_prompt_injection_compromise', title: 'Prompt-injection / jailbreak compromise of AI system', severity: 'high', description: 'Deployed AI system exhibited behaviour consistent with successful prompt injection, jailbreak, or indirect-prompt exploit.', notify: ['mlro', 'senior_management'], minimumRemediation: ['Quarantine affected endpoints.', 'Patch input sanitisation / system-prompt guards.', 'Re-run red-team panel against OWASP LLM Top 10.', 'Notify customers if data exposure occurred.'], regulatoryAnchors: ['OWASP LLM Top 10', 'NIST AI RMF'] },
  { id: 'inc_ai_model_drift_undetected', title: 'Model drift / concept drift undetected until impact', severity: 'medium', description: 'Production AI model drifted materially from baseline without monitoring detection; downstream decisions affected.', notify: ['mlro', 'senior_management'], minimumRemediation: ['Re-calibrate or retrain; re-validate on holdout.', 'Stand up drift monitoring + alerting.', 'Compensating human review for the drift window.'], regulatoryAnchors: ['NIST AI RMF Measure', 'EU AI Act Art.15'] },
  { id: 'inc_ai_shadow_deployment_detected', title: 'Shadow-AI deployment detected', severity: 'medium', description: 'Business unit identified consuming generative-AI or agentic-AI services outside the AI registry / model inventory.', notify: ['mlro'], minimumRemediation: ['Register or decommission the system.', 'Retrospective risk / conformity assessment.', 'Access-control and egress-policy tightening.'], regulatoryAnchors: ['ISO/IEC 42001'] },
  { id: 'inc_ai_synthetic_media_fraud_confirmed', title: 'Confirmed synthetic-media / deepfake fraud attempt', severity: 'high', description: 'Confirmed deepfake, voice-clone, or AI-generated document used in a fraud attempt against the firm or customer.', notify: ['mlro', 'senior_management', 'fiu'], minimumRemediation: ['File STR if transaction attempted.', 'Update authentication controls (out-of-band for exec instructions).', 'Customer / staff awareness notice.'], regulatoryAnchors: ['FATF R.20'] },

  // ── Wave 4 — insider threat ─────────────────────────────────────────
  { id: 'inc_insider_ip_exfil_confirmed', title: 'Confirmed insider IP / trade-secret exfiltration', severity: 'critical', description: 'Evidence-backed confirmation that a current or former privileged user exfiltrated IP, trade secrets, or sensitive data.', notify: ['mlro', 'senior_management', 'board', 'data_protection_officer'], minimumRemediation: ['Preserve forensic image + chain-of-custody.', 'Containment: access revocation, credential rotation, DLP tightening.', 'Legal action + law-enforcement referral where appropriate.', 'Post-mortem: detection-gap analysis and control uplift.'], regulatoryAnchors: ['Three Lines Model'] },

  // ── Wave 4 — environmental crime (FATF R.3 2021 predicate) ──────────
  { id: 'inc_env_crime_predicate_triggered', title: 'Environmental-crime predicate triggered', severity: 'high', description: 'Screening / monitoring linked a financial flow to illegal mining, logging, fishing, or waste trafficking (FATF R.3 2021 predicate).', notify: ['mlro', 'senior_management'], minimumRemediation: ['File STR if suspicion confirmed.', 'Supply-chain diligence refresh; quarantine affected inputs.', 'CAHRA / provenance evidence review with OECD Annex II discipline.'], regulatoryAnchors: ['FATF R.3 (2021)', 'OECD DDG'] },

  // ── Wave 4 — carbon-market fraud ────────────────────────────────────
  { id: 'inc_carbon_vcm_fraud_confirmed', title: 'Confirmed carbon-credit / VCM fraud', severity: 'high', description: 'Confirmed phantom-credit, double-counting, or registry-mismatch carbon-market fraud affecting the firm or counterparty.', notify: ['mlro', 'senior_management'], minimumRemediation: ['File STR.', 'Unwind / quarantine affected credits; reconcile against issuing registry.', 'Policy refresh on VCM due-diligence.'], regulatoryAnchors: ['ICVCM Core Carbon Principles', 'FATF RBA'] },
];

export const INCIDENT_BY_ID: Map<string, Incident> = new Map(INCIDENTS.map((i) => [i.id, i]));
