// Hawkeye Sterling — full ISO-3166-1 jurisdiction registry.
// Factual public reference data only (ISO codes + names). Risk values are
// EXPECTED to be hydrated from primary sources at run-time (FATF, EU AMLD,
// Basel AML Index). Per charter P8, no risk value here is asserted from
// training data — every row carries `seedOnly: true` until refreshed.

export interface JurisdictionRow {
  iso2: string;
  iso3: string;
  name: string;
  region: 'Africa' | 'Americas' | 'Asia' | 'Europe' | 'Oceania' | 'Antarctic';
  seedOnly: boolean; // true until Phase-2 ingestion overwrites with current data
}

export const JURISDICTIONS_FULL: JurisdictionRow[] = [
  { iso2: 'AD', iso3: 'AND', name: 'Andorra', region: 'Europe', seedOnly: true },
  { iso2: 'AE', iso3: 'ARE', name: 'United Arab Emirates', region: 'Asia', seedOnly: true },
  { iso2: 'AF', iso3: 'AFG', name: 'Afghanistan', region: 'Asia', seedOnly: true },
  { iso2: 'AG', iso3: 'ATG', name: 'Antigua and Barbuda', region: 'Americas', seedOnly: true },
  { iso2: 'AI', iso3: 'AIA', name: 'Anguilla', region: 'Americas', seedOnly: true },
  { iso2: 'AL', iso3: 'ALB', name: 'Albania', region: 'Europe', seedOnly: true },
  { iso2: 'AM', iso3: 'ARM', name: 'Armenia', region: 'Asia', seedOnly: true },
  { iso2: 'AO', iso3: 'AGO', name: 'Angola', region: 'Africa', seedOnly: true },
  { iso2: 'AQ', iso3: 'ATA', name: 'Antarctica', region: 'Antarctic', seedOnly: true },
  { iso2: 'AR', iso3: 'ARG', name: 'Argentina', region: 'Americas', seedOnly: true },
  { iso2: 'AS', iso3: 'ASM', name: 'American Samoa', region: 'Oceania', seedOnly: true },
  { iso2: 'AT', iso3: 'AUT', name: 'Austria', region: 'Europe', seedOnly: true },
  { iso2: 'AU', iso3: 'AUS', name: 'Australia', region: 'Oceania', seedOnly: true },
  { iso2: 'AW', iso3: 'ABW', name: 'Aruba', region: 'Americas', seedOnly: true },
  { iso2: 'AX', iso3: 'ALA', name: 'Åland Islands', region: 'Europe', seedOnly: true },
  { iso2: 'AZ', iso3: 'AZE', name: 'Azerbaijan', region: 'Asia', seedOnly: true },
  { iso2: 'BA', iso3: 'BIH', name: 'Bosnia and Herzegovina', region: 'Europe', seedOnly: true },
  { iso2: 'BB', iso3: 'BRB', name: 'Barbados', region: 'Americas', seedOnly: true },
  { iso2: 'BD', iso3: 'BGD', name: 'Bangladesh', region: 'Asia', seedOnly: true },
  { iso2: 'BE', iso3: 'BEL', name: 'Belgium', region: 'Europe', seedOnly: true },
  { iso2: 'BF', iso3: 'BFA', name: 'Burkina Faso', region: 'Africa', seedOnly: true },
  { iso2: 'BG', iso3: 'BGR', name: 'Bulgaria', region: 'Europe', seedOnly: true },
  { iso2: 'BH', iso3: 'BHR', name: 'Bahrain', region: 'Asia', seedOnly: true },
  { iso2: 'BI', iso3: 'BDI', name: 'Burundi', region: 'Africa', seedOnly: true },
  { iso2: 'BJ', iso3: 'BEN', name: 'Benin', region: 'Africa', seedOnly: true },
  { iso2: 'BL', iso3: 'BLM', name: 'Saint Barthélemy', region: 'Americas', seedOnly: true },
  { iso2: 'BM', iso3: 'BMU', name: 'Bermuda', region: 'Americas', seedOnly: true },
  { iso2: 'BN', iso3: 'BRN', name: 'Brunei Darussalam', region: 'Asia', seedOnly: true },
  { iso2: 'BO', iso3: 'BOL', name: 'Bolivia', region: 'Americas', seedOnly: true },
  { iso2: 'BQ', iso3: 'BES', name: 'Bonaire, Sint Eustatius and Saba', region: 'Americas', seedOnly: true },
  { iso2: 'BR', iso3: 'BRA', name: 'Brazil', region: 'Americas', seedOnly: true },
  { iso2: 'BS', iso3: 'BHS', name: 'Bahamas', region: 'Americas', seedOnly: true },
  { iso2: 'BT', iso3: 'BTN', name: 'Bhutan', region: 'Asia', seedOnly: true },
  { iso2: 'BV', iso3: 'BVT', name: 'Bouvet Island', region: 'Antarctic', seedOnly: true },
  { iso2: 'BW', iso3: 'BWA', name: 'Botswana', region: 'Africa', seedOnly: true },
  { iso2: 'BY', iso3: 'BLR', name: 'Belarus', region: 'Europe', seedOnly: true },
  { iso2: 'BZ', iso3: 'BLZ', name: 'Belize', region: 'Americas', seedOnly: true },
  { iso2: 'CA', iso3: 'CAN', name: 'Canada', region: 'Americas', seedOnly: true },
  { iso2: 'CC', iso3: 'CCK', name: 'Cocos (Keeling) Islands', region: 'Oceania', seedOnly: true },
  { iso2: 'CD', iso3: 'COD', name: 'Democratic Republic of the Congo', region: 'Africa', seedOnly: true },
  { iso2: 'CF', iso3: 'CAF', name: 'Central African Republic', region: 'Africa', seedOnly: true },
  { iso2: 'CG', iso3: 'COG', name: 'Republic of the Congo', region: 'Africa', seedOnly: true },
  { iso2: 'CH', iso3: 'CHE', name: 'Switzerland', region: 'Europe', seedOnly: true },
  { iso2: 'CI', iso3: 'CIV', name: 'Côte d’Ivoire', region: 'Africa', seedOnly: true },
  { iso2: 'CK', iso3: 'COK', name: 'Cook Islands', region: 'Oceania', seedOnly: true },
  { iso2: 'CL', iso3: 'CHL', name: 'Chile', region: 'Americas', seedOnly: true },
  { iso2: 'CM', iso3: 'CMR', name: 'Cameroon', region: 'Africa', seedOnly: true },
  { iso2: 'CN', iso3: 'CHN', name: 'China', region: 'Asia', seedOnly: true },
  { iso2: 'CO', iso3: 'COL', name: 'Colombia', region: 'Americas', seedOnly: true },
  { iso2: 'CR', iso3: 'CRI', name: 'Costa Rica', region: 'Americas', seedOnly: true },
  { iso2: 'CU', iso3: 'CUB', name: 'Cuba', region: 'Americas', seedOnly: true },
  { iso2: 'CV', iso3: 'CPV', name: 'Cabo Verde', region: 'Africa', seedOnly: true },
  { iso2: 'CW', iso3: 'CUW', name: 'Curaçao', region: 'Americas', seedOnly: true },
  { iso2: 'CX', iso3: 'CXR', name: 'Christmas Island', region: 'Oceania', seedOnly: true },
  { iso2: 'CY', iso3: 'CYP', name: 'Cyprus', region: 'Europe', seedOnly: true },
  { iso2: 'CZ', iso3: 'CZE', name: 'Czechia', region: 'Europe', seedOnly: true },
  { iso2: 'DE', iso3: 'DEU', name: 'Germany', region: 'Europe', seedOnly: true },
  { iso2: 'DJ', iso3: 'DJI', name: 'Djibouti', region: 'Africa', seedOnly: true },
  { iso2: 'DK', iso3: 'DNK', name: 'Denmark', region: 'Europe', seedOnly: true },
  { iso2: 'DM', iso3: 'DMA', name: 'Dominica', region: 'Americas', seedOnly: true },
  { iso2: 'DO', iso3: 'DOM', name: 'Dominican Republic', region: 'Americas', seedOnly: true },
  { iso2: 'DZ', iso3: 'DZA', name: 'Algeria', region: 'Africa', seedOnly: true },
  { iso2: 'EC', iso3: 'ECU', name: 'Ecuador', region: 'Americas', seedOnly: true },
  { iso2: 'EE', iso3: 'EST', name: 'Estonia', region: 'Europe', seedOnly: true },
  { iso2: 'EG', iso3: 'EGY', name: 'Egypt', region: 'Africa', seedOnly: true },
  { iso2: 'EH', iso3: 'ESH', name: 'Western Sahara', region: 'Africa', seedOnly: true },
  { iso2: 'ER', iso3: 'ERI', name: 'Eritrea', region: 'Africa', seedOnly: true },
  { iso2: 'ES', iso3: 'ESP', name: 'Spain', region: 'Europe', seedOnly: true },
  { iso2: 'ET', iso3: 'ETH', name: 'Ethiopia', region: 'Africa', seedOnly: true },
  { iso2: 'FI', iso3: 'FIN', name: 'Finland', region: 'Europe', seedOnly: true },
  { iso2: 'FJ', iso3: 'FJI', name: 'Fiji', region: 'Oceania', seedOnly: true },
  { iso2: 'FK', iso3: 'FLK', name: 'Falkland Islands', region: 'Americas', seedOnly: true },
  { iso2: 'FM', iso3: 'FSM', name: 'Federated States of Micronesia', region: 'Oceania', seedOnly: true },
  { iso2: 'FO', iso3: 'FRO', name: 'Faroe Islands', region: 'Europe', seedOnly: true },
  { iso2: 'FR', iso3: 'FRA', name: 'France', region: 'Europe', seedOnly: true },
  { iso2: 'GA', iso3: 'GAB', name: 'Gabon', region: 'Africa', seedOnly: true },
  { iso2: 'GB', iso3: 'GBR', name: 'United Kingdom', region: 'Europe', seedOnly: true },
  { iso2: 'GD', iso3: 'GRD', name: 'Grenada', region: 'Americas', seedOnly: true },
  { iso2: 'GE', iso3: 'GEO', name: 'Georgia', region: 'Asia', seedOnly: true },
  { iso2: 'GF', iso3: 'GUF', name: 'French Guiana', region: 'Americas', seedOnly: true },
  { iso2: 'GG', iso3: 'GGY', name: 'Guernsey', region: 'Europe', seedOnly: true },
  { iso2: 'GH', iso3: 'GHA', name: 'Ghana', region: 'Africa', seedOnly: true },
  { iso2: 'GI', iso3: 'GIB', name: 'Gibraltar', region: 'Europe', seedOnly: true },
  { iso2: 'GL', iso3: 'GRL', name: 'Greenland', region: 'Americas', seedOnly: true },
  { iso2: 'GM', iso3: 'GMB', name: 'Gambia', region: 'Africa', seedOnly: true },
  { iso2: 'GN', iso3: 'GIN', name: 'Guinea', region: 'Africa', seedOnly: true },
  { iso2: 'GP', iso3: 'GLP', name: 'Guadeloupe', region: 'Americas', seedOnly: true },
  { iso2: 'GQ', iso3: 'GNQ', name: 'Equatorial Guinea', region: 'Africa', seedOnly: true },
  { iso2: 'GR', iso3: 'GRC', name: 'Greece', region: 'Europe', seedOnly: true },
  { iso2: 'GS', iso3: 'SGS', name: 'South Georgia and the South Sandwich Islands', region: 'Antarctic', seedOnly: true },
  { iso2: 'GT', iso3: 'GTM', name: 'Guatemala', region: 'Americas', seedOnly: true },
  { iso2: 'GU', iso3: 'GUM', name: 'Guam', region: 'Oceania', seedOnly: true },
  { iso2: 'GW', iso3: 'GNB', name: 'Guinea-Bissau', region: 'Africa', seedOnly: true },
  { iso2: 'GY', iso3: 'GUY', name: 'Guyana', region: 'Americas', seedOnly: true },
  { iso2: 'HK', iso3: 'HKG', name: 'Hong Kong', region: 'Asia', seedOnly: true },
  { iso2: 'HM', iso3: 'HMD', name: 'Heard Island and McDonald Islands', region: 'Antarctic', seedOnly: true },
  { iso2: 'HN', iso3: 'HND', name: 'Honduras', region: 'Americas', seedOnly: true },
  { iso2: 'HR', iso3: 'HRV', name: 'Croatia', region: 'Europe', seedOnly: true },
  { iso2: 'HT', iso3: 'HTI', name: 'Haiti', region: 'Americas', seedOnly: true },
  { iso2: 'HU', iso3: 'HUN', name: 'Hungary', region: 'Europe', seedOnly: true },
  { iso2: 'ID', iso3: 'IDN', name: 'Indonesia', region: 'Asia', seedOnly: true },
  { iso2: 'IE', iso3: 'IRL', name: 'Ireland', region: 'Europe', seedOnly: true },
  { iso2: 'IL', iso3: 'ISR', name: 'Israel', region: 'Asia', seedOnly: true },
  { iso2: 'IM', iso3: 'IMN', name: 'Isle of Man', region: 'Europe', seedOnly: true },
  { iso2: 'IN', iso3: 'IND', name: 'India', region: 'Asia', seedOnly: true },
  { iso2: 'IO', iso3: 'IOT', name: 'British Indian Ocean Territory', region: 'Asia', seedOnly: true },
  { iso2: 'IQ', iso3: 'IRQ', name: 'Iraq', region: 'Asia', seedOnly: true },
  { iso2: 'IR', iso3: 'IRN', name: 'Iran', region: 'Asia', seedOnly: true },
  { iso2: 'IS', iso3: 'ISL', name: 'Iceland', region: 'Europe', seedOnly: true },
  { iso2: 'IT', iso3: 'ITA', name: 'Italy', region: 'Europe', seedOnly: true },
  { iso2: 'JE', iso3: 'JEY', name: 'Jersey', region: 'Europe', seedOnly: true },
  { iso2: 'JM', iso3: 'JAM', name: 'Jamaica', region: 'Americas', seedOnly: true },
  { iso2: 'JO', iso3: 'JOR', name: 'Jordan', region: 'Asia', seedOnly: true },
  { iso2: 'JP', iso3: 'JPN', name: 'Japan', region: 'Asia', seedOnly: true },
  { iso2: 'KE', iso3: 'KEN', name: 'Kenya', region: 'Africa', seedOnly: true },
  { iso2: 'KG', iso3: 'KGZ', name: 'Kyrgyzstan', region: 'Asia', seedOnly: true },
  { iso2: 'KH', iso3: 'KHM', name: 'Cambodia', region: 'Asia', seedOnly: true },
  { iso2: 'KI', iso3: 'KIR', name: 'Kiribati', region: 'Oceania', seedOnly: true },
  { iso2: 'KM', iso3: 'COM', name: 'Comoros', region: 'Africa', seedOnly: true },
  { iso2: 'KN', iso3: 'KNA', name: 'Saint Kitts and Nevis', region: 'Americas', seedOnly: true },
  { iso2: 'KP', iso3: 'PRK', name: 'Democratic People’s Republic of Korea', region: 'Asia', seedOnly: true },
  { iso2: 'KR', iso3: 'KOR', name: 'Republic of Korea', region: 'Asia', seedOnly: true },
  { iso2: 'KW', iso3: 'KWT', name: 'Kuwait', region: 'Asia', seedOnly: true },
  { iso2: 'KY', iso3: 'CYM', name: 'Cayman Islands', region: 'Americas', seedOnly: true },
  { iso2: 'KZ', iso3: 'KAZ', name: 'Kazakhstan', region: 'Asia', seedOnly: true },
  { iso2: 'LA', iso3: 'LAO', name: 'Lao People’s Democratic Republic', region: 'Asia', seedOnly: true },
  { iso2: 'LB', iso3: 'LBN', name: 'Lebanon', region: 'Asia', seedOnly: true },
  { iso2: 'LC', iso3: 'LCA', name: 'Saint Lucia', region: 'Americas', seedOnly: true },
  { iso2: 'LI', iso3: 'LIE', name: 'Liechtenstein', region: 'Europe', seedOnly: true },
  { iso2: 'LK', iso3: 'LKA', name: 'Sri Lanka', region: 'Asia', seedOnly: true },
  { iso2: 'LR', iso3: 'LBR', name: 'Liberia', region: 'Africa', seedOnly: true },
  { iso2: 'LS', iso3: 'LSO', name: 'Lesotho', region: 'Africa', seedOnly: true },
  { iso2: 'LT', iso3: 'LTU', name: 'Lithuania', region: 'Europe', seedOnly: true },
  { iso2: 'LU', iso3: 'LUX', name: 'Luxembourg', region: 'Europe', seedOnly: true },
  { iso2: 'LV', iso3: 'LVA', name: 'Latvia', region: 'Europe', seedOnly: true },
  { iso2: 'LY', iso3: 'LBY', name: 'Libya', region: 'Africa', seedOnly: true },
  { iso2: 'MA', iso3: 'MAR', name: 'Morocco', region: 'Africa', seedOnly: true },
  { iso2: 'MC', iso3: 'MCO', name: 'Monaco', region: 'Europe', seedOnly: true },
  { iso2: 'MD', iso3: 'MDA', name: 'Moldova', region: 'Europe', seedOnly: true },
  { iso2: 'ME', iso3: 'MNE', name: 'Montenegro', region: 'Europe', seedOnly: true },
  { iso2: 'MF', iso3: 'MAF', name: 'Saint Martin (French part)', region: 'Americas', seedOnly: true },
  { iso2: 'MG', iso3: 'MDG', name: 'Madagascar', region: 'Africa', seedOnly: true },
  { iso2: 'MH', iso3: 'MHL', name: 'Marshall Islands', region: 'Oceania', seedOnly: true },
  { iso2: 'MK', iso3: 'MKD', name: 'North Macedonia', region: 'Europe', seedOnly: true },
  { iso2: 'ML', iso3: 'MLI', name: 'Mali', region: 'Africa', seedOnly: true },
  { iso2: 'MM', iso3: 'MMR', name: 'Myanmar', region: 'Asia', seedOnly: true },
  { iso2: 'MN', iso3: 'MNG', name: 'Mongolia', region: 'Asia', seedOnly: true },
  { iso2: 'MO', iso3: 'MAC', name: 'Macao', region: 'Asia', seedOnly: true },
  { iso2: 'MP', iso3: 'MNP', name: 'Northern Mariana Islands', region: 'Oceania', seedOnly: true },
  { iso2: 'MQ', iso3: 'MTQ', name: 'Martinique', region: 'Americas', seedOnly: true },
  { iso2: 'MR', iso3: 'MRT', name: 'Mauritania', region: 'Africa', seedOnly: true },
  { iso2: 'MS', iso3: 'MSR', name: 'Montserrat', region: 'Americas', seedOnly: true },
  { iso2: 'MT', iso3: 'MLT', name: 'Malta', region: 'Europe', seedOnly: true },
  { iso2: 'MU', iso3: 'MUS', name: 'Mauritius', region: 'Africa', seedOnly: true },
  { iso2: 'MV', iso3: 'MDV', name: 'Maldives', region: 'Asia', seedOnly: true },
  { iso2: 'MW', iso3: 'MWI', name: 'Malawi', region: 'Africa', seedOnly: true },
  { iso2: 'MX', iso3: 'MEX', name: 'Mexico', region: 'Americas', seedOnly: true },
  { iso2: 'MY', iso3: 'MYS', name: 'Malaysia', region: 'Asia', seedOnly: true },
  { iso2: 'MZ', iso3: 'MOZ', name: 'Mozambique', region: 'Africa', seedOnly: true },
  { iso2: 'NA', iso3: 'NAM', name: 'Namibia', region: 'Africa', seedOnly: true },
  { iso2: 'NC', iso3: 'NCL', name: 'New Caledonia', region: 'Oceania', seedOnly: true },
  { iso2: 'NE', iso3: 'NER', name: 'Niger', region: 'Africa', seedOnly: true },
  { iso2: 'NF', iso3: 'NFK', name: 'Norfolk Island', region: 'Oceania', seedOnly: true },
  { iso2: 'NG', iso3: 'NGA', name: 'Nigeria', region: 'Africa', seedOnly: true },
  { iso2: 'NI', iso3: 'NIC', name: 'Nicaragua', region: 'Americas', seedOnly: true },
  { iso2: 'NL', iso3: 'NLD', name: 'Netherlands', region: 'Europe', seedOnly: true },
  { iso2: 'NO', iso3: 'NOR', name: 'Norway', region: 'Europe', seedOnly: true },
  { iso2: 'NP', iso3: 'NPL', name: 'Nepal', region: 'Asia', seedOnly: true },
  { iso2: 'NR', iso3: 'NRU', name: 'Nauru', region: 'Oceania', seedOnly: true },
  { iso2: 'NU', iso3: 'NIU', name: 'Niue', region: 'Oceania', seedOnly: true },
  { iso2: 'NZ', iso3: 'NZL', name: 'New Zealand', region: 'Oceania', seedOnly: true },
  { iso2: 'OM', iso3: 'OMN', name: 'Oman', region: 'Asia', seedOnly: true },
  { iso2: 'PA', iso3: 'PAN', name: 'Panama', region: 'Americas', seedOnly: true },
  { iso2: 'PE', iso3: 'PER', name: 'Peru', region: 'Americas', seedOnly: true },
  { iso2: 'PF', iso3: 'PYF', name: 'French Polynesia', region: 'Oceania', seedOnly: true },
  { iso2: 'PG', iso3: 'PNG', name: 'Papua New Guinea', region: 'Oceania', seedOnly: true },
  { iso2: 'PH', iso3: 'PHL', name: 'Philippines', region: 'Asia', seedOnly: true },
  { iso2: 'PK', iso3: 'PAK', name: 'Pakistan', region: 'Asia', seedOnly: true },
  { iso2: 'PL', iso3: 'POL', name: 'Poland', region: 'Europe', seedOnly: true },
  { iso2: 'PM', iso3: 'SPM', name: 'Saint Pierre and Miquelon', region: 'Americas', seedOnly: true },
  { iso2: 'PN', iso3: 'PCN', name: 'Pitcairn', region: 'Oceania', seedOnly: true },
  { iso2: 'PR', iso3: 'PRI', name: 'Puerto Rico', region: 'Americas', seedOnly: true },
  { iso2: 'PS', iso3: 'PSE', name: 'State of Palestine', region: 'Asia', seedOnly: true },
  { iso2: 'PT', iso3: 'PRT', name: 'Portugal', region: 'Europe', seedOnly: true },
  { iso2: 'PW', iso3: 'PLW', name: 'Palau', region: 'Oceania', seedOnly: true },
  { iso2: 'PY', iso3: 'PRY', name: 'Paraguay', region: 'Americas', seedOnly: true },
  { iso2: 'QA', iso3: 'QAT', name: 'Qatar', region: 'Asia', seedOnly: true },
  { iso2: 'RE', iso3: 'REU', name: 'Réunion', region: 'Africa', seedOnly: true },
  { iso2: 'RO', iso3: 'ROU', name: 'Romania', region: 'Europe', seedOnly: true },
  { iso2: 'RS', iso3: 'SRB', name: 'Serbia', region: 'Europe', seedOnly: true },
  { iso2: 'RU', iso3: 'RUS', name: 'Russian Federation', region: 'Europe', seedOnly: true },
  { iso2: 'RW', iso3: 'RWA', name: 'Rwanda', region: 'Africa', seedOnly: true },
  { iso2: 'SA', iso3: 'SAU', name: 'Saudi Arabia', region: 'Asia', seedOnly: true },
  { iso2: 'SB', iso3: 'SLB', name: 'Solomon Islands', region: 'Oceania', seedOnly: true },
  { iso2: 'SC', iso3: 'SYC', name: 'Seychelles', region: 'Africa', seedOnly: true },
  { iso2: 'SD', iso3: 'SDN', name: 'Sudan', region: 'Africa', seedOnly: true },
  { iso2: 'SE', iso3: 'SWE', name: 'Sweden', region: 'Europe', seedOnly: true },
  { iso2: 'SG', iso3: 'SGP', name: 'Singapore', region: 'Asia', seedOnly: true },
  { iso2: 'SH', iso3: 'SHN', name: 'Saint Helena', region: 'Africa', seedOnly: true },
  { iso2: 'SI', iso3: 'SVN', name: 'Slovenia', region: 'Europe', seedOnly: true },
  { iso2: 'SJ', iso3: 'SJM', name: 'Svalbard and Jan Mayen', region: 'Europe', seedOnly: true },
  { iso2: 'SK', iso3: 'SVK', name: 'Slovakia', region: 'Europe', seedOnly: true },
  { iso2: 'SL', iso3: 'SLE', name: 'Sierra Leone', region: 'Africa', seedOnly: true },
  { iso2: 'SM', iso3: 'SMR', name: 'San Marino', region: 'Europe', seedOnly: true },
  { iso2: 'SN', iso3: 'SEN', name: 'Senegal', region: 'Africa', seedOnly: true },
  { iso2: 'SO', iso3: 'SOM', name: 'Somalia', region: 'Africa', seedOnly: true },
  { iso2: 'SR', iso3: 'SUR', name: 'Suriname', region: 'Americas', seedOnly: true },
  { iso2: 'SS', iso3: 'SSD', name: 'South Sudan', region: 'Africa', seedOnly: true },
  { iso2: 'ST', iso3: 'STP', name: 'Sao Tome and Principe', region: 'Africa', seedOnly: true },
  { iso2: 'SV', iso3: 'SLV', name: 'El Salvador', region: 'Americas', seedOnly: true },
  { iso2: 'SX', iso3: 'SXM', name: 'Sint Maarten (Dutch part)', region: 'Americas', seedOnly: true },
  { iso2: 'SY', iso3: 'SYR', name: 'Syrian Arab Republic', region: 'Asia', seedOnly: true },
  { iso2: 'SZ', iso3: 'SWZ', name: 'Eswatini', region: 'Africa', seedOnly: true },
  { iso2: 'TC', iso3: 'TCA', name: 'Turks and Caicos Islands', region: 'Americas', seedOnly: true },
  { iso2: 'TD', iso3: 'TCD', name: 'Chad', region: 'Africa', seedOnly: true },
  { iso2: 'TF', iso3: 'ATF', name: 'French Southern Territories', region: 'Antarctic', seedOnly: true },
  { iso2: 'TG', iso3: 'TGO', name: 'Togo', region: 'Africa', seedOnly: true },
  { iso2: 'TH', iso3: 'THA', name: 'Thailand', region: 'Asia', seedOnly: true },
  { iso2: 'TJ', iso3: 'TJK', name: 'Tajikistan', region: 'Asia', seedOnly: true },
  { iso2: 'TK', iso3: 'TKL', name: 'Tokelau', region: 'Oceania', seedOnly: true },
  { iso2: 'TL', iso3: 'TLS', name: 'Timor-Leste', region: 'Asia', seedOnly: true },
  { iso2: 'TM', iso3: 'TKM', name: 'Turkmenistan', region: 'Asia', seedOnly: true },
  { iso2: 'TN', iso3: 'TUN', name: 'Tunisia', region: 'Africa', seedOnly: true },
  { iso2: 'TO', iso3: 'TON', name: 'Tonga', region: 'Oceania', seedOnly: true },
  { iso2: 'TR', iso3: 'TUR', name: 'Türkiye', region: 'Asia', seedOnly: true },
  { iso2: 'TT', iso3: 'TTO', name: 'Trinidad and Tobago', region: 'Americas', seedOnly: true },
  { iso2: 'TV', iso3: 'TUV', name: 'Tuvalu', region: 'Oceania', seedOnly: true },
  { iso2: 'TW', iso3: 'TWN', name: 'Taiwan', region: 'Asia', seedOnly: true },
  { iso2: 'TZ', iso3: 'TZA', name: 'United Republic of Tanzania', region: 'Africa', seedOnly: true },
  { iso2: 'UA', iso3: 'UKR', name: 'Ukraine', region: 'Europe', seedOnly: true },
  { iso2: 'UG', iso3: 'UGA', name: 'Uganda', region: 'Africa', seedOnly: true },
  { iso2: 'UM', iso3: 'UMI', name: 'United States Minor Outlying Islands', region: 'Oceania', seedOnly: true },
  { iso2: 'US', iso3: 'USA', name: 'United States of America', region: 'Americas', seedOnly: true },
  { iso2: 'UY', iso3: 'URY', name: 'Uruguay', region: 'Americas', seedOnly: true },
  { iso2: 'UZ', iso3: 'UZB', name: 'Uzbekistan', region: 'Asia', seedOnly: true },
  { iso2: 'VA', iso3: 'VAT', name: 'Holy See', region: 'Europe', seedOnly: true },
  { iso2: 'VC', iso3: 'VCT', name: 'Saint Vincent and the Grenadines', region: 'Americas', seedOnly: true },
  { iso2: 'VE', iso3: 'VEN', name: 'Venezuela', region: 'Americas', seedOnly: true },
  { iso2: 'VG', iso3: 'VGB', name: 'British Virgin Islands', region: 'Americas', seedOnly: true },
  { iso2: 'VI', iso3: 'VIR', name: 'United States Virgin Islands', region: 'Americas', seedOnly: true },
  { iso2: 'VN', iso3: 'VNM', name: 'Viet Nam', region: 'Asia', seedOnly: true },
  { iso2: 'VU', iso3: 'VUT', name: 'Vanuatu', region: 'Oceania', seedOnly: true },
  { iso2: 'WF', iso3: 'WLF', name: 'Wallis and Futuna', region: 'Oceania', seedOnly: true },
  { iso2: 'WS', iso3: 'WSM', name: 'Samoa', region: 'Oceania', seedOnly: true },
  { iso2: 'YE', iso3: 'YEM', name: 'Yemen', region: 'Asia', seedOnly: true },
  { iso2: 'YT', iso3: 'MYT', name: 'Mayotte', region: 'Africa', seedOnly: true },
  { iso2: 'ZA', iso3: 'ZAF', name: 'South Africa', region: 'Africa', seedOnly: true },
  { iso2: 'ZM', iso3: 'ZMB', name: 'Zambia', region: 'Africa', seedOnly: true },
  { iso2: 'ZW', iso3: 'ZWE', name: 'Zimbabwe', region: 'Africa', seedOnly: true },

  // ── AML-relevant financial centres (non-ISO-3166-1, X-prefix reserved) ──
  // These are FSRA/regulatory-recognised free zones and international financial
  // centres that have their own AML/CFT frameworks distinct from the host state.
  { iso2: 'XA', iso3: 'ADG', name: 'Abu Dhabi Global Market (ADGM)', region: 'Asia', seedOnly: true },
  { iso2: 'XD', iso3: 'DIF', name: 'Dubai International Financial Centre (DIFC)', region: 'Asia', seedOnly: true },
  { iso2: 'XJ', iso3: 'JAF', name: 'Jebel Ali Free Zone (JAFZA)', region: 'Asia', seedOnly: true },
  { iso2: 'XQ', iso3: 'DAF', name: 'Dubai Airport Free Zone (DAFZA)', region: 'Asia', seedOnly: true },
  { iso2: 'XG', iso3: 'GIF', name: 'GIFT City International Financial Services Centre (India)', region: 'Asia', seedOnly: true },
  { iso2: 'XI', iso3: 'IFS', name: 'IFSC Dublin (International Financial Services Centre, Ireland)', region: 'Europe', seedOnly: true },
  { iso2: 'XL', iso3: 'LFC', name: 'Luxembourg Fund Centre', region: 'Europe', seedOnly: true },
  { iso2: 'XM', iso3: 'MFX', name: 'Malta Financial Services Authority jurisdiction', region: 'Europe', seedOnly: true },
  { iso2: 'XK', iso3: 'KAI', name: 'Labuan International Business and Financial Centre (Malaysia)', region: 'Asia', seedOnly: true },
  { iso2: 'XB', iso3: 'BCX', name: 'Bahrain Financial Harbour / BIBF', region: 'Asia', seedOnly: true },
  { iso2: 'XR', iso3: 'QFC', name: 'Qatar Financial Centre (QFC)', region: 'Asia', seedOnly: true },
  { iso2: 'XW', iso3: 'KWX', name: 'Kuwait Finance House Regulatory Zone', region: 'Asia', seedOnly: true },
  { iso2: 'XN', iso3: 'NAI', name: 'Nauru Special Financial Zone', region: 'Oceania', seedOnly: true },
  { iso2: 'XP', iso3: 'PAM', name: 'Panama City International Banking Centre', region: 'Americas', seedOnly: true },
  { iso2: 'XV', iso3: 'VGX', name: 'BVI Financial Services Commission jurisdiction', region: 'Americas', seedOnly: true },
];

export const JURISDICTION_BY_ISO2: Map<string, JurisdictionRow> = new Map(
  JURISDICTIONS_FULL.map((j) => [j.iso2, j]),
);
export const JURISDICTION_BY_ISO3: Map<string, JurisdictionRow> = new Map(
  JURISDICTIONS_FULL.map((j) => [j.iso3, j]),
);
export function jurisdictionByName(name: string): JurisdictionRow | undefined {
  const n = name.trim().toLowerCase();
  return JURISDICTIONS_FULL.find((j) => j.name.toLowerCase() === n);
}
