// Hawkeye Sterling — MLRO Deep-Reasoning mode catalogue (typed mirror).
// Source: public/deep-reasoning.js (compliance-analyzer reference,
// 690 modes). Categorisation computed statically for the
// searchable picker. Prefixes live verbatim in the JS file so the
// browser ships the reference byte-for-byte.

export const MLRO_MODE_IDS = [
  'advance_fee',
  'adversarial_collaboration',
  'adversarial_debate',
  'adverse_media_source_tier',
  'adverse_media_tiering',
  'adverse_media_triage',
  'ai_governance',
  'analogical',
  'analogical_precedent',
  'anchoring_avoidance',
  'app_scam',
  'art_dealer',
  'art_hvg',
  'article_by_article',
  'attack_tree',
  'audit_data_integrity',
  'audit_data_sampling',
  'audit_finding_open',
  'audit_finding_remediation',
  'audit_independent_assurance',
  'audit_independent_engagement',
  'audit_lookback',
  'audit_lookback_sample',
  'audit_trail_reconstruction',
  'availability_check',
  'bayes_theorem',
  'bayesian',
  'bayesian_network',
  'bearer_shares',
  'bec_fraud',
  'beneficial_transfer',
  'bowtie',
  'break_even',
  'bridge_risk',
  'bullion_cross_border_transit',
  'bullion_dgd_refiner_deaccred',
  'bullion_dore_drc_asm',
  'bullion_good_delivery_dispute',
  'bullion_hallmark_mismatch',
  'bullion_letter_box_supplier',
  'bullion_letter_of_credit_gold',
  'bullion_refiner_recycled_scrap',
  'bullion_vault_custody_transfer',
  'bullion_wholesale_loco_split',
  'burden_of_proof',
  'cabinet_res_walk',
  'cahra_supplier',
  'cash_courier_ctn',
  'causal',
  'causal_inference',
  'cb_bni_undeclared',
  'cb_border_declaration_history_gap',
  'cb_cash_smuggle_concealed',
  'cb_crypto_to_cash_offramp',
  'cb_diplomatic_carrier',
  'cb_freight_non_declaration',
  'cb_hawala_overlap',
  'cb_re_export_ftz_cash',
  'cdd_digital_onboarding',
  'cdd_legacy_upgrade',
  'cdd_non_resident',
  'cdd_ongoing_cadence',
  'cdd_prospect_entity',
  'cdd_prospect_individual',
  'cdd_refresh_trigger',
  'cdd_simplified_eligibility',
  'cdd_third_party_reliance',
  'cdd_tier',
  'cdd_walk_in',
  'centrality',
  'chain_analysis',
  'chain_of_verification',
  'charity_tf',
  'chi_square',
  'circular_walk',
  'cognitive_bias_audit',
  'collusion_pattern',
  'community_detection',
  'completeness_audit',
  'confidence_calibration',
  'confidence_interval',
  'conflict_interest',
  'contradiction',
  'control_effectiveness',
  'corresp_cbd_downstream_pep',
  'corresp_cbuae_standard_gap',
  'corresp_cover_payment_miss',
  'corresp_downstream_sanctions',
  'corresp_escrow_payment_block',
  'corresp_historical_exit',
  'corresp_nested_bank_flow',
  'corresp_nested_vasp',
  'corresp_payment_intermediary_strip',
  'corresp_shell_bank_suspected',
  'correspondent_kyc',
  'correspondent_risk',
  'cost_benefit',
  'counterexample_search',
  'counterfactual',
  'craac',
  'cross_case_triangulation',
  'cuckoo_smurf',
  'cuckoo_smurfing',
  'cvar',
  'data',
  'data_quality_score',
  'de_minimis',
  'decision_tree',
  'deep',
  'default_reasoning',
  'defence_in_depth',
  'defi_smart_contract',
  'deontic_logic',
  'dialectic',
  'discrepancy_log',
  'documentation_quality',
  'dpms_bullion_loco',
  'dpms_cross_border_physical',
  'dpms_ewra',
  'dpms_goaml_dpmsr',
  'dpms_hallmark_verification',
  'dpms_kpi_quarterly',
  'dpms_pawn_broker',
  'dpms_refiner_cahra',
  'dpms_retail_buyback',
  'dpms_retail_cash_courier',
  'dpms_retail_digital_gold',
  'dpms_retail_expatriate_cash',
  'dpms_retail_franchise_chain',
  'dpms_retail_golden_visa_shopper',
  'dpms_retail_micro_structure',
  'dpms_retail_rapid_resale',
  'dpms_retail_third_party_payer',
  'dpms_retail_threshold',
  'dpms_retail_wedding_batch',
  'dpms_scrap_gold',
  'dpms_threshold',
  'dpms_wholesale_invoice',
  'dual_process',
  'edd_adverse_media_triggered',
  'edd_cash_intensive',
  'edd_complex_structure',
  'edd_correspondent_triggered',
  'edd_high_risk_jurisdiction',
  'edd_pep_family',
  'edd_sanctions_adjacent',
  'edd_sanctions_dismiss_rationale',
  'edd_sof_transaction',
  'edd_sow',
  'edd_sow_scope',
  'edd_uplift_trigger',
  'effective_control_ubo',
  'emirate_jurisdiction',
  'ensemble',
  'entity_resolution',
  'entropy',
  'epistemic_logic',
  'escalation_trigger',
  'ethical_matrix',
  'evidence_graph',
  'exception_log',
  'exit_client_risk',
  'expected_utility',
  'fair',
  'family_office_signal',
  'fatf_effectiveness',
  'fermi',
  'filing_cnmr_freeze',
  'filing_ctr_aggregation',
  'filing_deadline',
  'filing_dpmsr_quarterly',
  'filing_retention_package',
  'filing_str_narrative',
  'first_principles',
  'fishbone',
  'five_pillars',
  'five_whys',
  'fmea',
  'fo_art_collection',
  'fo_art_freeport',
  'fo_concentrated_issuer',
  'fo_concentrated_position',
  'fo_cross_border_settlor',
  'fo_jet_charter',
  'fo_mfo_downstream_pep',
  'fo_multi_family',
  'fo_next_gen_governance',
  'fo_next_gen_politics',
  'fo_pep_patriarch',
  'fo_philanthropy',
  'fo_philanthropy_conduit',
  'fo_private_trust',
  'fo_ptc_veto',
  'fo_single_family',
  'fo_succession',
  'fo_trust_multi_jur',
  'fo_yacht_jet',
  'fo_yacht_spv_chain',
  'forensic',
  'four_eyes_rationale',
  'four_eyes_stress',
  'fourth_party_payment',
  'framing_check',
  'fraud_app_romance',
  'fraud_app_scam',
  'fraud_bec',
  'fraud_bec_redirect',
  'fraud_identity_theft',
  'fraud_identity_theft_breach',
  'fraud_investment_scam',
  'fraud_phoenix_supplier',
  'fraud_romance_scam',
  'fraud_synthetic_id',
  'fraud_synthetic_onboard',
  'free_zone_red_flags',
  'freeze_notification_chain',
  'frequentist',
  'freshness_check',
  'front_running',
  'fund_capital_call',
  'fund_capital_call_source',
  'fund_charter_redemption',
  'fund_crypto_vehicle',
  'fund_distribution',
  'fund_distribution_assignment',
  'fund_gp_carry',
  'fund_gp_carry_sharing',
  'fund_large_redemption',
  'fund_master_feeder',
  'fund_master_feeder_layers',
  'fund_nominee_investor',
  'fund_nominee_principal',
  'fund_secondary_interest',
  'fund_secondary_market',
  'fund_side_letter',
  'fund_side_letter_mfn',
  'fund_sub_fund',
  'fund_sub_fund_cross',
  'fund_tokenised_subscription',
  'fuzzy_logic',
  'ghost_employees',
  'gifting_charity_payout',
  'gold_dore_asm',
  'golden_visa',
  'golden_visa_nexus',
  'golden_visa_residency',
  'gov_board_attestation',
  'gov_board_oversight',
  'gov_change_notification',
  'gov_independent_audit',
  'gov_mlro_authority',
  'gov_policy_gap',
  'gov_policy_update_circular',
  'gov_risk_assessment_refresh',
  'gov_training_matrix',
  'gov_vendor_risk',
  'gray_zone_resolution',
  'grey_blacklist_jurisdiction',
  'grievance_whistleblower',
  'high_risk_jur_list',
  'hindsight_check',
  'hmm',
  'hypothesis_test',
  'incident_breach_containment',
  'incident_law_enforcement',
  'incident_lessons',
  'incident_lessons_learned',
  'incident_penalty_exposure',
  'incident_public_statement',
  'incident_regulator_request',
  'incident_remediation_plan',
  'incident_str_no_tipping',
  'incident_tipping_off_audit',
  'incident_whistleblower',
  'inference',
  'ins_annuity_large',
  'ins_annuity_lump_sum',
  'ins_broker_kyc_gap',
  'ins_claim_proceeds',
  'ins_claim_third_party',
  'ins_group_policy_mls',
  'ins_ils_bond',
  'ins_ils_investor',
  'ins_life_settlement',
  'ins_life_surrender',
  'ins_life_surrender_cash',
  'ins_pep_life',
  'ins_pep_policy',
  'ins_premium_top_up',
  'ins_reinsurance_route',
  'ins_reinsurance_xborder',
  'ins_sanctions_cedant',
  'ins_sanctions_nexus',
  'ins_single_premium',
  'insider_threat',
  'insurance_wrap',
  'inversion',
  'invoice_fraud',
  'irac',
  'jurisdiction_cascade',
  'kill_chain',
  'kl_divergence',
  'kpi_dpms_thirty',
  'kri_alignment',
  'kyb_strict',
  'lapping',
  'layering_stage',
  'lbma_rgg',
  'lbma_rgg_five_step',
  'legal_formalism',
  'lens_shift',
  'lineage',
  'linguistic_forensics',
  'link_analysis',
  'list_walk',
  'loss_aversion_check',
  'lux_art_dealer',
  'lux_art_private_sale',
  'lux_classic_car',
  'lux_classic_car_escrow',
  'lux_jewellery_export',
  'lux_jewellery_kimberley',
  'lux_watch_dealer',
  'lux_watch_serial',
  'lux_yacht_broker',
  'lux_yacht_broker_flow',
  'marginal',
  'market_churning',
  'market_churning_adv',
  'market_corner_bid',
  'market_cornering',
  'market_cross_venue',
  'market_front_run',
  'market_front_running',
  'market_insider',
  'market_insider_trade',
  'market_kiting',
  'market_kiting_corp',
  'market_manipulation',
  'market_painting',
  'market_painting_tape',
  'market_pnd',
  'market_pump_dump',
  'market_spoofing',
  'market_spoofing_pattern',
  'market_wash_circ',
  'market_wash_trade',
  'markov_chain',
  'maximin',
  'mdl',
  'meta',
  'mev_scan',
  'minimax',
  'minimum_viable_compliance',
  'mitre_attack',
  'mlro_ai_governance_self',
  'mlro_ai_self_audit',
  'mlro_annual_risk_assessment',
  'mlro_appointment',
  'mlro_board_quarter',
  'mlro_board_report',
  'mlro_ew_risk_assessment',
  'mlro_four_eyes',
  'mlro_four_eyes_reversal',
  'mlro_override',
  'mlro_override_front_office',
  'mlro_regulator_briefing',
  'mlro_regulator_meeting',
  'mlro_regulator_rfi_response',
  'mlro_rfi_scope',
  'mlro_risk_appetite_change',
  'mlro_str_draft_review',
  'mlro_str_review',
  'mlro_training_refresh',
  'mlro_training_rollout',
  'modal_logic',
  'modus_ponens',
  'modus_tollens',
  'moe_inspection_readiness',
  'monte_carlo',
  'motif_detection',
  'multi_jur_ubo',
  'multi_jurisdictional_ubo',
  'multi_regime_sanctions',
  'narrative_coherence',
  'nested_correspondent',
  'nested_correspondent_kycc',
  'nft_wash',
  'nlp_contextual',
  'nominee_director',
  'non_monotonic',
  'npo_anonymous_donor_spike',
  'npo_cash_courier_relief',
  'npo_charity_conflict_zone',
  'npo_crypto_donations',
  'npo_dual_registration',
  'npo_governance_collapse',
  'npo_medical_supplies_proliferation',
  'npo_pif_platform_layering',
  'npo_risk',
  'npo_sanctioned_beneficiary',
  'npo_tf_risk',
  'npo_trustee_pep',
  'occam',
  'occam_vs_conspiracy',
  'occams',
  'octave',
  'oecd_ddg_annex',
  'ontological',
  'ooda',
  'ops_alert_aging',
  'ops_alert_backlog',
  'ops_alert_triage',
  'ops_bcp_fault',
  'ops_dashboard_drift',
  'ops_dashboard_kpi',
  'ops_false_positive',
  'ops_logging_gap',
  'ops_model_validation',
  'ops_outsourced_ctl',
  'ops_outsourced_soc',
  'ops_pen_test_aml',
  'ops_pen_test_finding',
  'ops_rule_tuning',
  'ops_segmentation_drift',
  'ops_segmentation_model',
  'ops_tm_calibration',
  'ops_tm_threshold',
  'ops_tuning_governance',
  'outsourced_reliance',
  'overconfidence_check',
  'paraconsistent',
  'parallel',
  'pareto',
  'pasta',
  'pattern_of_life',
  'pay_agent_network',
  'pay_agent_network_kyc',
  'pay_bnpl_merchant',
  'pay_bnpl_merchant_chain',
  'pay_cross_border_rail',
  'pay_cross_border_rails',
  'pay_digital_wallet',
  'pay_instant_rail_fraud',
  'pay_instant_rail_spike',
  'pay_merchant_acquirer',
  'pay_merchant_chargeback',
  'pay_merchant_layering',
  'pay_msb_agent_onboard',
  'pay_msb_onboard',
  'pay_pix_equiv',
  'pay_pix_equiv_scam',
  'pay_prepaid_card',
  'pay_prepaid_program',
  'pay_wallet_velocity',
  'payment_originator_info',
  'peer_benchmark',
  'peer_group_anomaly',
  'pep_cash_onboarding',
  'pep_domestic_minister',
  'pep_edd',
  'pep_escrow_structure',
  'pep_family_extension',
  'pep_former_official_decay',
  'pep_international_org',
  'pep_onboarding',
  'pep_political_transition',
  'pep_rca',
  'pep_rca_nephew',
  'pep_secondary_title',
  'pep_wolfsberg_cert',
  'pestle',
  'pf_dual_use',
  'pf_dual_use_controls',
  'pf_dual_use_goods',
  'phoenix_company',
  'planning_fallacy',
  'policy_drift',
  'policy_vs_rule',
  'ponzi_scheme',
  'popper_falsification',
  'porter_adapted',
  'portfolio_view',
  'post_mortem',
  'pre_mortem',
  'predicate_logic',
  'presumption_innocence',
  'principle_based',
  'privacy_coin',
  'privacy_coin_reasoning',
  'probabilistic_logic',
  'proportionality_test',
  'propositional_logic',
  'provenance_trace',
  'purposive',
  're_agent_dd',
  're_cash_purchase',
  're_cash_villa',
  're_goldenvisa_invest',
  're_intra_family_transfer',
  're_offplan_payer_switch',
  're_offplan_payment_plan',
  're_rapid_resale',
  're_reit_flow',
  're_reit_large_investor',
  're_sponsor_upstream',
  're_transfer_family',
  'real_estate_cash',
  'real_options',
  'reconciliation',
  'red_flags',
  'red_team',
  'reductio',
  'reflective',
  'refresher_cadence',
  'regime_change',
  'regression',
  'regret_min',
  'regulatory_mapping',
  'residual_vs_inherent',
  'retention_audit',
  'risk_adjusted',
  'risk_appetite_check',
  'risk_based_approach',
  'rogerian',
  'round_trip_hk',
  'round_tripping',
  'sanc_ambiguous_dual_national',
  'sanc_crypto_ofac_annex',
  'sanc_delisting_posture',
  'sanc_designation_imminent',
  'sanc_eu_vs_ofac_conflict',
  'sanc_fatf_grey_tranche',
  'sanc_list_freshness',
  'sanc_marine_dark_fleet_call',
  'sanc_ofac_eo',
  'sanc_partial_match_decision',
  'sanc_secondary_exposure',
  'sanc_secondary_penalty_exposure',
  'sanc_uk_opblock',
  'sanc_wind_down_general_licence',
  'sanctions_action',
  'sanctions_ambiguous_nationality',
  'sanctions_delta',
  'sanctions_hit',
  'sanctions_maritime_dark_fleet',
  'sanctions_maritime_stss',
  'sanctions_regime_matrix',
  'sanctions_wind_down',
  'saturation',
  'scale_invariance',
  'scenario_planning',
  'scenario_stress',
  'seasonality',
  'sectoral_vs_sdn',
  'self_dealing',
  'sensitivity_tornado',
  'sentiment_analysis',
  'shell_company',
  'shell_layering',
  'shortest_path',
  'sla_check',
  'socratic',
  'source_credibility',
  'source_triangulation',
  'sow_vs_sof',
  'speed',
  'spike_detection',
  'spoofing',
  'stablecoin_reserve',
  'staff_workload',
  'stakeholder_map',
  'standard',
  'stare_decisis',
  'statistical',
  'steelman',
  'steep',
  'str_draft',
  'str_trigger',
  'str_vs_ctr',
  'strategic',
  'stride',
  'structuring',
  'structuring_pattern',
  'survival',
  'swiss_cheese',
  'swot',
  'syllogistic',
  'synthetic_id',
  'tabletop_exercise',
  'taint_propagation',
  'tamper_detection',
  'tbml_bmpe',
  'tbml_bmpe_parallel',
  'tbml_cuckoo_smurfing',
  'tbml_free_trade_zone',
  'tbml_ftz_warehouse_letterbox',
  'tbml_invoicing',
  'tbml_maritime_aisoff',
  'tbml_maritime_bunker',
  'tbml_misdescribed_goods',
  'tbml_multiple_invoice_gold',
  'tbml_multiple_invoicing',
  'tbml_over_invoice_textile',
  'tbml_over_invoicing',
  'tbml_overlay',
  'tbml_pattern',
  'tbml_phantom',
  'tbml_phantom_shipment',
  'tbml_phantom_shipment_steel',
  'tbml_round_tripping',
  'tbml_round_tripping_smelter',
  'tbml_under_invoice_electronics',
  'tbml_under_invoicing',
  'temporal_logic',
  'tf_bank_guarantee',
  'tf_collateral_pledge',
  'tf_escrow',
  'tf_forfait_receivable',
  'tf_forfaiting_factoring',
  'tf_lc_amendment_flurry',
  'tf_lc_discrep',
  'tf_lc_discrepancy_waiver',
  'tf_merchant_forfait_chain',
  'tf_open_account',
  'tf_open_account_spike',
  'tf_red_flags',
  'tf_sblc_draw_chain',
  'tf_standby_lc',
  'tf_structured_commodity',
  'tf_trade_loan_collateral',
  'three_lines_defence',
  'time_series',
  'timeline_reconstruction',
  'timeseries',
  'toulmin',
  'training_compliance',
  'training_inadequacy',
  'triangulation',
  'trust_foundation',
  'turnover_anomaly',
  'typology_catalogue',
  'typology_match',
  'ubo_bearer_share_entity',
  'ubo_bearer_shares',
  'ubo_chain',
  'ubo_effective_control',
  'ubo_foundation_chain',
  'ubo_foundation_liechtenstein',
  'ubo_golden_share',
  'ubo_indirect_chain',
  'ubo_multi_jur_cascade',
  'ubo_nominee_director_gap',
  'ubo_nominee_directors',
  'ubo_protector_veto',
  'ubo_refusal_disposition',
  'ubo_refusal_to_disclose',
  'ubo_reverification_event',
  'ubo_reverification_missed',
  'ubo_secrecy_jurisdiction',
  'ubo_shell_hub_address',
  'ubo_tree_walk',
  'ubo_trust_chain',
  'vasp_bridge_wrapped_hop',
  'vasp_chain_hop_evasion',
  'vasp_crypto',
  'vasp_darknet_cluster',
  'vasp_defi_flash_layering',
  'vasp_mixer',
  'vasp_mixer_exposure',
  'vasp_mixer_inbound',
  'vasp_nft_layering',
  'vasp_on_off_ramp',
  'vasp_privacy_coin',
  'vasp_privacy_coin_swap',
  'vasp_sanctioned_wallet',
  'vasp_stablecoin_issuer',
  'vasp_stablecoin_large_redemption',
  'vasp_travel_rule',
  'vasp_travel_rule_missing',
  'vasp_wallet_screen',
  'velocity_analysis',
  'verdict_replay',
  'wallet_chain_hop',
  'war_game',
  'wash_trade',
  'wolfsberg_faq',
  'worst_case',
  'yacht_jet',
  'zoom',
] as const;

export type MlroModeId = typeof MLRO_MODE_IDS[number];

export const MLRO_MODE_CATEGORIES: Record<string, readonly MlroModeId[]> = {
  general: [
    'adverse_media_source_tier' as MlroModeId,
    'adverse_media_tiering' as MlroModeId,
    'adverse_media_triage' as MlroModeId,
    'beneficial_transfer' as MlroModeId,
    'break_even' as MlroModeId,
    'burden_of_proof' as MlroModeId,
    'cash_courier_ctn' as MlroModeId,
    'cb_bni_undeclared' as MlroModeId,
    'cb_border_declaration_history_gap' as MlroModeId,
    'cb_cash_smuggle_concealed' as MlroModeId,
    'cb_diplomatic_carrier' as MlroModeId,
    'cb_freight_non_declaration' as MlroModeId,
    'cb_hawala_overlap' as MlroModeId,
    'chain_of_verification' as MlroModeId,
    'conflict_interest' as MlroModeId,
    'contradiction' as MlroModeId,
    'cost_benefit' as MlroModeId,
    'counterexample_search' as MlroModeId,
    'counterfactual' as MlroModeId,
    'cross_case_triangulation' as MlroModeId,
    'cuckoo_smurf' as MlroModeId,
    'cuckoo_smurfing' as MlroModeId,
    'cvar' as MlroModeId,
    'data' as MlroModeId,
    'decision_tree' as MlroModeId,
    'deep' as MlroModeId,
    'defence_in_depth' as MlroModeId,
    'dialectic' as MlroModeId,
    'documentation_quality' as MlroModeId,
    'ensemble' as MlroModeId,
    'exit_client_risk' as MlroModeId,
    'expected_utility' as MlroModeId,
    'family_office_signal' as MlroModeId,
    'first_principles' as MlroModeId,
    'five_pillars' as MlroModeId,
    'fo_concentrated_issuer' as MlroModeId,
    'fo_concentrated_position' as MlroModeId,
    'fo_cross_border_settlor' as MlroModeId,
    'fo_multi_family' as MlroModeId,
    'fo_next_gen_politics' as MlroModeId,
    'fo_philanthropy' as MlroModeId,
    'fo_philanthropy_conduit' as MlroModeId,
    'fo_private_trust' as MlroModeId,
    'fo_ptc_veto' as MlroModeId,
    'fo_single_family' as MlroModeId,
    'fo_succession' as MlroModeId,
    'fo_trust_multi_jur' as MlroModeId,
    'forensic' as MlroModeId,
    'fourth_party_payment' as MlroModeId,
    'freeze_notification_chain' as MlroModeId,
    'fund_capital_call' as MlroModeId,
    'fund_capital_call_source' as MlroModeId,
    'fund_charter_redemption' as MlroModeId,
    'fund_gp_carry' as MlroModeId,
    'fund_gp_carry_sharing' as MlroModeId,
    'fund_large_redemption' as MlroModeId,
    'fund_master_feeder' as MlroModeId,
    'fund_master_feeder_layers' as MlroModeId,
    'fund_secondary_interest' as MlroModeId,
    'fund_secondary_market' as MlroModeId,
    'fund_side_letter' as MlroModeId,
    'fund_side_letter_mfn' as MlroModeId,
    'fund_sub_fund' as MlroModeId,
    'fund_sub_fund_cross' as MlroModeId,
    'fund_tokenised_subscription' as MlroModeId,
    'gov_board_attestation' as MlroModeId,
    'gov_board_oversight' as MlroModeId,
    'gov_change_notification' as MlroModeId,
    'gov_risk_assessment_refresh' as MlroModeId,
    'gov_vendor_risk' as MlroModeId,
    'grey_blacklist_jurisdiction' as MlroModeId,
    'grievance_whistleblower' as MlroModeId,
    'high_risk_jur_list' as MlroModeId,
    'incident_breach_containment' as MlroModeId,
    'incident_law_enforcement' as MlroModeId,
    'incident_lessons' as MlroModeId,
    'incident_lessons_learned' as MlroModeId,
    'incident_penalty_exposure' as MlroModeId,
    'incident_public_statement' as MlroModeId,
    'incident_regulator_request' as MlroModeId,
    'incident_remediation_plan' as MlroModeId,
    'incident_whistleblower' as MlroModeId,
    'inference' as MlroModeId,
    'ins_annuity_large' as MlroModeId,
    'ins_annuity_lump_sum' as MlroModeId,
    'ins_broker_kyc_gap' as MlroModeId,
    'ins_claim_proceeds' as MlroModeId,
    'ins_claim_third_party' as MlroModeId,
    'ins_ils_bond' as MlroModeId,
    'ins_ils_investor' as MlroModeId,
    'ins_premium_top_up' as MlroModeId,
    'ins_single_premium' as MlroModeId,
    'inversion' as MlroModeId,
    'kri_alignment' as MlroModeId,
    'legal_formalism' as MlroModeId,
    'lux_classic_car' as MlroModeId,
    'lux_classic_car_escrow' as MlroModeId,
    'lux_jewellery_export' as MlroModeId,
    'lux_jewellery_kimberley' as MlroModeId,
    'lux_watch_dealer' as MlroModeId,
    'lux_watch_serial' as MlroModeId,
    'marginal' as MlroModeId,
    'maximin' as MlroModeId,
    'mdl' as MlroModeId,
    'meta' as MlroModeId,
    'minimax' as MlroModeId,
    'moe_inspection_readiness' as MlroModeId,
    'nlp_contextual' as MlroModeId,
    'occam' as MlroModeId,
    'occams' as MlroModeId,
    'oecd_ddg_annex' as MlroModeId,
    'ops_alert_aging' as MlroModeId,
    'ops_alert_backlog' as MlroModeId,
    'ops_alert_triage' as MlroModeId,
    'ops_bcp_fault' as MlroModeId,
    'ops_dashboard_drift' as MlroModeId,
    'ops_dashboard_kpi' as MlroModeId,
    'ops_false_positive' as MlroModeId,
    'ops_logging_gap' as MlroModeId,
    'ops_model_validation' as MlroModeId,
    'ops_outsourced_ctl' as MlroModeId,
    'ops_outsourced_soc' as MlroModeId,
    'ops_pen_test_aml' as MlroModeId,
    'ops_pen_test_finding' as MlroModeId,
    'ops_rule_tuning' as MlroModeId,
    'ops_segmentation_drift' as MlroModeId,
    'ops_segmentation_model' as MlroModeId,
    'ops_tm_calibration' as MlroModeId,
    'ops_tm_threshold' as MlroModeId,
    'outsourced_reliance' as MlroModeId,
    'parallel' as MlroModeId,
    'pay_agent_network' as MlroModeId,
    'pay_agent_network_kyc' as MlroModeId,
    'pay_bnpl_merchant' as MlroModeId,
    'pay_bnpl_merchant_chain' as MlroModeId,
    'pay_cross_border_rail' as MlroModeId,
    'pay_cross_border_rails' as MlroModeId,
    'pay_instant_rail_spike' as MlroModeId,
    'pay_merchant_acquirer' as MlroModeId,
    'pay_pix_equiv' as MlroModeId,
    'pay_pix_equiv_scam' as MlroModeId,
    'pay_prepaid_card' as MlroModeId,
    'pay_prepaid_program' as MlroModeId,
    'payment_originator_info' as MlroModeId,
    'popper_falsification' as MlroModeId,
    'portfolio_view' as MlroModeId,
    'presumption_innocence' as MlroModeId,
    'principle_based' as MlroModeId,
    'purposive' as MlroModeId,
    'real_options' as MlroModeId,
    'reflective' as MlroModeId,
    'refresher_cadence' as MlroModeId,
    'regret_min' as MlroModeId,
    'residual_vs_inherent' as MlroModeId,
    'risk_adjusted' as MlroModeId,
    'risk_appetite_check' as MlroModeId,
    'risk_based_approach' as MlroModeId,
    'round_trip_hk' as MlroModeId,
    'round_tripping' as MlroModeId,
    'sanc_ambiguous_dual_national' as MlroModeId,
    'sanc_delisting_posture' as MlroModeId,
    'sanc_designation_imminent' as MlroModeId,
    'sanc_marine_dark_fleet_call' as MlroModeId,
    'sanc_partial_match_decision' as MlroModeId,
    'sanc_secondary_exposure' as MlroModeId,
    'sanc_secondary_penalty_exposure' as MlroModeId,
    'sanc_uk_opblock' as MlroModeId,
    'sanc_wind_down_general_licence' as MlroModeId,
    'saturation' as MlroModeId,
    'scale_invariance' as MlroModeId,
    'sectoral_vs_sdn' as MlroModeId,
    'sensitivity_tornado' as MlroModeId,
    'shell_company' as MlroModeId,
    'sla_check' as MlroModeId,
    'socratic' as MlroModeId,
    'speed' as MlroModeId,
    'staff_workload' as MlroModeId,
    'standard' as MlroModeId,
    'tf_bank_guarantee' as MlroModeId,
    'tf_collateral_pledge' as MlroModeId,
    'tf_escrow' as MlroModeId,
    'tf_forfait_receivable' as MlroModeId,
    'tf_forfaiting_factoring' as MlroModeId,
    'tf_merchant_forfait_chain' as MlroModeId,
    'tf_open_account' as MlroModeId,
    'tf_open_account_spike' as MlroModeId,
    'tf_standby_lc' as MlroModeId,
    'three_lines_defence' as MlroModeId,
    'timeseries' as MlroModeId,
    'triangulation' as MlroModeId,
    'trust_foundation' as MlroModeId,
    'turnover_anomaly' as MlroModeId,
    'typology_catalogue' as MlroModeId,
    'typology_match' as MlroModeId,
    'vasp_chain_hop_evasion' as MlroModeId,
    'vasp_darknet_cluster' as MlroModeId,
    'vasp_on_off_ramp' as MlroModeId,
    'vasp_travel_rule' as MlroModeId,
    'vasp_travel_rule_missing' as MlroModeId,
    'verdict_replay' as MlroModeId,
    'wolfsberg_faq' as MlroModeId,
    'worst_case' as MlroModeId,
    'zoom' as MlroModeId,
  ],
  governance: [
    'ai_governance' as MlroModeId,
    'audit_data_integrity' as MlroModeId,
    'audit_data_sampling' as MlroModeId,
    'audit_finding_open' as MlroModeId,
    'audit_finding_remediation' as MlroModeId,
    'audit_independent_assurance' as MlroModeId,
    'audit_independent_engagement' as MlroModeId,
    'audit_lookback' as MlroModeId,
    'audit_lookback_sample' as MlroModeId,
    'cognitive_bias_audit' as MlroModeId,
    'completeness_audit' as MlroModeId,
    'control_effectiveness' as MlroModeId,
    'escalation_trigger' as MlroModeId,
    'fo_next_gen_governance' as MlroModeId,
    'four_eyes_rationale' as MlroModeId,
    'gov_independent_audit' as MlroModeId,
    'gov_mlro_authority' as MlroModeId,
    'gov_policy_gap' as MlroModeId,
    'gov_policy_update_circular' as MlroModeId,
    'gov_training_matrix' as MlroModeId,
    'incident_tipping_off_audit' as MlroModeId,
    'ins_group_policy_mls' as MlroModeId,
    'ins_pep_policy' as MlroModeId,
    'ins_reinsurance_route' as MlroModeId,
    'ins_reinsurance_xborder' as MlroModeId,
    'insurance_wrap' as MlroModeId,
    'mlro_ai_governance_self' as MlroModeId,
    'mlro_ai_self_audit' as MlroModeId,
    'mlro_annual_risk_assessment' as MlroModeId,
    'mlro_appointment' as MlroModeId,
    'mlro_board_quarter' as MlroModeId,
    'mlro_board_report' as MlroModeId,
    'mlro_ew_risk_assessment' as MlroModeId,
    'mlro_four_eyes' as MlroModeId,
    'mlro_four_eyes_reversal' as MlroModeId,
    'mlro_override' as MlroModeId,
    'mlro_override_front_office' as MlroModeId,
    'mlro_regulator_briefing' as MlroModeId,
    'mlro_regulator_meeting' as MlroModeId,
    'mlro_regulator_rfi_response' as MlroModeId,
    'mlro_rfi_scope' as MlroModeId,
    'mlro_risk_appetite_change' as MlroModeId,
    'mlro_training_refresh' as MlroModeId,
    'mlro_training_rollout' as MlroModeId,
    'npo_governance_collapse' as MlroModeId,
    'ops_tuning_governance' as MlroModeId,
    'policy_drift' as MlroModeId,
    'policy_vs_rule' as MlroModeId,
    'retention_audit' as MlroModeId,
    'training_compliance' as MlroModeId,
    'training_inadequacy' as MlroModeId,
  ],
  gold_dpms: [
    'bullion_cross_border_transit' as MlroModeId,
    'bullion_dgd_refiner_deaccred' as MlroModeId,
    'bullion_dore_drc_asm' as MlroModeId,
    'bullion_good_delivery_dispute' as MlroModeId,
    'bullion_hallmark_mismatch' as MlroModeId,
    'bullion_letter_box_supplier' as MlroModeId,
    'bullion_letter_of_credit_gold' as MlroModeId,
    'bullion_refiner_recycled_scrap' as MlroModeId,
    'bullion_vault_custody_transfer' as MlroModeId,
    'bullion_wholesale_loco_split' as MlroModeId,
    'cahra_supplier' as MlroModeId,
    'dpms_bullion_loco' as MlroModeId,
    'dpms_cross_border_physical' as MlroModeId,
    'dpms_ewra' as MlroModeId,
    'dpms_goaml_dpmsr' as MlroModeId,
    'dpms_hallmark_verification' as MlroModeId,
    'dpms_kpi_quarterly' as MlroModeId,
    'dpms_pawn_broker' as MlroModeId,
    'dpms_refiner_cahra' as MlroModeId,
    'dpms_retail_buyback' as MlroModeId,
    'dpms_retail_cash_courier' as MlroModeId,
    'dpms_retail_digital_gold' as MlroModeId,
    'dpms_retail_expatriate_cash' as MlroModeId,
    'dpms_retail_franchise_chain' as MlroModeId,
    'dpms_retail_golden_visa_shopper' as MlroModeId,
    'dpms_retail_micro_structure' as MlroModeId,
    'dpms_retail_rapid_resale' as MlroModeId,
    'dpms_retail_third_party_payer' as MlroModeId,
    'dpms_retail_threshold' as MlroModeId,
    'dpms_retail_wedding_batch' as MlroModeId,
    'dpms_scrap_gold' as MlroModeId,
    'dpms_threshold' as MlroModeId,
    'dpms_wholesale_invoice' as MlroModeId,
    'filing_dpmsr_quarterly' as MlroModeId,
    'gold_dore_asm' as MlroModeId,
    'golden_visa' as MlroModeId,
    'golden_visa_nexus' as MlroModeId,
    'golden_visa_residency' as MlroModeId,
    'kpi_dpms_thirty' as MlroModeId,
    'lbma_rgg' as MlroModeId,
    'lbma_rgg_five_step' as MlroModeId,
    're_goldenvisa_invest' as MlroModeId,
    'tbml_multiple_invoice_gold' as MlroModeId,
    'ubo_golden_share' as MlroModeId,
  ],
  cdd_edd: [
    'cdd_digital_onboarding' as MlroModeId,
    'cdd_legacy_upgrade' as MlroModeId,
    'cdd_non_resident' as MlroModeId,
    'cdd_ongoing_cadence' as MlroModeId,
    'cdd_prospect_entity' as MlroModeId,
    'cdd_prospect_individual' as MlroModeId,
    'cdd_refresh_trigger' as MlroModeId,
    'cdd_simplified_eligibility' as MlroModeId,
    'cdd_third_party_reliance' as MlroModeId,
    'cdd_tier' as MlroModeId,
    'cdd_walk_in' as MlroModeId,
    'edd_adverse_media_triggered' as MlroModeId,
    'edd_cash_intensive' as MlroModeId,
    'edd_complex_structure' as MlroModeId,
    'edd_high_risk_jurisdiction' as MlroModeId,
    'edd_pep_family' as MlroModeId,
    'edd_sanctions_adjacent' as MlroModeId,
    'edd_sanctions_dismiss_rationale' as MlroModeId,
    'edd_sof_transaction' as MlroModeId,
    'edd_sow' as MlroModeId,
    'edd_sow_scope' as MlroModeId,
    'edd_uplift_trigger' as MlroModeId,
    'fraud_synthetic_onboard' as MlroModeId,
    'pay_msb_agent_onboard' as MlroModeId,
    'pay_msb_onboard' as MlroModeId,
    'pep_cash_onboarding' as MlroModeId,
    'pep_edd' as MlroModeId,
    'pep_onboarding' as MlroModeId,
    'sow_vs_sof' as MlroModeId,
    'tbml_maritime_aisoff' as MlroModeId,
  ],
  crypto: [
    'bridge_risk' as MlroModeId,
    'cb_crypto_to_cash_offramp' as MlroModeId,
    'chain_analysis' as MlroModeId,
    'defi_smart_contract' as MlroModeId,
    'fund_crypto_vehicle' as MlroModeId,
    'mev_scan' as MlroModeId,
    'nft_wash' as MlroModeId,
    'npo_crypto_donations' as MlroModeId,
    'pay_digital_wallet' as MlroModeId,
    'pay_wallet_velocity' as MlroModeId,
    'privacy_coin' as MlroModeId,
    'privacy_coin_reasoning' as MlroModeId,
    'sanc_crypto_ofac_annex' as MlroModeId,
    'stablecoin_reserve' as MlroModeId,
    'taint_propagation' as MlroModeId,
    'vasp_bridge_wrapped_hop' as MlroModeId,
    'vasp_crypto' as MlroModeId,
    'vasp_defi_flash_layering' as MlroModeId,
    'vasp_mixer' as MlroModeId,
    'vasp_mixer_exposure' as MlroModeId,
    'vasp_mixer_inbound' as MlroModeId,
    'vasp_nft_layering' as MlroModeId,
    'vasp_privacy_coin' as MlroModeId,
    'vasp_privacy_coin_swap' as MlroModeId,
    'vasp_sanctioned_wallet' as MlroModeId,
    'vasp_stablecoin_issuer' as MlroModeId,
    'vasp_stablecoin_large_redemption' as MlroModeId,
    'vasp_wallet_screen' as MlroModeId,
    'wallet_chain_hop' as MlroModeId,
  ],
  filings: [
    'audit_trail_reconstruction' as MlroModeId,
    'filing_cnmr_freeze' as MlroModeId,
    'filing_ctr_aggregation' as MlroModeId,
    'filing_deadline' as MlroModeId,
    'filing_retention_package' as MlroModeId,
    'filing_str_narrative' as MlroModeId,
    'fo_mfo_downstream_pep' as MlroModeId,
    'four_eyes_stress' as MlroModeId,
    'fund_distribution' as MlroModeId,
    'fund_distribution_assignment' as MlroModeId,
    'incident_str_no_tipping' as MlroModeId,
    'kyb_strict' as MlroModeId,
    'mlro_str_draft_review' as MlroModeId,
    'mlro_str_review' as MlroModeId,
    'npo_dual_registration' as MlroModeId,
    'pep_escrow_structure' as MlroModeId,
    're_sponsor_upstream' as MlroModeId,
    'scenario_stress' as MlroModeId,
    'str_draft' as MlroModeId,
    'str_trigger' as MlroModeId,
    'str_vs_ctr' as MlroModeId,
    'strategic' as MlroModeId,
    'structuring' as MlroModeId,
    'structuring_pattern' as MlroModeId,
    'tbml_under_invoice_electronics' as MlroModeId,
    'tf_structured_commodity' as MlroModeId,
    'timeline_reconstruction' as MlroModeId,
  ],
  forensic: [
    'causal' as MlroModeId,
    'causal_inference' as MlroModeId,
    'centrality' as MlroModeId,
    'collusion_pattern' as MlroModeId,
    'community_detection' as MlroModeId,
    'entity_resolution' as MlroModeId,
    'evidence_graph' as MlroModeId,
    'fishbone' as MlroModeId,
    'five_whys' as MlroModeId,
    'fmea' as MlroModeId,
    'ghost_employees' as MlroModeId,
    'lapping' as MlroModeId,
    'linguistic_forensics' as MlroModeId,
    'link_analysis' as MlroModeId,
    'motif_detection' as MlroModeId,
    'narrative_coherence' as MlroModeId,
    'pareto' as MlroModeId,
    'pattern_of_life' as MlroModeId,
    'peer_group_anomaly' as MlroModeId,
    'regime_change' as MlroModeId,
    'seasonality' as MlroModeId,
    'self_dealing' as MlroModeId,
    'sentiment_analysis' as MlroModeId,
    'shortest_path' as MlroModeId,
    'spike_detection' as MlroModeId,
    'swiss_cheese' as MlroModeId,
    'velocity_analysis' as MlroModeId,
  ],
  ubo_transparency: [
    'bearer_shares' as MlroModeId,
    'effective_control_ubo' as MlroModeId,
    'fund_nominee_investor' as MlroModeId,
    'fund_nominee_principal' as MlroModeId,
    'multi_jur_ubo' as MlroModeId,
    'multi_jurisdictional_ubo' as MlroModeId,
    'nominee_director' as MlroModeId,
    'ubo_bearer_share_entity' as MlroModeId,
    'ubo_bearer_shares' as MlroModeId,
    'ubo_chain' as MlroModeId,
    'ubo_effective_control' as MlroModeId,
    'ubo_foundation_chain' as MlroModeId,
    'ubo_foundation_liechtenstein' as MlroModeId,
    'ubo_indirect_chain' as MlroModeId,
    'ubo_multi_jur_cascade' as MlroModeId,
    'ubo_nominee_director_gap' as MlroModeId,
    'ubo_nominee_directors' as MlroModeId,
    'ubo_protector_veto' as MlroModeId,
    'ubo_refusal_disposition' as MlroModeId,
    'ubo_refusal_to_disclose' as MlroModeId,
    'ubo_reverification_event' as MlroModeId,
    'ubo_reverification_missed' as MlroModeId,
    'ubo_secrecy_jurisdiction' as MlroModeId,
    'ubo_shell_hub_address' as MlroModeId,
    'ubo_tree_walk' as MlroModeId,
    'ubo_trust_chain' as MlroModeId,
  ],
  market_abuse: [
    'front_running' as MlroModeId,
    'layering_stage' as MlroModeId,
    'market_churning' as MlroModeId,
    'market_churning_adv' as MlroModeId,
    'market_corner_bid' as MlroModeId,
    'market_cornering' as MlroModeId,
    'market_cross_venue' as MlroModeId,
    'market_front_run' as MlroModeId,
    'market_front_running' as MlroModeId,
    'market_insider' as MlroModeId,
    'market_insider_trade' as MlroModeId,
    'market_kiting' as MlroModeId,
    'market_kiting_corp' as MlroModeId,
    'market_manipulation' as MlroModeId,
    'market_painting' as MlroModeId,
    'market_painting_tape' as MlroModeId,
    'market_pnd' as MlroModeId,
    'market_pump_dump' as MlroModeId,
    'market_spoofing' as MlroModeId,
    'market_spoofing_pattern' as MlroModeId,
    'market_wash_circ' as MlroModeId,
    'market_wash_trade' as MlroModeId,
    'pay_merchant_layering' as MlroModeId,
    'shell_layering' as MlroModeId,
    'spoofing' as MlroModeId,
    'wash_trade' as MlroModeId,
  ],
  trade_finance: [
    'invoice_fraud' as MlroModeId,
    'tbml_bmpe' as MlroModeId,
    'tbml_bmpe_parallel' as MlroModeId,
    'tbml_cuckoo_smurfing' as MlroModeId,
    'tbml_free_trade_zone' as MlroModeId,
    'tbml_ftz_warehouse_letterbox' as MlroModeId,
    'tbml_invoicing' as MlroModeId,
    'tbml_misdescribed_goods' as MlroModeId,
    'tbml_multiple_invoicing' as MlroModeId,
    'tbml_over_invoice_textile' as MlroModeId,
    'tbml_over_invoicing' as MlroModeId,
    'tbml_overlay' as MlroModeId,
    'tbml_pattern' as MlroModeId,
    'tbml_phantom' as MlroModeId,
    'tbml_round_tripping' as MlroModeId,
    'tbml_round_tripping_smelter' as MlroModeId,
    'tbml_under_invoicing' as MlroModeId,
    'tf_lc_amendment_flurry' as MlroModeId,
    'tf_lc_discrep' as MlroModeId,
    'tf_lc_discrepancy_waiver' as MlroModeId,
    'tf_sblc_draw_chain' as MlroModeId,
    'tf_trade_loan_collateral' as MlroModeId,
  ],
  sanctions_pf: [
    'fatf_effectiveness' as MlroModeId,
    'ins_sanctions_cedant' as MlroModeId,
    'ins_sanctions_nexus' as MlroModeId,
    'multi_regime_sanctions' as MlroModeId,
    'npo_medical_supplies_proliferation' as MlroModeId,
    'npo_sanctioned_beneficiary' as MlroModeId,
    'pf_dual_use' as MlroModeId,
    'pf_dual_use_controls' as MlroModeId,
    'pf_dual_use_goods' as MlroModeId,
    'sanc_eu_vs_ofac_conflict' as MlroModeId,
    'sanc_fatf_grey_tranche' as MlroModeId,
    'sanc_ofac_eo' as MlroModeId,
    'sanctions_action' as MlroModeId,
    'sanctions_ambiguous_nationality' as MlroModeId,
    'sanctions_delta' as MlroModeId,
    'sanctions_hit' as MlroModeId,
    'sanctions_maritime_dark_fleet' as MlroModeId,
    'sanctions_maritime_stss' as MlroModeId,
    'sanctions_regime_matrix' as MlroModeId,
    'sanctions_wind_down' as MlroModeId,
  ],
  fraud: [
    'advance_fee' as MlroModeId,
    'app_scam' as MlroModeId,
    'bec_fraud' as MlroModeId,
    'fraud_app_romance' as MlroModeId,
    'fraud_app_scam' as MlroModeId,
    'fraud_bec' as MlroModeId,
    'fraud_bec_redirect' as MlroModeId,
    'fraud_identity_theft' as MlroModeId,
    'fraud_identity_theft_breach' as MlroModeId,
    'fraud_investment_scam' as MlroModeId,
    'fraud_phoenix_supplier' as MlroModeId,
    'fraud_romance_scam' as MlroModeId,
    'fraud_synthetic_id' as MlroModeId,
    'pay_instant_rail_fraud' as MlroModeId,
    'pay_merchant_chargeback' as MlroModeId,
    'phoenix_company' as MlroModeId,
    'ponzi_scheme' as MlroModeId,
    'synthetic_id' as MlroModeId,
  ],
  quantitative: [
    'bayes_theorem' as MlroModeId,
    'bayesian' as MlroModeId,
    'bayesian_network' as MlroModeId,
    'chi_square' as MlroModeId,
    'confidence_interval' as MlroModeId,
    'entropy' as MlroModeId,
    'fermi' as MlroModeId,
    'frequentist' as MlroModeId,
    'hmm' as MlroModeId,
    'hypothesis_test' as MlroModeId,
    'kl_divergence' as MlroModeId,
    'markov_chain' as MlroModeId,
    'monte_carlo' as MlroModeId,
    'probabilistic_logic' as MlroModeId,
    'regression' as MlroModeId,
    'statistical' as MlroModeId,
    'survival' as MlroModeId,
    'time_series' as MlroModeId,
  ],
  logic: [
    'analogical' as MlroModeId,
    'analogical_precedent' as MlroModeId,
    'default_reasoning' as MlroModeId,
    'deontic_logic' as MlroModeId,
    'epistemic_logic' as MlroModeId,
    'fuzzy_logic' as MlroModeId,
    'modal_logic' as MlroModeId,
    'modus_ponens' as MlroModeId,
    'modus_tollens' as MlroModeId,
    'non_monotonic' as MlroModeId,
    'ontological' as MlroModeId,
    'paraconsistent' as MlroModeId,
    'predicate_logic' as MlroModeId,
    'propositional_logic' as MlroModeId,
    'reductio' as MlroModeId,
    'syllogistic' as MlroModeId,
    'temporal_logic' as MlroModeId,
  ],
  correspondent: [
    'corresp_cbd_downstream_pep' as MlroModeId,
    'corresp_cbuae_standard_gap' as MlroModeId,
    'corresp_cover_payment_miss' as MlroModeId,
    'corresp_downstream_sanctions' as MlroModeId,
    'corresp_escrow_payment_block' as MlroModeId,
    'corresp_historical_exit' as MlroModeId,
    'corresp_nested_bank_flow' as MlroModeId,
    'corresp_nested_vasp' as MlroModeId,
    'corresp_payment_intermediary_strip' as MlroModeId,
    'corresp_shell_bank_suspected' as MlroModeId,
    'correspondent_kyc' as MlroModeId,
    'correspondent_risk' as MlroModeId,
    'edd_correspondent_triggered' as MlroModeId,
    'nested_correspondent' as MlroModeId,
    'nested_correspondent_kycc' as MlroModeId,
  ],
  real_estate: [
    'cb_re_export_ftz_cash' as MlroModeId,
    'pre_mortem' as MlroModeId,
    're_agent_dd' as MlroModeId,
    're_cash_purchase' as MlroModeId,
    're_cash_villa' as MlroModeId,
    're_intra_family_transfer' as MlroModeId,
    're_offplan_payer_switch' as MlroModeId,
    're_offplan_payment_plan' as MlroModeId,
    're_rapid_resale' as MlroModeId,
    're_reit_flow' as MlroModeId,
    're_reit_large_investor' as MlroModeId,
    're_transfer_family' as MlroModeId,
    'real_estate_cash' as MlroModeId,
    'stare_decisis' as MlroModeId,
  ],
  threat_modeling: [
    'adversarial_collaboration' as MlroModeId,
    'adversarial_debate' as MlroModeId,
    'attack_tree' as MlroModeId,
    'bowtie' as MlroModeId,
    'fair' as MlroModeId,
    'insider_threat' as MlroModeId,
    'kill_chain' as MlroModeId,
    'mitre_attack' as MlroModeId,
    'octave' as MlroModeId,
    'pasta' as MlroModeId,
    'red_team' as MlroModeId,
    'stride' as MlroModeId,
    'tabletop_exercise' as MlroModeId,
  ],
  compliance_framework: [
    'article_by_article' as MlroModeId,
    'cabinet_res_walk' as MlroModeId,
    'circular_walk' as MlroModeId,
    'de_minimis' as MlroModeId,
    'emirate_jurisdiction' as MlroModeId,
    'exception_log' as MlroModeId,
    'gray_zone_resolution' as MlroModeId,
    'jurisdiction_cascade' as MlroModeId,
    'list_walk' as MlroModeId,
    'peer_benchmark' as MlroModeId,
    'proportionality_test' as MlroModeId,
    'regulatory_mapping' as MlroModeId,
    'source_triangulation' as MlroModeId,
  ],
  cognitive: [
    'anchoring_avoidance' as MlroModeId,
    'availability_check' as MlroModeId,
    'confidence_calibration' as MlroModeId,
    'dual_process' as MlroModeId,
    'framing_check' as MlroModeId,
    'hindsight_check' as MlroModeId,
    'loss_aversion_check' as MlroModeId,
    'ooda' as MlroModeId,
    'overconfidence_check' as MlroModeId,
    'planning_fallacy' as MlroModeId,
    'post_mortem' as MlroModeId,
    'steelman' as MlroModeId,
  ],
  luxury: [
    'art_dealer' as MlroModeId,
    'art_hvg' as MlroModeId,
    'fo_art_collection' as MlroModeId,
    'fo_art_freeport' as MlroModeId,
    'fo_jet_charter' as MlroModeId,
    'fo_yacht_jet' as MlroModeId,
    'fo_yacht_spv_chain' as MlroModeId,
    'lux_art_dealer' as MlroModeId,
    'lux_art_private_sale' as MlroModeId,
    'lux_yacht_broker' as MlroModeId,
    'lux_yacht_broker_flow' as MlroModeId,
    'yacht_jet' as MlroModeId,
  ],
  pep: [
    'fo_pep_patriarch' as MlroModeId,
    'ins_pep_life' as MlroModeId,
    'npo_trustee_pep' as MlroModeId,
    'pep_domestic_minister' as MlroModeId,
    'pep_family_extension' as MlroModeId,
    'pep_former_official_decay' as MlroModeId,
    'pep_international_org' as MlroModeId,
    'pep_political_transition' as MlroModeId,
    'pep_rca' as MlroModeId,
    'pep_rca_nephew' as MlroModeId,
    'pep_secondary_title' as MlroModeId,
    'pep_wolfsberg_cert' as MlroModeId,
  ],
  data_quality: [
    'data_quality_score' as MlroModeId,
    'discrepancy_log' as MlroModeId,
    'freshness_check' as MlroModeId,
    'lineage' as MlroModeId,
    'provenance_trace' as MlroModeId,
    'reconciliation' as MlroModeId,
    'sanc_list_freshness' as MlroModeId,
    'source_credibility' as MlroModeId,
    'tamper_detection' as MlroModeId,
  ],
  strategic: [
    'lens_shift' as MlroModeId,
    'minimum_viable_compliance' as MlroModeId,
    'pestle' as MlroModeId,
    'porter_adapted' as MlroModeId,
    'scenario_planning' as MlroModeId,
    'stakeholder_map' as MlroModeId,
    'steep' as MlroModeId,
    'swot' as MlroModeId,
    'war_game' as MlroModeId,
  ],
  npo: [
    'charity_tf' as MlroModeId,
    'gifting_charity_payout' as MlroModeId,
    'npo_anonymous_donor_spike' as MlroModeId,
    'npo_cash_courier_relief' as MlroModeId,
    'npo_charity_conflict_zone' as MlroModeId,
    'npo_pif_platform_layering' as MlroModeId,
    'npo_risk' as MlroModeId,
    'npo_tf_risk' as MlroModeId,
  ],
  ethics_rhetoric: [
    'craac' as MlroModeId,
    'ethical_matrix' as MlroModeId,
    'irac' as MlroModeId,
    'occam_vs_conspiracy' as MlroModeId,
    'rogerian' as MlroModeId,
    'toulmin' as MlroModeId,
  ],
  maritime: [
    'free_zone_red_flags' as MlroModeId,
    'red_flags' as MlroModeId,
    'tbml_maritime_bunker' as MlroModeId,
    'tbml_phantom_shipment' as MlroModeId,
    'tbml_phantom_shipment_steel' as MlroModeId,
    'tf_red_flags' as MlroModeId,
  ],
  insurance: [
    'ins_life_settlement' as MlroModeId,
    'ins_life_surrender' as MlroModeId,
    'ins_life_surrender_cash' as MlroModeId,
  ],
};

export type MlroModeCategory = string;

export const MLRO_CATEGORY_LABELS: Record<string, string> = {
  general: 'General',
  governance: 'Governance',
  gold_dpms: 'Gold / DPMS',
  cdd_edd: 'CDD / EDD',
  crypto: 'Crypto / VA',
  filings: 'Filings',
  forensic: 'Forensic',
  ubo_transparency: 'UBO / transparency',
  market_abuse: 'Market abuse',
  trade_finance: 'Trade finance',
  sanctions_pf: 'Sanctions / PF',
  fraud: 'Fraud',
  quantitative: 'Quantitative',
  logic: 'Formal logic',
  correspondent: 'Correspondent',
  real_estate: 'Real estate',
  threat_modeling: 'Threat modelling',
  compliance_framework: 'Compliance framework',
  cognitive: 'Cognitive science',
  luxury: 'Luxury assets',
  pep: 'PEP / RCA',
  data_quality: 'Data quality',
  strategic: 'Strategic',
  npo: 'NPO',
  ethics_rhetoric: 'Ethics / rhetoric',
  maritime: 'Maritime',
  insurance: 'Insurance',
};

export function modesByCategory(c: MlroModeCategory): readonly MlroModeId[] {
  return MLRO_MODE_CATEGORIES[c] ?? [];
}

export function searchModes(query: string): MlroModeId[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const tokens = q.split(/\s+/).filter(Boolean);
  return MLRO_MODE_IDS.filter((id) => tokens.every((t) => id.toLowerCase().includes(t))) as MlroModeId[];
}

export function suggestModesFor(context: { sector?: string; hasCrypto?: boolean; hasCahra?: boolean; hasPep?: boolean; hasCash?: boolean }): MlroModeId[] {
  const picks = new Set<MlroModeId>();
  const add = (key: string) => {
    const xs = MLRO_MODE_CATEGORIES[key];
    if (xs) xs.slice(0, 3).forEach((x) => picks.add(x));
  };
  add('logic');
  add('cognitive');
  if (context.sector === 'dpms') add('gold_dpms');
  if (context.hasCrypto) add('crypto');
  if (context.hasCahra) add('sanctions_pf');
  if (context.hasPep) add('pep');
  if (context.hasCash) add('quantitative');
  return [...picks];
}
