// Hawkeye Sterling — Orphan mode declarations.
// 135 modes that are implemented in src/brain/modes/registry.ts (MODE_OVERRIDES)
// but were NOT declared in REASONING_MODES, so the brain engine never invoked them.
// This file declares their metadata stubs; the real apply() from MODE_OVERRIDES
// takes precedence at runtime via the standard override merge loop in reasoning-modes.ts.

import type { FacultyId, ReasoningCategory, ReasoningMode } from './types.js';
import { defaultApply } from './modes/default-apply.js';

const m = (
  id: string,
  name: string,
  category: ReasoningCategory,
  faculties: FacultyId[],
  description: string,
): ReasoningMode => ({
  id, name, category, faculties, wave: 3, description,
  apply: defaultApply(id, category, faculties, description),
});

// ── cryptoasset_forensics (18) ───────────────────────────────────────────────
const cryptoassetModes: ReasoningMode[] = [
  m('utxo_clustering', 'UTXO Clustering',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Clusters UTXO sets using common-input-ownership and change-address heuristics to map wallet graphs and identify structuring across Bitcoin/UTXO chains.'),
  m('address_reuse_analysis', 'Address Reuse Analysis',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Detects repeated address reuse patterns indicating hot-wallet concentration or deliberate traceability reduction; alias of utxo_clustering UTXO detector.'),
  m('heuristic_common_input', 'Heuristic Common Input',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Applies Meiklejohn common-input-ownership heuristic to infer address co-ownership from multi-input transactions.'),
  m('heuristic_change_address', 'Heuristic Change Address',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Identifies change-address round-vs-remainder splits to reconstruct wallet ownership boundaries across UTXO chains.'),
  m('peeling_chain_pattern', 'Peeling Chain Pattern',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Detects peel-chain residual cluster patterns where small sequential sends progressively strip value before a final consolidation.'),
  m('coinjoin_participation', 'CoinJoin Participation',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Identifies CoinJoin mixing transactions by equal-output fingerprinting, flagging use of privacy-enhancing mixing services.'),
  m('lazarus_address_match', 'Lazarus Address Match',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Screens wallet addresses against Lazarus Group (DPRK APT38) known deposit/exchange clusters from OFAC/FinCEN public advisories.'),
  m('ofac_sdn_address_match', 'OFAC SDN Address Match',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Cross-references crypto wallet addresses against OFAC SDN digital-currency address identifiers for direct sanctions exposure.'),
  m('defi_recursive_loan', 'DeFi Recursive Loan',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Detects recursive flash-loan loops in DeFi protocol call traces indicative of price manipulation or liquidity drain attacks.'),
  m('smart_contract_drain', 'Smart Contract Drain',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Identifies reentrancy and selfdestruct drain patterns in smart contract interactions consistent with exploit typologies.'),
  m('flash_loan_attack_pattern', 'Flash Loan Attack Pattern',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Detects single-block flash-loan sequences used for oracle price manipulation, arbitrage exploitation, or governance attacks.'),
  m('rugpull_indicator', 'Rugpull Indicator',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Flags DeFi liquidity-pool drain events where developer-controlled wallets remove all liquidity, signalling exit-scam typology.'),
  m('stablecoin_arbitrage_anomaly', 'Stablecoin Arbitrage Anomaly',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Detects anomalous stablecoin arbitrage velocity inconsistent with legitimate market-making, indicative of layering through peg mechanisms.'),
  m('mixer_forensics', 'Mixer Forensics',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Analyses transaction graph topology around known mixing services (Tornado Cash, ChipMixer, Wasabi) for indirect exposure.'),
  m('crypto_chain_hop_layering', 'Crypto Chain-Hop Layering',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Detects rapid chain-hop layering: assets moved across ≥3 blockchain networks within 24 hours to obscure originating wallet.'),
  m('nft_wash_trading', 'NFT Wash Trading',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Identifies NFT wash-trading cycles where the same NFT transfers between related wallets at inflating prices to establish artificial market value.'),
  m('unhosted_wallet_high_volume', 'Unhosted Wallet High Volume',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Flags high-volume transactions to/from unhosted (self-custodied) wallets exceeding FATF Travel Rule thresholds.'),
  m('travel_rule_compliance_gap', 'Travel Rule Compliance Gap',
    'cryptoasset_forensics', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Detects transfers above FATF Travel Rule threshold (USD 1 000 / EUR 1 000) that lack required originator/beneficiary VASP data.'),
];

// ── proliferation (11) ───────────────────────────────────────────────────────
const proliferationModes: ReasoningMode[] = [
  m('dual_use_goods_routing', 'Dual-Use Goods Routing',
    'proliferation', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Screens payment routes for dual-use goods subject to Wassenaar Arrangement and EU/UAE export-control schedules.'),
  m('dual_use_chemical_routing', 'Dual-Use Chemical Routing',
    'proliferation', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Flags financial flows associated with chemical precursors on the Australia Group control list or CWC Schedule 1-3.'),
  m('proliferation_finance_unscr1540', 'Proliferation Finance UNSCR 1540',
    'proliferation', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Checks transactions against UNSCR 1540 obligations: financing WMD proliferation through front companies, brokers, or shell entities.'),
  m('iran_oil_sts_transfer', 'Iran Oil STS Transfer',
    'proliferation', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Detects ship-to-ship crude-oil transfer patterns consistent with Iranian sanctions evasion via flags-of-convenience tanker fleets.'),
  m('russia_oil_price_cap_evasion', 'Russia Oil Price Cap Evasion',
    'proliferation', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Flags transactions involving Russian crude above the G7 price cap (USD 60/bbl for crude) routed through third-country intermediaries.'),
  m('dprk_it_worker_payment', 'DPRK IT Worker Payment',
    'proliferation', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Identifies payment patterns to DPRK IT worker front companies — typically micro-company payroll, cryptocurrency off-ramp, and VPN-masked endpoints.'),
  m('vessel_callsign_manipulation', 'Vessel Callsign Manipulation',
    'proliferation', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Detects AIS callsign or MMSI manipulation used to disguise vessel identity during sanctions-violating port calls.'),
  m('sanctioned_jurisdiction_layering', 'Sanctioned Jurisdiction Layering',
    'proliferation', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Maps multi-hop payment chains passing through sanctioned jurisdictions (Iran, DPRK, Syria, Cuba) via correspondent intermediaries.'),
  m('fronting_company_indicator', 'Fronting Company Indicator',
    'proliferation', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Identifies fronting company patterns: newly incorporated entities in third countries receiving payments subsequently forwarded to sanctioned parties.'),
  m('phantom_shipment_detection', 'Phantom Shipment Detection',
    'proliferation', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Detects trade-finance transactions with no corresponding shipping evidence — no B/L, AIS movement, or port manifest match.'),
  m('nested_designation_match', 'Nested Designation Match',
    'proliferation', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Screens UBO chains for partial name matches against designated persons using Unicode normalisation and transliteration.'),
];

// ── identity_fraud (13) ──────────────────────────────────────────────────────
const identityFraudModes: ReasoningMode[] = [
  m('synthetic_identity_indicator', 'Synthetic Identity Indicator',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects synthetic identity patterns: SSN/Emirates ID issued after 1990 combined with thin credit file and high-velocity account openings.'),
  m('id_document_deepfake', 'ID Document Deepfake',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags biometric document submissions with AI-generated artefacts: pixel-level inconsistencies, metadata mismatches, or deepfake facial mapping.'),
  m('address_aggregation_red_flag', 'Address Aggregation Red Flag',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects multiple unrelated customer accounts sharing the same residential address — indicator of identity farming or mule recruitment.'),
  m('multi_account_same_device', 'Multi-Account Same Device',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies multiple distinct customer accounts authenticated from the same device fingerprint within 30 days.'),
  m('disposable_email_signal', 'Disposable Email Signal',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags use of disposable or temporary email domains (Guerrilla Mail, Mailinator, 10-minute mail) at account opening.'),
  m('voip_phone_anomaly', 'VoIP Phone Anomaly',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects VoIP-based phone numbers used for 2FA or contact, which cannot receive SMS verification and are trivially re-routed.'),
  m('sim_swap_indicator', 'SIM Swap Indicator',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags accounts where the 2FA SIM changed within 24 hours of a large withdrawal — consistent with SIM-swap account takeover.'),
  m('velocity_account_creation', 'Velocity Account Creation',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects burst account-opening velocity: ≥5 accounts from the same IP subnet or device class within 60 minutes.'),
  m('non_face_to_face_kyc_anomaly', 'Non-Face-to-Face KYC Anomaly',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags non-face-to-face onboarding where document metadata, geolocation, and selfie timestamps are inconsistent.'),
  m('email_spoof_forensic', 'Email Spoof Forensic',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Analyses email header chain for SPF/DKIM failures, lookalike display-name spoofing, and domain typosquatting.'),
  m('typosquat_domain_detection', 'Typosquat Domain Detection',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies typosquatted sending domains using Levenshtein distance ≤2 from known counterparty domains.'),
  m('invoice_redirection_trace', 'Invoice Redirection Trace',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Traces invoice-redirection fraud patterns: original beneficiary account replaced by attacker-controlled account mid-transaction.'),
  m('ceo_impersonation_signal', 'CEO Impersonation Signal',
    'identity_fraud', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects CEO-impersonation BEC patterns: urgent payment instruction from spoofed executive email bypassing normal authorisation workflow.'),
];

// ── behavioral_signals (18) ──────────────────────────────────────────────────
const behavioralSignalsModes: ReasoningMode[] = [
  m('rapid_layering_pattern', 'Rapid Layering Pattern',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects rapid-layering typology: funds received and re-sent within 24 hours across ≥3 sequential hops, reducing traceability.'),
  m('funnel_account_indicator', 'Funnel Account Indicator',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies funnel accounts: high inflow from many counterparties followed by immediate single-beneficiary bulk transfer.'),
  m('circular_payment_loop', 'Circular Payment Loop',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects circular payment chains where funds return to the originator within N hops, indicating value recycling without economic purpose.'),
  m('dormant_to_active_anomaly', 'Dormant-to-Active Anomaly',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags accounts dormant >12 months that suddenly receive/send high-value transactions without updated CDD or EDD trigger.'),
  m('round_amount_clustering', 'Round Amount Clustering',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects clustering of round-number transactions (e.g., exactly AED 10 000, 50 000, 100 000) inconsistent with organic trading patterns.'),
  m('midnight_burst_pattern', 'Midnight Burst Pattern',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags burst transaction activity between 00:00 and 05:00 local time, a timing profile associated with automated layering scripts.'),
  m('salary_account_misuse', 'Salary Account Misuse',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies personal salary accounts receiving structurally diverse inflows inconsistent with payroll — indicative of mule account use.'),
  m('atm_density_anomaly', 'ATM Density Anomaly',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects abnormally high ATM withdrawal frequency or geographic spread inconsistent with the account holder\'s registered address.'),
  m('impossible_geo_velocity', 'Impossible Geo Velocity',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags transactions implying physical presence in two geographically distant locations within an impossibly short time window.'),
  m('chargeback_ring_pattern', 'Chargeback Ring Pattern',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies chargeback rings: coordinated merchant-consumer collusion using repeated dispute cycles to extract value from payment networks.'),
  m('pep_proximity_chain', 'PEP Proximity Chain',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Maps PEP proximity: non-PEP subject with ≥2 direct financial relationships to known domestic PEPs, signalling beneficial influence risk.'),
  m('domestic_pep_concentration', 'Domestic PEP Concentration',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags geographic concentration of domestic PEP-linked transactions in single jurisdiction branches — potential corruption hub indicator.'),
  m('soe_executive_payout', 'SOE Executive Payout',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects state-owned enterprise executive compensation payments structurally inconsistent with disclosed salary scales.'),
  m('electoral_window_anomaly', 'Electoral Window Anomaly',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags unusual payment volumes to PEP-linked accounts in the 90-day window before national or regional elections.'),
  m('judicial_payment_correlation', 'Judicial Payment Correlation',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies financial flows to judicial-branch officials correlated with pending case outcomes — potential corruption signal.'),
  m('procurement_kickback_pattern', 'Procurement Kickback Pattern',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects procurement kickback typology: government contractor payment followed by rapid disbursement to official-linked accounts.'),
  m('extractive_payment_opacity', 'Extractive Payment Opacity',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags extractive-industry revenue payments (oil, mining, gas) lacking commodity volumes, pricing references, or off-take agreement documentation.'),
  m('mule_cluster_detection', 'Mule Cluster Detection',
    'behavioral_signals', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies money-mule cluster networks using graph community detection on shared device, IP, and beneficiary linkages.'),
];

// ── market_integrity (11) ────────────────────────────────────────────────────
const marketIntegrityModes: ReasoningMode[] = [
  m('carousel_vat_fraud', 'Carousel VAT Fraud',
    'market_integrity', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects missing-trader intra-community (MTIC) carousel VAT fraud: goods cycling through shell importers and exporters to claim fraudulent VAT refunds.'),
  m('circular_trade_pattern', 'Circular Trade Pattern',
    'market_integrity', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies circular trade flows where goods or value return to the originating entity after a chain of intermediaries with no net economic benefit.'),
  m('multi_invoicing_anomaly', 'Multi-Invoicing Anomaly',
    'market_integrity', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags the same shipment invoiced to multiple buyers or financed by multiple trade-finance facilities simultaneously.'),
  m('mis_described_goods', 'Mis-Described Goods',
    'market_integrity', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects commodity mis-description in trade documents: declared HS code, weight, or value materially inconsistent with shipping intelligence.'),
  m('transfer_pricing_manipulation', 'Transfer Pricing Manipulation',
    'market_integrity', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies intra-group transfer pricing outside arm\'s-length ranges as defined by OECD TP Guidelines, used to shift profits to low-tax jurisdictions.'),
  m('round_tripping_pattern', 'Round-Tripping Pattern',
    'market_integrity', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects round-tripping: capital exported and re-imported as foreign investment to benefit from favourable FDI tax treatment.'),
  m('import_export_ratio_anomaly', 'Import/Export Ratio Anomaly',
    'market_integrity', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags import/export value ratios for specific HS-code commodity pairs that deviate >30% from COMTRADE global average — indicative of TBML.'),
  m('wash_trading_securities', 'Wash Trading Securities',
    'market_integrity', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies wash-trading in securities: offsetting buy/sell orders for the same instrument between related parties to create artificial volume.'),
  m('securities_swap_layering', 'Securities Swap Layering',
    'market_integrity', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects layering through equity/debt swap chains: securities converted to cash and back multiple times to obscure ownership.'),
  m('spoofing_layering', 'Spoofing Layering',
    'market_integrity', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags order-book spoofing combined with layering: large non-bona-fide orders placed and cancelled to move price before execution.'),
  m('pump_and_dump_indicator', 'Pump-and-Dump Indicator',
    'market_integrity', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects pump-and-dump typology: coordinated promotional activity followed by insider sell-off of low-cap securities.'),
];

// ── forensic (9) ─────────────────────────────────────────────────────────────
const forensicModes: ReasoningMode[] = [
  m('vessel_ais_gap', 'Vessel AIS Gap',
    'forensic', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Detects AIS dark-period gaps >6 hours in international waters, port-proximity STS transfers, and flag-hopping consistent with sanctions evasion.'),
  m('vessel_ais_gap_analysis', 'Vessel AIS Gap Analysis',
    'forensic', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Extended AIS gap analysis mode: correlates dark periods with sanctioned port proximity, cargo type, and insurance endorsement anomalies.'),
  m('vessel_beneficial_owner', 'Vessel Beneficial Owner',
    'forensic', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Traces vessel beneficial ownership through flag-state registries, ISM managers, and P&I club records to identify sanctioned beneficial interests.'),
  m('flag_of_convenience', 'Flag of Convenience',
    'forensic', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Flags vessels registered under open-registry FOC states (Panama, Marshall Islands, Liberia) with ownership chains linked to sanctioned entities.'),
  m('port_state_control', 'Port State Control',
    'forensic', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Cross-references vessel port-state-control deficiency records with cargo and payment flows for elevated sanctions-evasion risk scoring.'),
  m('tbml_invoice_manipulation', 'TBML Invoice Manipulation',
    'forensic', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Detects trade-based money laundering via invoice manipulation: over/under-invoicing, multiple invoicing, and phantom shipment indicators.'),
  m('cargo_manifest_cross_check', 'Cargo Manifest Cross-Check',
    'forensic', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Cross-references cargo manifest commodity declarations against shipping weight, vessel capacity, and commodity market prices for TBML indicators.'),
  m('lc_confirmation_gap', 'LC Confirmation Gap',
    'forensic', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Identifies letter-of-credit confirmation gaps: absence of confirming-bank endorsement on high-value LCs issued from high-risk jurisdictions.'),
  m('chain_of_custody_break', 'Chain of Custody Break',
    'forensic', ['data_analysis', 'intelligence', 'forensic_accounting'],
    'Detects breaks in mineral/commodity chain-of-custody documentation required under OECD Due Diligence Guidance and Dodd-Frank §1502.'),
];

// ── sectoral_typology (27) ───────────────────────────────────────────────────
const sectoralTypologyModes: ReasoningMode[] = [
  m('assay_certificate_audit', 'Assay Certificate Audit',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Audits precious-metal assay certificates for LBMA-accredited refinery provenance, hallmark consistency, and sequential certificate numbering.'),
  m('assay_certificate_inconsistency', 'Assay Certificate Inconsistency',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects inconsistencies between assay certificate weight/purity declarations and corresponding customs entries or storage receipts.'),
  m('bullion_warehouse_anomaly', 'Bullion Warehouse Anomaly',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags bullion warehouse receipt anomalies: duplicate receipts, unexplained storage gaps, or warehouse not LBMA-approved.'),
  m('gold_smuggling_corridor', 'Gold Smuggling Corridor',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects UAE-specific gold smuggling corridor payments: cash purchases, same-day cross-border shipment, and missing VAT documentation.'),
  m('lbma_five_step_gate', 'LBMA Five-Step Gate',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Applies the LBMA five-step precious-metals due-diligence framework to assess country-of-origin risk for gold, silver, platinum, and palladium.'),
  m('precious_stones_provenance_gap', 'Precious Stones Provenance Gap',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags diamond, ruby, emerald, or sapphire transactions lacking Kimberley Process Certification Scheme certificates or provenance chain.'),
  m('dpms_cash_structuring_split', 'DPMS Cash Structuring Split',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects DPMS cash-purchase structuring: single jewellery purchase split across multiple transactions to avoid AED 55 000 cash-reporting threshold.'),
  m('dpms_fictitious_supplier', 'DPMS Fictitious Supplier',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies DPMS fictitious-supplier payments: invoiced from non-existent or newly incorporated precious-metals suppliers with no trade history.'),
  m('oecd_annex_ii_discipline', 'OECD Annex II Discipline',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Applies OECD Annex II mineral-supply-chain due-diligence model to assess 3TG (tin, tantalum, tungsten, gold) sourcing risk.'),
  m('casino_chip_dumping', 'Casino Chip Dumping',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects casino chip-dumping typology: chips purchased with cash then cashed out by a different person or redeemed as a cheque, converting illicit cash to clean funds.'),
  m('family_office_trust_transparency', 'Family Office Trust Transparency',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Evaluates transparency of family office and private trust structures: undisclosed settlors, non-professional trustees in secrecy jurisdictions, and missing beneficial ownership registers.'),
  m('art_auction_provenance_gap', 'Art Auction Provenance Gap',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects art-market provenance gaps: artworks with ownership periods missing between 1933 and 1945 (Nazi-era looting risk) or post-1970 UNESCO cut-off.'),
  m('art_provenance_chain', 'Art Provenance Chain',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Traces full provenance chain for high-value artworks using auction-house records, dealer invoices, and museum exhibition histories.'),
  m('real_estate_underpricing', 'Real Estate Underpricing',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags real-estate transactions priced >20% below municipal assessed value — indicative of deliberate underpricing to launder difference as undeclared cash.'),
  m('re_cash_purchase_check', 'RE Cash Purchase Check',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Applies UAE FDL 20/2018 Art.16 cash-purchase disclosure requirements to real-estate transactions above AED 55 000.'),
  m('re_golden_visa_investment', 'RE Golden Visa Investment',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Screens UAE Golden Visa real-estate investments for source-of-funds completeness and PEP/sanctions nexus of the investing beneficial owner.'),
  m('re_shell_owner_check', 'RE Shell Owner Check',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies real-estate purchases through single-purpose shell companies without disclosed UBOs — primary UAE property-sector ML typology.'),
  m('npo_high_risk_outflow', 'NPO High-Risk Outflow',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags NPO cash outflows to high-risk jurisdictions exceeding 30% of annual programme budget — FATF R.8 NPO sector risk indicator.'),
  m('npo_grantee_diligence', 'NPO Grantee Diligence',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Assesses NPO grantee due-diligence completeness: registration status, programme alignment, and geographic-risk classification of recipient organisations.'),
  m('npo_conflict_zone_flow', 'NPO Conflict Zone Flow',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects NPO payments to organisations operating in active conflict zones listed by FATF, UN, or EU as high CFT risk.'),
  m('npo_programme_vs_cash_ratio', 'NPO Programme vs Cash Ratio',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Compares NPO cash disbursements to reported programme expenditure — ratios >40% cash raise FATF R.8 diversion risk.'),
  m('ins_early_surrender_cash', 'Insurance Early Surrender Cash',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags life-insurance policy early surrender (within 24 months of inception) with cash-value payment — classic ML placement typology.'),
  m('ins_premium_overfund', 'Insurance Premium Overfund',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects insurance premium overfunding: premiums paid significantly in excess of contractual obligation, creating a refundable surplus.'),
  m('ins_policy_assignment', 'Insurance Policy Assignment',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags life-policy assignments to unrelated third parties without documented insurable interest or legitimate estate-planning rationale.'),
  m('ins_beneficiary_rotation', 'Insurance Beneficiary Rotation',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects rapid beneficiary rotations on life policies (>2 changes per year) inconsistent with legitimate succession planning.'),
  m('ins_cross_border_nominee', 'Insurance Cross-Border Nominee',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Identifies cross-border life-insurance policies with nominee beneficiaries in different jurisdiction from the policyholder — nominee-trust ML typology.'),
  m('ins_single_premium_scrutiny', 'Insurance Single Premium Scrutiny',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Applies FATF Life Insurance Guidance Oct 2018 single-premium scrutiny: large lump-sum insurance premia from customers with no prior investment profile.'),
  m('insurance_premium_dump', 'Insurance Premium Dump',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects insurance-premium dump typology: excessive premium payments followed by immediate policy cancellation and refund to a different account.'),
  m('life_policy_third_party_assignment', 'Life Policy Third-Party Assignment',
    'sectoral_typology', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags life-policy assignment to a third-party investor (life-settlement secondary market) without documented MLRO review of assignee.'),
];

// ── hawala_ivt (4) ───────────────────────────────────────────────────────────
const hawalaIvtModes: ReasoningMode[] = [
  m('hawala_ivts_pattern', 'Hawala/IVTS Pattern',
    'hawala_ivt', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Detects hawala/IVT patterns: matched offsetting transactions between geographic corridors with no corresponding banking record or remittance license.'),
  m('cash_courier_ctn', 'Cash Courier CTN',
    'hawala_ivt', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Identifies physical cash courier patterns via currency-transaction-notification (CTN) records exceeding UAE AED 100 000 cross-border threshold.'),
  m('cash_courier_threshold', 'Cash Courier Threshold',
    'hawala_ivt', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Applies UAE Cabinet Resolution No. 10/2019 AED 100 000 cash-declaration threshold to cross-border cash courier and bearer-instrument movements.'),
  m('bridge_crossing_trace', 'Bridge Crossing Trace',
    'hawala_ivt', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Traces cash courier movements at UAE land border crossings using CTN filings correlated with vehicle and passport data.'),
];

// ── correspondent_banking (2) ────────────────────────────────────────────────
const correspondentBankingModes: ReasoningMode[] = [
  m('correspondent_banking_nesting', 'Correspondent Banking Nesting',
    'correspondent_banking', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects nested correspondent banking: respondent bank processing transactions on behalf of unnamed sub-respondents without principal-bank visibility.'),
  m('wire_stripping_indicator', 'Wire Stripping Indicator',
    'correspondent_banking', ['data_analysis', 'intelligence', 'reasoning'],
    'Flags wire-transfer messages with truncated originator information — a wire-stripping red flag under FATF R.16.'),
];

// ── ftz_risk (1) ─────────────────────────────────────────────────────────────
const ftzRiskModes: ReasoningMode[] = [
  m('ftz_layered_ownership', 'FTZ Layered Ownership',
    'ftz_risk', ['intelligence', 'geopolitical_awareness', 'reasoning'],
    'Maps layered ownership structures within UAE Free Trade Zones where nominee shareholders obscure beneficial ownership beyond CDD requirements.'),
];

// ── predicate_crime (7) ──────────────────────────────────────────────────────
const predicateCrimeModes: ReasoningMode[] = [
  m('wildlife_trafficking_indicator', 'Wildlife Trafficking Indicator',
    'predicate_crime', ['intelligence', 'reasoning', 'forensic_accounting'],
    'Flags payments to wildlife-trade counterparties or jurisdictions with high TRAFFIC/UNODC wildlife-trafficking risk indices.'),
  m('drug_proceeds_indicator', 'Drug Proceeds Indicator',
    'predicate_crime', ['intelligence', 'reasoning', 'forensic_accounting'],
    'Detects drug-proceeds placement indicators: structured cash deposits below reporting thresholds, high-velocity street-value equivalent amounts.'),
  m('illegal_logging_payment', 'Illegal Logging Payment',
    'predicate_crime', ['intelligence', 'reasoning', 'forensic_accounting'],
    'Identifies payments linked to timber merchants in Global Forest Watch high-deforestation jurisdictions lacking FLEGT/CITES documentation.'),
  m('tax_evasion_offshore', 'Tax Evasion Offshore',
    'predicate_crime', ['intelligence', 'reasoning', 'forensic_accounting'],
    'Detects offshore tax-evasion indicators: undisclosed foreign accounts, treaty-shopping structures, and AEOI CRS mismatch signals.'),
  m('fraud_419_pattern', 'Fraud 419 Pattern',
    'predicate_crime', ['intelligence', 'reasoning', 'forensic_accounting'],
    'Identifies advance-fee fraud (419) payment patterns: overseas wire transfers to recently opened accounts following unsolicited solicitation.'),
  m('counterfeit_supply_chain', 'Counterfeit Supply Chain',
    'predicate_crime', ['intelligence', 'reasoning', 'forensic_accounting'],
    'Flags payments to suppliers in known counterfeit-goods source jurisdictions without legitimate trademark licensing documentation.'),
  m('smuggling_corridor_uae', 'Smuggling Corridor UAE',
    'predicate_crime', ['intelligence', 'reasoning', 'forensic_accounting'],
    'Detects UAE-specific smuggling corridor payments: cash flows correlating with known Jebel Ali port contraband routes.'),
];

// ── professional_ml (2) ──────────────────────────────────────────────────────
const professionalMlModes: ReasoningMode[] = [
  m('professional_enabler_pattern', 'Professional Enabler Pattern',
    'professional_ml', ['intelligence', 'reasoning', 'data_analysis'],
    'Identifies professional-enabler ML patterns: lawyers, accountants, or corporate-service providers acting as payment intermediaries without disclosed purpose.'),
  m('legal_pooled_account_abuse', 'Legal Pooled Account Abuse',
    'professional_ml', ['intelligence', 'reasoning', 'data_analysis'],
    'Detects misuse of legal professional pooled client accounts to layer funds across multiple underlying client matters.'),
];

// ── human_rights (3) ─────────────────────────────────────────────────────────
const humanRightsModes: ReasoningMode[] = [
  m('modern_slavery_indicator', 'Modern Slavery Indicator',
    'human_rights', ['intelligence', 'reasoning', 'geopolitical_awareness'],
    'Flags payment patterns consistent with modern slavery: group payroll to single payee, deductions for accommodation, and wage suppression below minimum wage.'),
  m('child_labour_indicator', 'Child Labour Indicator',
    'human_rights', ['intelligence', 'reasoning', 'geopolitical_awareness'],
    'Detects child-labour-linked supply chain payments using ILO/UNICEF risk-country mapping and sector-vulnerability indices.'),
  m('human_trafficking_pattern', 'Human Trafficking Pattern',
    'human_rights', ['intelligence', 'reasoning', 'geopolitical_awareness'],
    'Identifies human-trafficking financial patterns: shared-address payees, escort-service merchant codes, and cross-border cash remittances to high-risk corridors.'),
];

// ── esg (1) ──────────────────────────────────────────────────────────────────
const esgModes: ReasoningMode[] = [
  m('conflict_mineral_documentation', 'Conflict Mineral Documentation',
    'esg', ['intelligence', 'reasoning', 'data_analysis'],
    'Validates OECD/ICGLR conflict-mineral due-diligence documentation for 3TG minerals sourced from DRC conflict-affected areas.'),
];

// ── digital_economy (1) ──────────────────────────────────────────────────────
const digitalEconomyModes: ReasoningMode[] = [
  m('ransomware_payment_indicator', 'Ransomware Payment Indicator',
    'digital_economy', ['data_analysis', 'intelligence', 'reasoning'],
    'Detects ransomware payment indicators: urgent USDT/BTC transfers to freshly generated wallets following endpoint-security alerts.'),
];

// ── corporate_intelligence (5) ───────────────────────────────────────────────
const corporateIntelligenceModes: ReasoningMode[] = [
  m('dormant_company_reactivation', 'Dormant Company Reactivation',
    'corporate_intelligence', ['intelligence', 'data_analysis', 'reasoning'],
    'Detects dormant-company reactivation: companies inactive >2 years suddenly registering new directors and receiving large inbound payments.'),
  m('director_resignation_cluster', 'Director Resignation Cluster',
    'corporate_intelligence', ['intelligence', 'data_analysis', 'reasoning'],
    'Flags burst director-resignation events on a single company within 30 days — indicator of upcoming control transfer or regulatory evasion.'),
  m('registered_agent_concentration', 'Registered Agent Concentration',
    'corporate_intelligence', ['intelligence', 'data_analysis', 'reasoning'],
    'Detects high concentration of unrelated companies registered to the same corporate-service-provider address — shell-company factory indicator.'),
  m('mass_filing_same_day', 'Mass Filing Same Day',
    'corporate_intelligence', ['intelligence', 'data_analysis', 'reasoning'],
    'Identifies coordinated same-day filing of multiple company documents (resolutions, address changes) across related entities — typical pre-fraud reorganisation.'),
  m('shell_company_indicator', 'Shell Company Indicator',
    'corporate_intelligence', ['intelligence', 'data_analysis', 'reasoning'],
    'Evaluates multi-factor shell-company scoring: nominee directors, registered-agent address, zero employees, and undisclosed UBO chain.'),
];

export const ORPHAN_MODES: ReasoningMode[] = [
  ...cryptoassetModes,
  ...proliferationModes,
  ...identityFraudModes,
  ...behavioralSignalsModes,
  ...marketIntegrityModes,
  ...forensicModes,
  ...sectoralTypologyModes,
  ...hawalaIvtModes,
  ...correspondentBankingModes,
  ...ftzRiskModes,
  ...predicateCrimeModes,
  ...professionalMlModes,
  ...humanRightsModes,
  ...esgModes,
  ...digitalEconomyModes,
  ...corporateIntelligenceModes,
];
