// Wave 11 — common sense, quantitative analysis, synthetic intelligence,
// formal reasoning. 40 modes. Stub-apply pending Phase 11.

import type {
  BrainContext, Finding, FacultyId, ReasoningCategory, ReasoningMode,
} from './types.js';

const stubApply = (modeId: string, category: ReasoningCategory, faculties: FacultyId[]) =>
  async (_ctx: BrainContext): Promise<Finding> => ({
    modeId,
    category,
    faculties,
    score: 0,
    confidence: 0,
    verdict: 'inconclusive',
    rationale: `[stub] ${modeId} — implementation pending (Phase 11).`,
    evidence: [],
    producedAt: Date.now(),
  });

const m = (
  id: string,
  name: string,
  category: ReasoningCategory,
  faculties: FacultyId[],
  description: string,
): ReasoningMode => ({
  id, name, category, faculties, wave: 11, description,
  apply: stubApply(id, category, faculties),
});

// ── common_sense (10) ─────────────────────────────────────────────────────────
const common_sense: ReasoningMode[] = [
  m('cs.plausibility_check', 'Plausibility Check', 'common_sense',
    ['reasoning', 'intelligence'],
    'Apply everyday plausibility reasoning to detected facts: flag scenarios that defy normal economic, geographic, or temporal logic (e.g., same-day dual-jurisdiction cash deposits, impossible travel patterns).'),
  m('cs.motive_coherence', 'Motive Coherence', 'common_sense',
    ['reasoning', 'inference'],
    'Ask whether the subject\'s stated purpose is coherent with their observed behaviour. Mismatches between declared motive and financial footprint are a primary common-sense red flag.'),
  m('cs.lifestyle_vs_income', 'Lifestyle vs Income Congruence', 'common_sense',
    ['data_analysis', 'reasoning'],
    'Compare observable lifestyle indicators (property, travel, vehicles, luxury spend) against declared income. Unexplained wealth is a tier-1 AML signal requiring escalation.'),
  m('cs.counterparty_logic', 'Counterparty Logic Check', 'common_sense',
    ['reasoning', 'intelligence'],
    'Evaluate whether the subject\'s counterparties make commercial sense: assess geographic fit, sector alignment, and whether relationships exist that a reasonable person would expect.'),
  m('cs.timing_anomaly_sense', 'Timing Anomaly Sense', 'common_sense',
    ['reasoning', 'data_analysis'],
    'Identify timing patterns that defy business logic: transactions at 3 AM, accounts opened immediately before large flows, dormant entities reactivated on sanction anniversaries.'),
  m('cs.round_number_suspicion', 'Round Number Suspicion', 'common_sense',
    ['data_analysis', 'reasoning'],
    'Flag an over-representation of round-number transactions or deposits. Structuring and layering often leave a statistical signature of suspiciously "clean" denominations.'),
  m('cs.narrative_consistency', 'Narrative Consistency Check', 'common_sense',
    ['reasoning', 'argumentation'],
    'Cross-check the customer\'s story across all touchpoints (KYC declarations, transaction purpose fields, interview notes). Internal contradictions are a primary deception signal.'),
  m('cs.too_good_to_be_true', 'Too Good To Be True Detector', 'common_sense',
    ['reasoning', 'introspection'],
    'Identify when an investment return, fee arrangement, or business opportunity is implausibly favourable. Ponzi, fraud, and tax-evasion schemes routinely offer outlier terms.'),
  m('cs.victim_vs_perpetrator', 'Victim vs Perpetrator Classification', 'common_sense',
    ['reasoning', 'inference'],
    'Distinguish whether a subject is the originator or recipient of illicit flows. Common-sense indicators: who benefits, who moves first, and who controls the account.'),
  m('cs.basic_entity_reality_check', 'Basic Entity Reality Check', 'common_sense',
    ['reasoning', 'intelligence'],
    'Verify that a company or individual is plausibly real: registered address exists, employees exist, website is older than 6 months, sector matches location. Shell signals: zero-staff, virtual-office-only addresses, same director across 10+ jurisdictions.'),
];

// ── quantitative_analysis (10) ────────────────────────────────────────────────
const quantitative_analysis: ReasoningMode[] = [
  m('qa.statistical_outlier_detection', 'Statistical Outlier Detection', 'quantitative_analysis',
    ['data_analysis', 'reasoning'],
    'Apply z-score, IQR, and percentile analysis to transaction volumes, frequencies, and counterparty counts. Flag values more than 3σ from peer-group medians as requiring justification.'),
  m('qa.flow_velocity_analysis', 'Flow Velocity Analysis', 'quantitative_analysis',
    ['data_analysis', 'intelligence'],
    'Measure the speed at which funds enter and leave accounts. High-velocity pass-through (>80% of inflows exiting within 24 hours) is a layering typology indicator.'),
  m('qa.concentration_risk_scoring', 'Concentration Risk Scoring', 'quantitative_analysis',
    ['data_analysis', 'reasoning'],
    'Compute Herfindahl–Hirschman index over counterparty distribution. High concentration to a single opaque counterparty signals control risk; high dispersion to many unknown parties signals structuring.'),
  m('qa.benford_law_analysis', 'Benford\'s Law Analysis', 'quantitative_analysis',
    ['data_analysis', 'forensic_accounting'],
    'Apply Benford\'s Law (first-digit frequency distribution) to transaction sets. Statistically significant deviation from the expected log-scale distribution signals manipulation or fabrication.'),
  m('qa.time_series_anomaly', 'Time-Series Anomaly Detection', 'quantitative_analysis',
    ['data_analysis', 'reasoning'],
    'Apply ARIMA, STL decomposition, or rolling-window z-score to detect step-changes in activity levels that cannot be explained by legitimate business seasonality.'),
  m('qa.peer_group_benchmarking', 'Peer Group Benchmarking', 'quantitative_analysis',
    ['data_analysis', 'intelligence'],
    'Construct a peer cohort (same sector, jurisdiction, entity size) and benchmark the subject\'s financial behaviour. Material deviation from cohort norms triggers a proportionate investigation.'),
  m('qa.value_at_risk_exposure', 'Value-at-Risk Exposure Quantification', 'quantitative_analysis',
    ['data_analysis', 'strong_brain'],
    'Estimate the financial institution\'s regulatory and reputational exposure from a given relationship using Monte Carlo simulation over scenario distributions of fine levels and remediation costs.'),
  m('qa.network_flow_matrix', 'Network Flow Matrix Analysis', 'quantitative_analysis',
    ['data_analysis', 'reasoning'],
    'Build an adjacency-weighted flow matrix across all transacting parties. Identify eigenvector-central nodes, bridge nodes, and sink nodes that indicate control or layering roles.'),
  m('qa.seasonality_stripping', 'Seasonality-Stripped Trend Analysis', 'quantitative_analysis',
    ['data_analysis', 'deep_thinking'],
    'Decompose raw volume data into trend, seasonal, and residual components. Investigate the residual: unexplained surges in the residual signal non-business-driven cash flows.'),
  m('qa.regression_discontinuity', 'Regression Discontinuity for Threshold Avoidance', 'quantitative_analysis',
    ['data_analysis', 'inference'],
    'Apply regression discontinuity design around reporting thresholds (e.g., $10,000 CTR, €15,000 EU). A sharp drop in transaction density just below the threshold is a structuring signature.'),
];

// ── synthetic_intelligence (10) ───────────────────────────────────────────────
const synthetic_intelligence: ReasoningMode[] = [
  m('si.cross_modal_fusion', 'Cross-Modal Evidence Fusion', 'synthetic_intelligence',
    ['strong_brain', 'intelligence', 'synthesis'],
    'Fuse signals from disparate data modalities (structured transaction data, unstructured media, graph topology, geospatial metadata) into a unified risk vector using weighted multi-modal aggregation.'),
  m('si.adversarial_simulation', 'Adversarial Evasion Simulation', 'synthetic_intelligence',
    ['intelligence', 'reasoning', 'anticipation'],
    'Simulate how a sophisticated money-launderer would attempt to evade detection given the observed controls. Identify the weakest detection link and recommend countermeasures.'),
  m('si.knowledge_graph_inference', 'Knowledge Graph Inference', 'synthetic_intelligence',
    ['inference', 'intelligence', 'strong_brain'],
    'Run graph-completion and link-prediction algorithms over the entity knowledge graph to surface relationships not directly evidenced but probabilistically supported by structural similarity.'),
  m('si.meta_pattern_recognition', 'Meta-Pattern Recognition', 'synthetic_intelligence',
    ['intelligence', 'synthesis', 'deep_thinking'],
    'Identify recurrent structural patterns (not just known typologies) by comparing the current case graph against a corpus of confirmed cases. Novel typologies emerge as outliers in the pattern space.'),
  m('si.counterfactual_reasoning', 'Counterfactual Risk Reasoning', 'synthetic_intelligence',
    ['reasoning', 'intelligence', 'anticipation'],
    'Evaluate what the risk picture would look like had specific inputs changed (different jurisdiction, different UBO, different source of funds). Counterfactual sensitivity reveals which variables drive the verdict.'),
  m('si.ensemble_verdict_fusion', 'Ensemble Verdict Fusion', 'synthetic_intelligence',
    ['strong_brain', 'synthesis', 'reasoning'],
    'Combine multiple independent analytical models (rules-based, statistical, graph, LLM) using stacked generalisation or Bayesian model averaging. Ensemble diversity reduces false-positive rate.'),
  m('si.hypothesis_generation', 'Automated Hypothesis Generation', 'synthetic_intelligence',
    ['intelligence', 'inference', 'deep_thinking'],
    'Given the evidence state, systematically generate all plausible risk hypotheses (not just the most obvious) ranked by prior probability. Prevents fixation on a single narrative.'),
  m('si.semantic_vector_search', 'Semantic Vector Search for Latent Signals', 'synthetic_intelligence',
    ['intelligence', 'data_analysis'],
    'Embed all evidence artefacts into a semantic vector space and retrieve latent matches to known-bad patterns. Surface non-lexical similarity that keyword search misses.'),
  m('si.causal_dag_inference', 'Causal DAG Inference', 'synthetic_intelligence',
    ['reasoning', 'inference', 'strong_brain'],
    'Construct a directed acyclic graph of inferred causal relationships between observed events. Identify root causes and downstream effects to distinguish symptom from source.'),
  m('si.belief_propagation', 'Belief Propagation over Factor Graph', 'synthetic_intelligence',
    ['inference', 'reasoning', 'quantum_intelligence'],
    'Model the evidence network as a factor graph and run belief propagation (sum-product algorithm) to infer marginal posteriors for each unobserved variable, including hidden controlling parties.'),
];

// ── formal_reasoning (10) ─────────────────────────────────────────────────────
const formal_reasoning: ReasoningMode[] = [
  m('fr.logical_entailment_check', 'Logical Entailment Check', 'formal_reasoning',
    ['reasoning', 'argumentation', 'ratiocination'],
    'Formalise the compliance determination as a set of propositions and verify that the conclusion is a logically necessary consequence of the premises. Surface any logical gaps or hidden assumptions.'),
  m('fr.modal_logic_obligation', 'Modal Logic — Obligation & Permission', 'formal_reasoning',
    ['reasoning', 'argumentation'],
    'Encode regulatory requirements as modal-logic statements (□ obligation, ◇ permission). Verify that the subject\'s conduct satisfies the modal structure of the applicable rules.'),
  m('fr.rule_conflict_resolution', 'Rule Conflict Resolution', 'formal_reasoning',
    ['reasoning', 'ratiocination', 'argumentation'],
    'Detect conflicts between applicable regulatory rules (lex specialis, lex posterior, lex superior). Apply standard priority rules and flag irresolvable conflicts for legal counsel.'),
  m('fr.first_order_predicate_audit', 'First-Order Predicate Audit', 'formal_reasoning',
    ['reasoning', 'deep_thinking', 'ratiocination'],
    'Translate KYC/AML obligations into first-order predicate logic. For each predicate, verify whether a grounding in evidence exists. Ungrounded predicates are evidentiary gaps.'),
  m('fr.proof_by_contradiction', 'Proof by Contradiction', 'formal_reasoning',
    ['reasoning', 'argumentation', 'introspection'],
    'Assume the subject is fully compliant and derive contradictions from the evidence set. The strength of the contradiction set measures the depth of the compliance failure.'),
  m('fr.abductive_inference', 'Abductive Inference to Best Explanation', 'formal_reasoning',
    ['inference', 'reasoning', 'ratiocination'],
    'Enumerate candidate explanations for the observed evidence and select the one with the greatest explanatory power (highest posterior, fewest auxiliary assumptions, most testable predictions).'),
  m('fr.temporal_logic_sequencing', 'Temporal Logic Event Sequencing', 'formal_reasoning',
    ['reasoning', 'inference', 'data_analysis'],
    'Encode the timeline of events using linear temporal logic (LTL). Verify whether the observed sequence satisfies, violates, or is ambiguous with respect to expected compliance-process properties.'),
  m('fr.defeasible_reasoning', 'Defeasible Reasoning', 'formal_reasoning',
    ['reasoning', 'argumentation', 'ratiocination'],
    'Apply defeasible logic to handle exceptions and rebuttals in compliance determinations. Track which default rules have been overridden and ensure overrides are properly evidenced.'),
  m('fr.argument_structure_mapping', 'Argument Structure Mapping', 'formal_reasoning',
    ['argumentation', 'reasoning', 'introspection'],
    'Map the full argument structure (claim → grounds → warrant → backing → qualifier → rebuttal) using Toulmin notation. Identify weak warrants, missing backings, and unaddressed rebuttals.'),
  m('fr.constraint_satisfaction', 'Constraint Satisfaction Problem Formulation', 'formal_reasoning',
    ['reasoning', 'strong_brain', 'data_analysis'],
    'Encode the compliance problem as a constraint satisfaction problem (CSP). Use arc-consistency and backtracking search to enumerate all solutions (compliant states) and all violated constraints.'),
];

export const WAVE11_MODES: ReasoningMode[] = [
  ...common_sense,
  ...quantitative_analysis,
  ...synthetic_intelligence,
  ...formal_reasoning,
];

export const WAVE11_OVERRIDES: ReasoningMode[] = [];
