// Hawkeye Sterling — structured red-flag catalogue.
// Red flags are FACTUAL INDICATORS, not legal conclusions (per P3 of the
// compliance charter). Each flag binds to the typology it indicates, the
// reasoning modes that detect it, and a severity (low | medium | high).
// The brain cites red flags by id in its findings; the UI groups them by
// typology for the MLRO.

export type RedFlagSeverity = 'low' | 'medium' | 'high';

export interface RedFlag {
  id: string;
  typology: string;
  indicator: string;
  severity: RedFlagSeverity;
  reasoningModes: string[];
  sources: string[];
}

export const RED_FLAGS: RedFlag[] = [
  // — Structuring / smurfing
  { id: 'rf_structuring_threshold', typology: 'structuring', indicator: 'Multiple cash deposits immediately below the reporting threshold.', severity: 'high', reasoningModes: ['velocity_analysis', 'spike_detection', 'peer_group_anomaly'], sources: ['FATF RBA', 'UAE FIU typology catalogue'] },
  { id: 'rf_structuring_branches', typology: 'structuring', indicator: 'Same customer depositing across multiple branches on the same day.', severity: 'high', reasoningModes: ['pattern_of_life', 'link_analysis'], sources: ['Wolfsberg FAQ'] },

  // — DPMS / precious metals
  { id: 'rf_dpms_cash_walk_in', typology: 'dpms_retail', indicator: 'Walk-in buyer pays for high-value gold in cash with no relationship history.', severity: 'high', reasoningModes: ['dpms_retail_threshold', 'cash_courier_ctn'], sources: ['MoE DNFBP circular', 'LBMA RGG'] },
  { id: 'rf_dpms_no_receipt', typology: 'dpms_retail', indicator: 'Customer declines receipt or requests anonymous transaction.', severity: 'high', reasoningModes: ['documentation_quality', 'source_credibility'], sources: ['MoE DNFBP'] },
  { id: 'rf_dpms_refiner_cahra', typology: 'dpms_refinery', indicator: 'Doré/scrap origin in conflict-affected or high-risk area without OECD-annex-II documentation.', severity: 'high', reasoningModes: ['oecd_ddg_annex', 'provenance_trace', 'lineage'], sources: ['LBMA RGG', 'OECD DDG'] },

  // — Trade-based money laundering
  { id: 'rf_tbml_over_invoice', typology: 'tbml', indicator: 'Invoice value materially above market rate for goods described.', severity: 'high', reasoningModes: ['tbml_over_invoicing', 'regression', 'peer_benchmark'], sources: ['FATF TBML report'] },
  { id: 'rf_tbml_phantom_shipment', typology: 'tbml', indicator: 'Shipping documents inconsistent with vessel AIS tracks or absent entirely.', severity: 'high', reasoningModes: ['tbml_phantom_shipment', 'sanctions_maritime_stss', 'timeline_reconstruction'], sources: ['FATF', 'OFAC maritime advisory'] },
  { id: 'rf_tbml_ucp600_gap', typology: 'tbml', indicator: 'LC discrepancies waived repeatedly under UCP 600 without documented rationale.', severity: 'medium', reasoningModes: ['ucp600_discipline', 'exception_log', 'documentation_quality'], sources: ['ICC UCP 600'] },

  // — Sanctions evasion / proliferation
  { id: 'rf_sanc_shell_chain', typology: 'sanctions_evasion', indicator: 'Counterparty is a newly-formed shell with nominee directors in opaque jurisdictions.', severity: 'high', reasoningModes: ['ubo_nominee_directors', 'jurisdiction_cascade', 'entity_resolution'], sources: ['OFAC', 'UK OFSI'] },
  { id: 'rf_sanc_dual_use', typology: 'proliferation', indicator: 'Dual-use goods shipped to end-user in proliferation-sensitive jurisdiction.', severity: 'high', reasoningModes: ['pf_dual_use_controls', 'sanctions_regime_matrix', 'attack_tree'], sources: ['UN 1540', 'EU dual-use regulation'] },
  { id: 'rf_sanc_stss', typology: 'sanctions_evasion', indicator: 'Vessel performs ship-to-ship transfer outside established port with AIS gap.', severity: 'high', reasoningModes: ['sanctions_maritime_stss', 'velocity_analysis'], sources: ['OFAC maritime', 'UK OFSI'] },

  // — PEP
  { id: 'rf_pep_wealth_mismatch', typology: 'pep', indicator: 'Declared source of wealth inconsistent with known public salary.', severity: 'high', reasoningModes: ['source_triangulation', 'narrative_coherence', 'regression'], sources: ['Wolfsberg FAQ', 'FATF R.12'] },
  { id: 'rf_pep_family_nominee', typology: 'pep', indicator: 'Accounts opened in names of PEP family members shortly after appointment.', severity: 'medium', reasoningModes: ['pep_domestic_minister', 'link_analysis', 'timeline_reconstruction'], sources: ['FATF R.12'] },

  // — UBO / corporate opacity
  { id: 'rf_ubo_bearer_shares', typology: 'ubo', indicator: 'Beneficial ownership obscured by bearer shares or multi-layered holding.', severity: 'high', reasoningModes: ['ubo_bearer_shares', 'ubo_tree_walk', 'jurisdiction_cascade'], sources: ['FATF R.24', 'Wolfsberg'] },
  { id: 'rf_ubo_common_address', typology: 'ubo', indicator: 'Multiple apparently unrelated entities share the same registered address or agent.', severity: 'medium', reasoningModes: ['entity_resolution', 'community_detection'], sources: ['Open Corporates typology'] },

  // — VASP / crypto
  { id: 'rf_vasp_mixer', typology: 'vasp', indicator: 'Inbound funds sourced from a known mixer or privacy protocol address.', severity: 'high', reasoningModes: ['vasp_mixer_inbound' as string, 'privacy_coin_reasoning', 'chain_analysis'], sources: ['FATF VASP guidance'] },
  { id: 'rf_vasp_travel_rule_gap', typology: 'vasp', indicator: 'Transfer above threshold missing originator/beneficiary data (Travel Rule).', severity: 'high', reasoningModes: ['vasp_travel_rule', 'completeness_audit'], sources: ['FATF R.16'] },

  // — Adverse media / conduct
  { id: 'rf_am_ongoing_investigation', typology: 'adverse_media', indicator: 'Counterparty named in credible, recent ongoing investigation.', severity: 'medium', reasoningModes: ['source_triangulation', 'freshness_check', 'source_credibility'], sources: ['news APIs', 'regulator press releases'] },

  // — Governance / controls
  { id: 'rf_ctl_four_eyes_bypass', typology: 'governance', indicator: 'Second approver role repeatedly overridden by same user.', severity: 'high', reasoningModes: ['four_eyes_stress', 'policy_drift', 'exception_log'], sources: ['CR 134/2025 Art.19', 'Three Lines Model'] },
  { id: 'rf_ctl_training_gap', typology: 'governance', indicator: 'AML training overdue for users handling high-risk disposition.', severity: 'medium', reasoningModes: ['training_inadequacy', 'documentation_quality'], sources: ['FATF R.18'] },
  { id: 'rf_ctl_record_gap', typology: 'governance', indicator: 'Screening evidence missing for a disposition already recorded.', severity: 'high', reasoningModes: ['retention_audit', 'audit_trail_reconstruction', 'reconciliation'], sources: ['FDL 10/2025 Art.24'] },

  // ── Wave 4 — environmental crime (FATF 2021 predicate) ──────────────
  { id: 'rf_env_crime_cahra_flow', typology: 'environmental_crime', indicator: 'Commodity flows linked to CAHRA supply chain without OECD / provenance evidence of legal extraction.', severity: 'high', reasoningModes: ['oecd_ddg_annex', 'provenance_trace', 'jurisdiction_cascade'], sources: ['FATF R.3 (2021)', 'OECD DDG'] },
  { id: 'rf_env_crime_waste_trafficking', typology: 'environmental_crime', indicator: 'Cross-border waste shipment without Basel Convention notification or with false HS-code classification.', severity: 'high', reasoningModes: ['provenance_trace', 'commodity_price_anomaly'], sources: ['Basel Convention', 'FATF R.3'] },

  // ── Wave 4 — carbon-market fraud ────────────────────────────────────
  { id: 'rf_carbon_market_phantom_credit', typology: 'carbon_market_fraud', indicator: 'Carbon credits issued against a project with no verifiable baseline or with a registry-registration gap.', severity: 'high', reasoningModes: ['provenance_trace', 'source_triangulation'], sources: ['ICVCM Core Carbon Principles'] },
  { id: 'rf_carbon_market_double_count', typology: 'carbon_market_fraud', indicator: 'Same tonne of emissions claimed under more than one corresponding-adjustment ledger or retirement registry.', severity: 'high', reasoningModes: ['reconciliation', 'provenance_trace'], sources: ['Article 6 Paris Agreement'] },

  // ── Wave 4 — insider threat / IP exfiltration ───────────────────────
  { id: 'rf_insider_threat_privileged_exfil', typology: 'insider_threat', indicator: 'Privileged user downloads or exports data volume materially above role-profile baseline in short window.', severity: 'high', reasoningModes: ['velocity_analysis', 'peer_group_anomaly', 'timeline_reconstruction'], sources: ['Three Lines Model'] },
  { id: 'rf_insider_threat_offboarding_spike', typology: 'insider_threat', indicator: 'Material access, print, or external-drive activity in the 30 days preceding announced resignation or role change.', severity: 'high', reasoningModes: ['timeline_reconstruction', 'pattern_of_life'], sources: [] },

  // ── Wave 4 — AI governance breach (EU AI Act / NIST / ISO 42001) ────
  { id: 'rf_ai_gov_no_model_inventory', typology: 'ai_governance_breach', indicator: 'AI system in production not recorded in the AI registry / model inventory required by ISO/IEC 42001.', severity: 'high', reasoningModes: ['retention_audit', 'documentation_quality'], sources: ['ISO/IEC 42001', 'EU AI Act Art.11'] },
  { id: 'rf_ai_gov_high_risk_tier_skipped', typology: 'ai_governance_breach', indicator: 'AI use-case fits a high-risk tier (hiring, credit, health, education, law-enforcement) yet no EU AI Act conformity assessment has been executed.', severity: 'high', reasoningModes: ['regulatory_mapping', 'control_effectiveness'], sources: ['EU AI Act Annex III'] },
  { id: 'rf_ai_gov_red_team_absent', typology: 'ai_governance_breach', indicator: 'High-risk AI system deployed without pre- and post-deployment red-team evidence (OWASP LLM Top 10).', severity: 'medium', reasoningModes: ['attack_tree', 'control_effectiveness'], sources: ['OWASP LLM Top 10', 'EU AI Act'] },
  { id: 'rf_ai_gov_no_kill_switch', typology: 'ai_governance_breach', indicator: 'Agentic AI acting on irreversible actions without documented kill-switch, approval-gate, or human-in-the-loop control.', severity: 'high', reasoningModes: ['control_effectiveness', 'four_eyes_stress'], sources: ['EU AI Act', 'NIST AI RMF'] },

  // ── Wave 4 — AI synthetic-media fraud ───────────────────────────────
  { id: 'rf_ai_synthetic_ceo_deepfake', typology: 'ai_synthetic_media_fraud', indicator: 'Payment or policy instruction apparently authorised via live video/voice call matching the profile of a known deepfake CEO-fraud pattern.', severity: 'high', reasoningModes: ['linguistic_forensics', 'pattern_of_life', 'timeline_reconstruction'], sources: [] },
  { id: 'rf_ai_synthetic_kyc_bypass', typology: 'ai_synthetic_media_fraud', indicator: 'Onboarding liveness / biometric check shows indicators of face-swap, liveness spoof, or AI-generated document.', severity: 'high', reasoningModes: ['linguistic_forensics', 'entity_resolution'], sources: [] },

  // ── Wave 6 — crypto on-/off-ramp obfuscation ────────────────────────
  { id: 'rf_crypto_onramp_card_to_mixer', typology: 'crypto_onramp_obfuscation', indicator: 'Card-funded crypto purchase on a centralised exchange followed within minutes by withdrawal to a private wallet that subsequently routes through a mixer or chain-hop.', severity: 'high', reasoningModes: ['chain_analysis', 'taint_propagation', 'velocity_analysis'], sources: ['FATF VASP guidance', 'Chainalysis crypto crime report'] },
  { id: 'rf_crypto_offramp_otc_cash', typology: 'crypto_onramp_obfuscation', indicator: 'Privacy-coin or mixer-tainted crypto sold via unlicensed P2P / OTC desk for fiat cash with no Travel-Rule data and no KYC linkage to the originator.', severity: 'high', reasoningModes: ['vasp_travel_rule', 'chain_analysis', 'jurisdiction_cascade'], sources: ['FATF R.16', 'FATF VASP guidance'] },

  // ── Wave 6 — NPO diversion (terrorism financing predicate) ──────────
  { id: 'rf_npo_field_office_cash_payouts', typology: 'npo_diversion', indicator: 'Charity field office in a conflict-affected area issues large cash payouts with no beneficiary register or with beneficiaries that cannot be independently verified.', severity: 'high', reasoningModes: ['source_triangulation', 'jurisdiction_cascade', 'documentation_quality'], sources: ['FATF R.8', 'UN 1267 / 1373'] },
  { id: 'rf_npo_donor_chain_circular', typology: 'npo_diversion', indicator: 'Inbound donations originate from related parties or shell entities and the funds flow back as field-office expenses to the same beneficial network — a circular donor chain.', severity: 'high', reasoningModes: ['link_analysis', 'community_detection', 'reconciliation'], sources: ['FATF R.8'] },

  // ── Wave 6 — shell-layering / sanctions evasion ─────────────────────
  { id: 'rf_shell_director_overlap', typology: 'shell_company_chain', indicator: 'The same nominee director, registered agent, or company-formation service appears across more than five shell entities active simultaneously, several of which are counterparties to one another.', severity: 'high', reasoningModes: ['entity_resolution', 'community_detection', 'ubo_nominee_directors'], sources: ['FATF R.24', 'OpenCorporates typology'] },
  { id: 'rf_shell_back_to_back', typology: 'shell_company_chain', indicator: 'Loan, supply, or service contract between two related shell entities with offsetting terms and no apparent operational substance — classic back-to-back layering.', severity: 'high', reasoningModes: ['reconciliation', 'narrative_coherence', 'ubo_tree_walk'], sources: ['Wolfsberg FAQ', 'FATF RBA'] },

  // ── Wave 6 — bearer-share / free-zone loophole ──────────────────────
  { id: 'rf_bearer_share_fz_holding', typology: 'bearer_share_fz_loophole', indicator: 'UAE / GCC free-zone holding entity registered with bearer-share equivalent or undisclosed beneficial owner not refreshed against the local UBO register.', severity: 'high', reasoningModes: ['ubo_bearer_shares', 'ubo_tree_walk', 'jurisdiction_cascade'], sources: ['FDL No.10/2025', 'FATF R.24'] },
  { id: 'rf_fz_no_substance', typology: 'bearer_share_fz_loophole', indicator: 'Free-zone licensee with mailbox-only office, zero employees, and no demonstrable economic activity yet invoicing mainland operations or third-country counterparties at material volume.', severity: 'high', reasoningModes: ['kyb_strict', 'narrative_coherence', 'reconciliation'], sources: ['UAE Cabinet Resolution 31/2019 — Economic Substance', 'FATF R.24'] },

  // ── Wave 6 — TBML invoice anomalies ─────────────────────────────────
  { id: 'rf_tbml_round_trip', typology: 'tbml', indicator: 'Same goods or HS-code class invoiced multiple times between related parties across jurisdictions within a short window — carousel / round-trip pattern.', severity: 'high', reasoningModes: ['tbml_overlay', 'tbml_over_invoicing', 'reconciliation', 'community_detection'], sources: ['FATF TBML report', 'WCO carousel-fraud typology'] },
  { id: 'rf_tbml_unit_price_outlier', typology: 'tbml', indicator: 'Per-unit declared price diverges by more than three standard deviations from peer-benchmark shipments of the same HS-code in the same month.', severity: 'medium', reasoningModes: ['regression', 'peer_benchmark', 'commodity_price_anomaly'], sources: ['FATF TBML report'] },

  // ── Wave 6 — synthetic identity / mule funnel ───────────────────────
  { id: 'rf_synthetic_id_thin_file', typology: 'synthetic_identity', indicator: 'Identity record presents as adult yet credit / utility / address footprint is under 90 days and shows no historical address change — characteristic synthetic-identity pattern.', severity: 'high', reasoningModes: ['synthetic_id', 'entity_resolution', 'pattern_of_life'], sources: ['FRB synthetic-identity toolkit'] },
  { id: 'rf_funnel_rapid_disburse', typology: 'funnel_account', indicator: 'Account aggregates ten or more inbound transfers from unrelated payers and disburses more than 90% of the consolidated balance within 24 hours to third-party accounts.', severity: 'high', reasoningModes: ['velocity_analysis', 'pattern_of_life', 'spike_detection'], sources: ['FATF mule-network typology'] },

  // ── Wave 5 — extended red flag catalogue ────────────────────────────
  // KYC/CDD gaps
  { id: 'rf_incomplete_kyc', typology: 'kyc_gap', indicator: 'Customer file missing mandatory CDD documents at onboarding or review', severity: 'high', reasoningModes: ['documentation_quality', 'retention_audit'], sources: ['FATF R.10', 'FDL No.10/2025 Art.10'] },
  { id: 'rf_inconsistent_id', typology: 'kyc_gap', indicator: 'Identity documents submitted by customer are inconsistent with each other or with external registry data', severity: 'high', reasoningModes: ['entity_resolution', 'documentation_quality'], sources: ['FATF R.10'] },
  { id: 'rf_address_mismatch', typology: 'kyc_gap', indicator: "Customer's declared address does not match registered address, utility records, or IP geolocation", severity: 'medium', reasoningModes: ['pattern_of_life', 'entity_resolution'], sources: ['FATF R.10'] },
  { id: 'rf_nominee_director', typology: 'ubo', indicator: 'Director or shareholder identified as professional nominee with no operational role', severity: 'high', reasoningModes: ['ubo_nominee_directors', 'entity_resolution'], sources: ['FATF R.24'] },
  { id: 'rf_pep_undisclosed', typology: 'pep', indicator: 'Customer is a PEP but failed to self-declare at onboarding or during periodic review', severity: 'high', reasoningModes: ['pep_domestic_minister', 'source_triangulation'], sources: ['FATF R.12'] },
  { id: 'rf_pep_step_down_unjustified', typology: 'pep', indicator: 'Former PEP applying for step-down with insufficient cooling-off period or continued influence', severity: 'medium', reasoningModes: ['timeline_reconstruction', 'narrative_coherence'], sources: ['FATF R.12'] },
  { id: 'rf_passport_retention', typology: 'kyc_gap', indicator: 'Passport or identity document held by employer or third party suggesting forced labour or trafficking', severity: 'high', reasoningModes: ['pattern_of_life', 'source_triangulation'], sources: ['FATF R.10', 'Palermo Protocol'] },
  { id: 'rf_disproportionate_wealth', typology: 'source_of_wealth', indicator: "Customer's declared or observable assets are disproportionate to known lawful income", severity: 'high', reasoningModes: ['source_triangulation', 'regression', 'narrative_coherence'], sources: ['FATF R.12', 'Wolfsberg FAQ'] },
  { id: 'rf_undocumented_wealth', typology: 'source_of_wealth', indicator: 'Customer unable to provide any documentary evidence corroborating declared source of wealth', severity: 'high', reasoningModes: ['documentation_quality', 'source_triangulation'], sources: ['FATF R.12'] },
  { id: 'rf_unverifiable_sof', typology: 'source_of_funds', indicator: 'Declared source of funds cannot be independently verified through documentation or counterparty records', severity: 'high', reasoningModes: ['documentation_quality', 'source_credibility'], sources: ['FATF R.10', 'Wolfsberg FAQ'] },
  // Transaction patterns
  { id: 'rf_threshold_avoidance', typology: 'structuring', indicator: 'Transaction amounts consistently just below reporting or monitoring thresholds suggesting deliberate avoidance', severity: 'high', reasoningModes: ['velocity_analysis', 'spike_detection', 'threshold_monitoring'], sources: ['FATF RBA', 'UAE FIU typology'] },
  { id: 'rf_pattern_change', typology: 'transaction_monitoring', indicator: "Customer's transaction pattern deviates materially from established baseline with no business explanation", severity: 'medium', reasoningModes: ['pattern_of_life', 'peer_group_anomaly', 'spike_detection'], sources: ['Wolfsberg FAQ', 'FATF RBA'] },
  { id: 'rf_unexpected_velocity', typology: 'transaction_monitoring', indicator: 'Transaction velocity spikes to multiples of 12-month average with no documented business rationale', severity: 'high', reasoningModes: ['velocity_analysis', 'spike_detection'], sources: ['FATF RBA'] },
  { id: 'rf_cash_above_threshold', typology: 'dpms_retail', indicator: 'Cash transaction at or above the DPMS or CTR threshold requiring mandatory reporting', severity: 'high', reasoningModes: ['dpms_retail_threshold', 'cash_courier_ctn'], sources: ['MoE DNFBP circular'] },
  { id: 'rf_cash_intensive', typology: 'structuring', indicator: 'Customer with no obvious cash-intensive business profile transacting primarily in physical cash', severity: 'high', reasoningModes: ['pattern_of_life', 'peer_group_anomaly'], sources: ['FATF RBA'] },
  { id: 'rf_round_amount_offset', typology: 'structuring', indicator: 'Series of exactly round-amount transactions offset by small irregular amounts — classic structuring artefact', severity: 'medium', reasoningModes: ['velocity_analysis', 'spike_detection', 'reconciliation'], sources: ['FATF RBA'] },
  { id: 'rf_smurf_network', typology: 'structuring', indicator: 'Multiple individuals making sub-threshold deposits into the same account — smurfing network', severity: 'high', reasoningModes: ['link_analysis', 'community_detection', 'velocity_analysis'], sources: ['FATF RBA', 'UAE FIU typology'] },
  { id: 'rf_third_party_funding', typology: 'source_of_funds', indicator: 'Account funded by unrelated third parties with no clear business or family relationship', severity: 'high', reasoningModes: ['link_analysis', 'source_triangulation'], sources: ['Wolfsberg FAQ', 'FATF R.10'] },
  { id: 'rf_third_party_payment', typology: 'transaction_monitoring', indicator: 'Payment made on behalf of or received from an undisclosed third party', severity: 'medium', reasoningModes: ['link_analysis', 'entity_resolution'], sources: ['FATF R.10', 'Wolfsberg FAQ'] },
  { id: 'rf_loan_back_scheme', typology: 'layering', indicator: 'Customer deposits funds then receives a loan from a related entity for the same amount — loan-back layering', severity: 'high', reasoningModes: ['reconciliation', 'narrative_coherence', 'link_analysis'], sources: ['FATF RBA'] },
  // KYB / Corporate
  { id: 'rf_complex_ownership', typology: 'ubo', indicator: 'Corporate structure involves multiple layered entities across jurisdictions without apparent business rationale', severity: 'high', reasoningModes: ['ubo_tree_walk', 'jurisdiction_cascade', 'entity_resolution'], sources: ['FATF R.24'] },
  { id: 'rf_ubo_chain_break', typology: 'ubo', indicator: 'Beneficial ownership chain cannot be traced to a natural person — break in ownership chain', severity: 'high', reasoningModes: ['ubo_tree_walk', 'entity_resolution'], sources: ['FATF R.24'] },
  { id: 'rf_no_substance', typology: 'shell_company', indicator: 'Entity has no physical presence, employees, or genuine economic activity in its registered jurisdiction', severity: 'high', reasoningModes: ['kyb_strict', 'narrative_coherence'], sources: ['FATF R.24', 'UAE Economic Substance Regulations'] },
  { id: 'rf_common_address', typology: 'ubo', indicator: 'Multiple unrelated entities share the same registered address suggesting a formation-agent shell cluster', severity: 'medium', reasoningModes: ['entity_resolution', 'community_detection'], sources: ['OpenCorporates typology'] },
  { id: 'rf_offshore_concentration', typology: 'shell_company', indicator: "Customer's counterparties are concentrated in high-secrecy offshore jurisdictions with no apparent business nexus", severity: 'high', reasoningModes: ['jurisdiction_cascade', 'link_analysis'], sources: ['FATF R.24'] },
  { id: 'rf_high_risk_jurisdiction', typology: 'sanctions_evasion', indicator: 'Transaction or customer nexus with FATF Call-for-Action or Increased-Monitoring jurisdiction', severity: 'high', reasoningModes: ['jurisdiction_cascade', 'sanctions_regime_matrix'], sources: ['FATF RBA', 'CR 74/2020'] },
  { id: 'rf_offshore_account_undisclosed', typology: 'tax_evasion', indicator: 'Evidence of offshore account or asset not declared to regulatory authority', severity: 'high', reasoningModes: ['source_triangulation', 'pattern_of_life'], sources: ['FATF R.3', 'OECD CRS'] },
  { id: 'rf_offshore_buyer', typology: 'real_estate_aml', indicator: 'Real estate purchaser is an offshore entity with no disclosed beneficial owner', severity: 'high', reasoningModes: ['ubo_tree_walk', 'entity_resolution', 'jurisdiction_cascade'], sources: ['FATF DNFBP guidance'] },
  { id: 'rf_shell_bank', typology: 'correspondent_banking', indicator: 'Correspondent customer identified as a shell bank with no physical presence and no regulatory licence', severity: 'high', reasoningModes: ['kyb_strict', 'entity_resolution'], sources: ['FATF R.13', 'Wolfsberg Correspondent Banking Principles'] },
  { id: 'rf_nested', typology: 'correspondent_banking', indicator: 'Respondent bank is providing correspondent services to a third-party bank without disclosure', severity: 'high', reasoningModes: ['kyb_strict', 'link_analysis'], sources: ['FATF R.13'] },
  { id: 'rf_payable_through', typology: 'correspondent_banking', indicator: 'Payable-through account used to give third parties direct access to correspondent services', severity: 'high', reasoningModes: ['kyb_strict', 'entity_resolution'], sources: ['FATF R.13', 'Wolfsberg FAQ'] },
  { id: 'rf_pass_through_kyc', typology: 'correspondent_banking', indicator: 'Respondent bank relying on third-party KYC without own customer verification', severity: 'medium', reasoningModes: ['documentation_quality', 'source_credibility'], sources: ['FATF R.17'] },
  // Crypto / VASP
  { id: 'rf_chain_hop', typology: 'vasp', indicator: 'Funds routed through multiple blockchain networks or bridges to obscure transaction trail', severity: 'high', reasoningModes: ['chain_analysis', 'taint_propagation'], sources: ['FATF VASP guidance'] },
  { id: 'rf_mixer_exposure', typology: 'vasp', indicator: 'Wallet has direct or indirect exposure to a known mixer or obfuscation service', severity: 'high', reasoningModes: ['chain_analysis', 'taint_propagation'], sources: ['FATF VASP guidance', 'OFAC mixer advisory'] },
  { id: 'rf_privacy_coin', typology: 'vasp', indicator: 'Transaction involves a privacy coin (Monero, Zcash, Dash) without Travel Rule data', severity: 'high', reasoningModes: ['privacy_coin_reasoning', 'chain_analysis'], sources: ['FATF R.16'] },
  { id: 'rf_self_hosted_wallet', typology: 'vasp', indicator: 'Transfer to or from an unhosted (self-custodied) wallet above threshold without counterparty verification', severity: 'medium', reasoningModes: ['chain_analysis', 'vasp_travel_rule'], sources: ['FATF R.16', 'EU TFR'] },
  { id: 'rf_missing_originator', typology: 'vasp', indicator: 'Incoming crypto transfer above threshold is missing required originator information', severity: 'high', reasoningModes: ['vasp_travel_rule', 'completeness_audit'], sources: ['FATF R.16'] },
  { id: 'rf_missing_beneficiary', typology: 'vasp', indicator: 'Outgoing crypto transfer is missing required beneficiary information', severity: 'high', reasoningModes: ['vasp_travel_rule', 'completeness_audit'], sources: ['FATF R.16'] },
  { id: 'rf_sanctioned_ip', typology: 'sanctions_evasion', indicator: 'Login or transaction originates from an IP address geolocated to a sanctioned jurisdiction', severity: 'high', reasoningModes: ['jurisdiction_cascade', 'sanctions_regime_matrix'], sources: ['OFAC', 'CR 74/2020'] },
  { id: 'rf_dark_fleet', typology: 'sanctions_evasion', indicator: 'Vessel linked to dark/shadow fleet with AIS manipulation or flag-of-convenience pattern', severity: 'high', reasoningModes: ['sanctions_maritime_stss', 'timeline_reconstruction'], sources: ['OFAC maritime advisory', 'UK OFSI'] },
  { id: 'rf_price_cap_breach', typology: 'sanctions_evasion', indicator: 'Petroleum cargo priced above the G7/EU price cap for Russian crude without exception documentation', severity: 'high', reasoningModes: ['commodity_price_anomaly', 'sanctions_regime_matrix'], sources: ['EU Russia sanctions', 'OFAC price cap guidance'] },
  { id: 'rf_platform_aggregation', typology: 'vasp', indicator: 'Customer aggregates large volumes across multiple VASP platforms to avoid single-platform reporting thresholds', severity: 'high', reasoningModes: ['velocity_analysis', 'link_analysis', 'spike_detection'], sources: ['FATF VASP guidance'] },
  { id: 'rf_synthetic_persona', typology: 'synthetic_identity', indicator: 'Customer profile shows synthetic-persona characteristics: thin file, fabricated history, inconsistent biometrics', severity: 'high', reasoningModes: ['synthetic_id', 'entity_resolution', 'linguistic_forensics'], sources: ['FRB synthetic-identity toolkit'] },
  { id: 'rf_face_swap', typology: 'ai_synthetic_media_fraud', indicator: 'Liveness check shows signs of face-swap or presentation attack', severity: 'high', reasoningModes: ['linguistic_forensics', 'entity_resolution'], sources: ['FATF R.10'] },
  { id: 'rf_liveness_bypass', typology: 'ai_synthetic_media_fraud', indicator: 'Biometric liveness check bypassed or returns anomalous confidence score', severity: 'high', reasoningModes: ['entity_resolution', 'linguistic_forensics'], sources: ['FATF R.10'] },
  { id: 'rf_voice_clone', typology: 'ai_synthetic_media_fraud', indicator: 'Voice instruction or authorisation call exhibits voice-clone artefacts', severity: 'high', reasoningModes: ['linguistic_forensics', 'pattern_of_life'], sources: [] },
  { id: 'rf_injection_attack', typology: 'ai_governance_breach', indicator: 'Compliance AI system received input that appears to manipulate model output or bypass controls', severity: 'high', reasoningModes: ['attack_tree', 'control_effectiveness'], sources: ['OWASP LLM Top 10'] },
  { id: 'rf_llm_prompt_injection', typology: 'ai_governance_breach', indicator: 'LLM received a prompt that appears to instruct it to ignore safety constraints or produce harmful output', severity: 'high', reasoningModes: ['attack_tree', 'control_effectiveness'], sources: ['OWASP LLM Top 10'] },
  { id: 'rf_unverified_subagent', typology: 'ai_governance_breach', indicator: 'Agentic AI sub-task delegated to an unverified model or tool without human authorisation', severity: 'high', reasoningModes: ['control_effectiveness', 'four_eyes_stress'], sources: ['EU AI Act', 'NIST AI RMF'] },
  { id: 'rf_unbounded_model_use', typology: 'ai_governance_breach', indicator: 'AI model deployed without usage restrictions, rate limits, or scope constraints', severity: 'medium', reasoningModes: ['control_effectiveness', 'policy_drift'], sources: ['ISO/IEC 42001', 'EU AI Act'] },
  { id: 'rf_no_model_card', typology: 'ai_governance_breach', indicator: 'AI model in production has no model card, evaluation report, or transparency documentation', severity: 'medium', reasoningModes: ['documentation_quality', 'retention_audit'], sources: ['EU AI Act Art.11', 'ISO/IEC 42001'] },
  { id: 'rf_unmonitored_drift', typology: 'ai_governance_breach', indicator: 'AI model in production has not been monitored for performance drift since deployment', severity: 'medium', reasoningModes: ['policy_drift', 'control_effectiveness'], sources: ['ISO/IEC 42001', 'NIST AI RMF'] },
  // Trade / TBML
  { id: 'rf_invoice_anomaly', typology: 'tbml', indicator: 'Commercial invoice contains anomalies: missing signatures, inconsistent quantities, implausible unit prices', severity: 'high', reasoningModes: ['tbml_over_invoicing', 'documentation_quality'], sources: ['FATF TBML report'] },
  { id: 'rf_circular_trade', typology: 'tbml', indicator: 'Same goods invoiced in a circular pattern across related counterparties with no net economic purpose', severity: 'high', reasoningModes: ['tbml_overlay', 'reconciliation', 'community_detection'], sources: ['FATF TBML report'] },
  { id: 'rf_phantom_shipment', typology: 'tbml', indicator: 'Trade documentation references shipment that cannot be verified against vessel tracking or port records', severity: 'high', reasoningModes: ['tbml_phantom_shipment', 'timeline_reconstruction'], sources: ['FATF TBML report'] },
  { id: 'rf_mislabel_freight', typology: 'tbml', indicator: 'Freight or cargo description inconsistent with HS-code, shipping route, or counterparty profile', severity: 'high', reasoningModes: ['tbml_overlay', 'documentation_quality'], sources: ['WCO', 'FATF TBML report'] },
  { id: 'rf_dual_use', typology: 'proliferation', indicator: 'Goods or technology have both civilian and military applications and the end-use is unverified', severity: 'high', reasoningModes: ['pf_dual_use_controls', 'sanctions_regime_matrix'], sources: ['UN 1540', 'EU dual-use regulation'] },
  { id: 'rf_eu_certificate_anomaly', typology: 'tbml', indicator: 'EU origin certificate or AEO authorisation shows anomalies or cannot be verified with issuing authority', severity: 'medium', reasoningModes: ['documentation_quality', 'source_credibility'], sources: ['EU Customs Code'] },
  { id: 'rf_truncated_address', typology: 'tbml', indicator: 'Correspondent message or trade document contains truncated counterparty address obscuring jurisdiction', severity: 'medium', reasoningModes: ['completeness_audit', 'documentation_quality'], sources: ['FATF R.16', 'Wolfsberg FAQ'] },
  // Environmental crime
  { id: 'rf_illegal_logging', typology: 'environmental_crime', indicator: 'Timber shipment without valid FLEGT licence or from a region with illegal-logging enforcement action', severity: 'high', reasoningModes: ['provenance_trace', 'jurisdiction_cascade'], sources: ['FATF R.3 (2021)', 'EU EUDR'] },
  { id: 'rf_iuu_catch', typology: 'environmental_crime', indicator: 'Seafood product without FAO catch certificate or from a vessel on the RFMO IUU vessel list', severity: 'high', reasoningModes: ['provenance_trace', 'source_credibility'], sources: ['FAO', 'FATF R.3 (2021)'] },
  { id: 'rf_cites_certificate_anomaly', typology: 'environmental_crime', indicator: 'CITES permit for wildlife product is missing, expired, or cannot be verified with issuing authority', severity: 'high', reasoningModes: ['documentation_quality', 'source_credibility'], sources: ['CITES', 'FATF R.3 (2021)'] },
  { id: 'rf_cahra_origin', typology: 'environmental_crime', indicator: 'Mineral commodity originates from a conflict-affected or high-risk area without OECD DDG Annex II documentation', severity: 'high', reasoningModes: ['oecd_ddg_annex', 'provenance_trace'], sources: ['OECD DDG', 'LBMA RGG'] },
  { id: 'rf_kpcs_mismatch', typology: 'environmental_crime', indicator: 'Rough diamond presented without Kimberley Process certificate or with certificate that does not match the parcel', severity: 'high', reasoningModes: ['documentation_quality', 'provenance_trace'], sources: ['Kimberley Process', 'FATF R.3'] },
  { id: 'rf_carbon_double_counting', typology: 'carbon_market_fraud', indicator: 'Carbon credits appear to be claimed across multiple registries or without corresponding Article 6 adjustment', severity: 'high', reasoningModes: ['reconciliation', 'provenance_trace'], sources: ['Article 6 Paris Agreement', 'ICVCM'] },
  { id: 'rf_greenwash_marketing', typology: 'carbon_market_fraud', indicator: 'Carbon-credit marketing claims not supported by underlying project documentation or independent verification', severity: 'medium', reasoningModes: ['documentation_quality', 'source_credibility'], sources: ['ICVCM Core Carbon Principles'] },
  { id: 'rf_forced_labour_supply_chain', typology: 'environmental_crime', indicator: 'Supply-chain audit flags forced labour in production or extraction without remediation plan', severity: 'high', reasoningModes: ['provenance_trace', 'jurisdiction_cascade'], sources: ['FATF R.3', 'Palermo Protocol'] },
  { id: 'rf_armed_group_proximity', typology: 'environmental_crime', indicator: 'Commodity supply chain passes through territory controlled by armed non-state actors', severity: 'high', reasoningModes: ['oecd_ddg_annex', 'jurisdiction_cascade'], sources: ['OECD DDG Annex II', 'FATF R.3'] },
  { id: 'rf_dpr_iran_nexus', typology: 'sanctions_evasion', indicator: 'Transaction or counterparty has nexus to DPRK or Iran-linked entity or jurisdiction', severity: 'high', reasoningModes: ['sanctions_regime_matrix', 'jurisdiction_cascade'], sources: ['UN 1718', 'UN 2231', 'OFAC', 'CR 74/2020'] },
  { id: 'rf_wage_underpayment', typology: 'environmental_crime', indicator: 'Supplier pays wages below legal minimum suggesting labour exploitation as business model', severity: 'medium', reasoningModes: ['pattern_of_life', 'source_triangulation'], sources: ['ILO', 'FATF R.3'] },
  // Governance / controls
  { id: 'rf_alert_fatigue', typology: 'governance', indicator: 'Analyst dismisses alerts without documented rationale — bulk dismissal pattern suggesting alert fatigue', severity: 'high', reasoningModes: ['exception_log', 'policy_drift', 'peer_group_anomaly'], sources: ['FATF R.18', 'CR 134/2025'] },
  { id: 'rf_appetite_silence', typology: 'governance', indicator: 'Risk appetite statement has not been reviewed or updated for more than 12 months', severity: 'medium', reasoningModes: ['policy_drift', 'retention_audit'], sources: ['FATF R.1', 'CR 134/2025'] },
  { id: 'rf_override_log_silence', typology: 'governance', indicator: 'Manual override applied to a screening or monitoring alert with no log entry or approval record', severity: 'high', reasoningModes: ['exception_log', 'four_eyes_stress', 'retention_audit'], sources: ['FDL 10/2025 Art.24', 'CR 134/2025'] },
  { id: 'rf_self_approval', typology: 'governance', indicator: 'User approves their own alert disposition or transaction without independent second-level sign-off', severity: 'high', reasoningModes: ['four_eyes_stress', 'exception_log'], sources: ['CR 134/2025 Art.19', 'Three Lines Model'] },
  { id: 'rf_committee_dormant', typology: 'governance', indicator: 'AML/CFT committee has not met within its scheduled interval — governance body dormant', severity: 'medium', reasoningModes: ['policy_drift', 'timeline_reconstruction'], sources: ['CR 134/2025', 'FATF R.18'] },
  { id: 'rf_finding_overdue', typology: 'governance', indicator: 'Internal audit or regulatory finding remains open beyond its agreed remediation deadline', severity: 'high', reasoningModes: ['retention_audit', 'timeline_reconstruction'], sources: ['Three Lines Model', 'FDL 10/2025'] },
  { id: 'rf_concealed_finding', typology: 'governance', indicator: 'Audit or compliance finding recorded as closed without evidence of actual remediation', severity: 'high', reasoningModes: ['retention_audit', 'exception_log'], sources: ['FDL 10/2025 Art.24'] },
  { id: 'rf_kri_breach_unreported', typology: 'governance', indicator: 'Key risk indicator has breached its threshold but no escalation or management notification was triggered', severity: 'high', reasoningModes: ['policy_drift', 'exception_log'], sources: ['CR 134/2025', 'Three Lines Model'] },
  { id: 'rf_late_filing', typology: 'governance', indicator: 'STR, FFR, or CTR filed after statutory deadline', severity: 'high', reasoningModes: ['timeline_reconstruction', 'retention_audit'], sources: ['FDL No.10/2025 Art.22', 'CR 74/2020'] },
  { id: 'rf_under_filing', typology: 'governance', indicator: 'Filing volume materially below peer benchmark suggesting under-reporting', severity: 'high', reasoningModes: ['peer_group_anomaly', 'regression'], sources: ['FATF R.20', 'FATF R.29'] },
  { id: 'rf_outdated_typology', typology: 'governance', indicator: 'AML programme references outdated typologies not updated since last FATF evaluation or NRA', severity: 'medium', reasoningModes: ['policy_drift', 'documentation_quality'], sources: ['FATF R.1'] },
  { id: 'rf_unrenewed_training', typology: 'governance', indicator: 'Staff AML training certification has lapsed beyond the mandatory renewal period', severity: 'medium', reasoningModes: ['training_inadequacy', 'retention_audit'], sources: ['FATF R.18'] },
  { id: 'rf_data_residency_violation', typology: 'governance', indicator: 'Customer data processed or stored outside permitted jurisdictions in violation of PDPL or contractual restrictions', severity: 'medium', reasoningModes: ['jurisdiction_cascade', 'policy_drift'], sources: ['UAE PDPL', 'GDPR'] },
  { id: 'rf_litigation_pattern', typology: 'governance', indicator: 'Customer or counterparty subject to repeated civil or regulatory litigation suggesting systemic conduct issues', severity: 'medium', reasoningModes: ['source_triangulation', 'pattern_of_life'], sources: ['Wolfsberg FAQ'] },
  { id: 'rf_regulator_enforcement', typology: 'governance', indicator: 'Customer or counterparty subject to recent regulatory enforcement action, fine, or licence sanction', severity: 'high', reasoningModes: ['source_triangulation', 'source_credibility'], sources: ['Wolfsberg FAQ', 'FATF R.29'] },
  { id: 'rf_relationship_manager_disclosed', typology: 'governance', indicator: 'Relationship manager has a personal or financial connection to the customer that was not declared', severity: 'high', reasoningModes: ['policy_drift', 'four_eyes_stress'], sources: ['Three Lines Model', 'CR 134/2025'] },
  { id: 'rf_continuing_activity', typology: 'governance', indicator: 'Suspicious activity identified but no STR filed and activity continues — continuing suspicious activity not reported', severity: 'high', reasoningModes: ['retention_audit', 'timeline_reconstruction'], sources: ['FDL No.10/2025 Art.22', 'FATF R.20'] },
  { id: 'rf_unusual_access', typology: 'governance', indicator: 'User accesses system records outside their role scope or during unusual hours', severity: 'medium', reasoningModes: ['velocity_analysis', 'pattern_of_life'], sources: ['ISO/IEC 42001', 'Three Lines Model'] },
  { id: 'rf_unauthorised_access', typology: 'governance', indicator: 'System or data accessed without valid authorisation credentials', severity: 'high', reasoningModes: ['pattern_of_life', 'attack_tree'], sources: ['UAE PDPL', 'ISO/IEC 27001'] },
  { id: 'rf_unauthorised_processing', typology: 'governance', indicator: 'Personal data processed without valid legal basis in violation of PDPL', severity: 'high', reasoningModes: ['policy_drift', 'documentation_quality'], sources: ['UAE PDPL'] },
  { id: 'rf_data_exfil', typology: 'insider_threat', indicator: 'Bulk data extracted and transferred to external location outside normal business operations', severity: 'high', reasoningModes: ['velocity_analysis', 'peer_group_anomaly', 'timeline_reconstruction'], sources: ['Three Lines Model', 'ISO/IEC 27001'] },
  { id: 'rf_excess_retention', typology: 'governance', indicator: 'Personal data retained beyond the maximum retention period prescribed by PDPL or internal policy', severity: 'medium', reasoningModes: ['retention_audit', 'policy_drift'], sources: ['UAE PDPL', 'FDL 10/2025 Art.24'] },
  { id: 'rf_premature_destruction', typology: 'governance', indicator: 'AML records destroyed before the minimum 5-year retention period', severity: 'high', reasoningModes: ['retention_audit', 'timeline_reconstruction'], sources: ['FDL 10/2025 Art.24'] },
  { id: 'rf_undisclosed_rca', typology: 'pep', indicator: 'Customer is a relative or close associate of a PEP but failed to disclose the connection', severity: 'high', reasoningModes: ['pep_domestic_minister', 'link_analysis'], sources: ['FATF R.12'] },
  { id: 'rf_arrest_article', typology: 'adverse_media', indicator: 'Adverse media reports customer or counterparty arrested, charged, or convicted of a financial crime', severity: 'high', reasoningModes: ['source_triangulation', 'freshness_check', 'source_credibility'], sources: ['Wolfsberg FAQ'] },
  { id: 'rf_close_match', typology: 'sanctions_screening', indicator: 'Screening engine returns a high-similarity match to a sanctioned name requiring disambiguation', severity: 'high', reasoningModes: ['entity_resolution', 'source_triangulation'], sources: ['CR 74/2020', 'OFAC'] },
  { id: 'rf_customer_alerted', typology: 'tipping_off', indicator: 'Customer appears to have been informed, directly or indirectly, of an internal suspicion or investigation', severity: 'high', reasoningModes: ['narrative_coherence', 'timeline_reconstruction'], sources: ['FDL No.10/2025 Art.25'] },
  { id: 'rf_subcontractor_unknown', typology: 'third_party_risk', indicator: 'Service provider uses undisclosed subcontractors with access to customer data or AML-relevant processes', severity: 'medium', reasoningModes: ['documentation_quality', 'entity_resolution'], sources: ['FATF R.17', 'UAE PDPL'] },
  { id: 'rf_vendor_concentration', typology: 'third_party_risk', indicator: 'Critical compliance function relies on a single third-party vendor with no documented contingency', severity: 'medium', reasoningModes: ['policy_drift', 'control_effectiveness'], sources: ['Three Lines Model'] },
  { id: 'rf_single_customer', typology: 'third_party_risk', indicator: 'Payment service provider is financially dependent on a single customer creating undue concentration risk', severity: 'medium', reasoningModes: ['peer_group_anomaly', 'narrative_coherence'], sources: ['FATF RBA'] },
  { id: 'rf_program_manager_concentration', typology: 'third_party_risk', indicator: 'BaaS programme manager relies on a single sponsor bank creating systemic risk', severity: 'medium', reasoningModes: ['peer_group_anomaly', 'control_effectiveness'], sources: ['FATF RBA'] },
  { id: 'rf_third_party_premium', typology: 'insurance_aml', indicator: 'Insurance premium paid by an unrelated third party with no insurable interest', severity: 'high', reasoningModes: ['link_analysis', 'source_triangulation'], sources: ['FATF Insurance guidance', 'Wolfsberg FAQ'] },
  { id: 'rf_early_surrender', typology: 'insurance_aml', indicator: 'High-value insurance policy surrendered shortly after inception at a financial loss — classic placement layering', severity: 'high', reasoningModes: ['pattern_of_life', 'timeline_reconstruction'], sources: ['FATF Insurance guidance'] },
  { id: 'rf_minimal_play_pattern', typology: 'gaming', indicator: 'Gambling account deposits large sums but plays minimally before withdrawal — casino layering pattern', severity: 'high', reasoningModes: ['pattern_of_life', 'velocity_analysis'], sources: ['FATF Gambling guidance'] },
  { id: 'rf_chip_dumping', typology: 'gaming', indicator: 'Collusive loss of chips to a confederate to transfer value — chip dumping', severity: 'high', reasoningModes: ['link_analysis', 'pattern_of_life'], sources: ['FATF Gambling guidance'] },
  { id: 'rf_capital_market_restriction', typology: 'tax_evasion', indicator: 'Transaction structured to circumvent capital controls or cross-border reporting requirements', severity: 'high', reasoningModes: ['jurisdiction_cascade', 'velocity_analysis'], sources: ['FATF R.3', 'OECD CRS'] },
  { id: 'rf_cash_donations', typology: 'npo_diversion', indicator: 'NPO receives substantial cash donations without donor identification or acknowledgement records', severity: 'high', reasoningModes: ['documentation_quality', 'source_credibility'], sources: ['FATF R.8', 'UN 1267/1373'] },
  { id: 'rf_cross_border_charity', typology: 'npo_diversion', indicator: 'Charity transfers significant funds to a field office in a high-risk jurisdiction without adequate controls', severity: 'high', reasoningModes: ['jurisdiction_cascade', 'source_triangulation'], sources: ['FATF R.8'] },
  { id: 'rf_corporate_buyer_no_substance', typology: 'real_estate_aml', indicator: 'Real estate buyer is a newly incorporated corporate with no substance and no business rationale for the purchase', severity: 'high', reasoningModes: ['kyb_strict', 'narrative_coherence', 'ubo_tree_walk'], sources: ['FATF DNFBP guidance'] },
  { id: 'rf_cash_property_purchase', typology: 'real_estate_aml', indicator: 'Real estate purchased wholly or mainly in physical cash with no mortgage or verified bank transfer', severity: 'high', reasoningModes: ['documentation_quality', 'source_triangulation'], sources: ['FATF DNFBP guidance'] },
  { id: 'rf_ransom_note', typology: 'cyber_incident', indicator: 'Ransomware note or extortion demand received identifying a cryptocurrency payment address', severity: 'high', reasoningModes: ['chain_analysis', 'timeline_reconstruction'], sources: ['OFAC ransomware advisory'] },
  { id: 'rf_cuckoo_pattern', typology: 'structuring', indicator: 'Inbound deposits from unrelated third parties into accounts whose owners are unaware — cuckoo smurfing pattern', severity: 'high', reasoningModes: ['link_analysis', 'velocity_analysis', 'pattern_of_life'], sources: ['AUSTRAC typology', 'FATF RBA'] },
  { id: 'rf_residual_breach', typology: 'governance', indicator: 'Residual risk after control application still exceeds approved risk appetite threshold', severity: 'medium', reasoningModes: ['policy_drift', 'control_effectiveness'], sources: ['CR 134/2025', 'FATF R.1'] },
  { id: 'rf_unanswered_rfi', typology: 'kyc_gap', indicator: 'Request for information issued to customer remains unanswered beyond agreed response deadline', severity: 'high', reasoningModes: ['timeline_reconstruction', 'documentation_quality'], sources: ['FATF R.10'] },
  { id: 'rf_unusual_purpose', typology: 'kyc_gap', indicator: 'Customer is unable or unwilling to explain the intended purpose of the account or transaction in a plausible manner', severity: 'high', reasoningModes: ['narrative_coherence', 'documentation_quality', 'source_credibility'], sources: ['FATF R.10', 'Wolfsberg FAQ'] },
  { id: 'rf_25_pct_avoidance', typology: 'ubo', indicator: 'Corporate ownership structure designed to keep each individual holding below 25% threshold, avoiding UBO disclosure obligations', severity: 'high', reasoningModes: ['ubo_tree_walk', 'entity_resolution', 'community_detection'], sources: ['FATF R.24', 'FDL No.10/2025 Art.10'] },
  { id: 'rf_unverified_origin', typology: 'dpms_retail', indicator: 'Precious metal or gemstone presented for purchase without verified origin documentation or hallmark certification', severity: 'high', reasoningModes: ['provenance_trace', 'documentation_quality', 'source_credibility'], sources: ['MoE DNFBP circular', 'LBMA RGG', 'OECD DDG'] },
  { id: 'rf_unlicensed_msb', typology: 'transaction_monitoring', indicator: 'Customer or counterparty is operating a money service business or remittance operation without a valid MVTS licence', severity: 'high', reasoningModes: ['kyb_strict', 'entity_resolution', 'regulatory_mapping'], sources: ['FATF R.14', 'UAE MVTS regulations'] },
  { id: 'rf_50_pct_aggregation', typology: 'sanctions_screening', indicator: 'Two or more separately screened entities each hold just below 50% in a target entity; aggregate ownership meets or exceeds 50% SDN/HMT ownership rule', severity: 'high', reasoningModes: ['ubo_tree_walk', 'entity_resolution', 'sanctions_regime_matrix'], sources: ['OFAC 50% rule', 'UK OFSI', 'EU FSF'] },
];

export const RED_FLAGS_BY_TYPOLOGY: Record<string, RedFlag[]> = RED_FLAGS.reduce(
  (acc, rf) => {
    (acc[rf.typology] ||= []).push(rf);
    return acc;
  },
  {} as Record<string, RedFlag[]>,
);

export const RED_FLAG_BY_ID: Map<string, RedFlag> = new Map(
  RED_FLAGS.map((rf) => [rf.id, rf]),
);
