// Hawkeye Sterling — extended typology catalogue.
// Extra named patterns of conduct covering niche sectors. Purely descriptive
// labels (charter P3).

import type { Typology } from './typologies.js';

export const TYPOLOGIES_EXTENDED: Typology[] = [
  { id: 'funnel_accounts' as never, displayName: 'Funnel accounts', describes: 'Multiple unrelated payers feed one account with consolidated outbound.', redFlagIds: ['rfx_bank_funnel_account'], reasoningModes: ['community_detection', 'link_analysis'], doctrines: ['fatf_rba'] },
  { id: 'pass_through' as never, displayName: 'Pass-through', describes: 'Same-day inbound/outbound with narrow margin.', redFlagIds: ['rfx_bank_cross_border_same_day'], reasoningModes: ['velocity_analysis', 'chain_analysis'], doctrines: ['fatf_rba'] },
  { id: 'dormant_reactivation' as never, displayName: 'Dormant account reactivation', describes: 'Dormant accounts reactivated before large inbound.', redFlagIds: ['rfx_bank_dormant_reactivated'], reasoningModes: ['pattern_of_life', 'timeline_reconstruction'], doctrines: [] },
  { id: 'round_number_activity' as never, displayName: 'Round-number activity', describes: 'Round amounts without commercial rationale.', redFlagIds: ['rfx_bank_round_amounts'], reasoningModes: ['narrative_coherence'], doctrines: [] },
  { id: 'peel_chain' as never, displayName: 'Peel chain', describes: 'Layered crypto peel pattern.', redFlagIds: ['rfx_crypto_peel_chain'], reasoningModes: ['peel_chain'], doctrines: [] },
  { id: 'bridge_hop_offramp' as never, displayName: 'Bridge-hop-offramp', describes: 'Cross-chain bridge then rapid swap and off-ramp.', redFlagIds: ['rfx_crypto_bridge_rapid_swap'], reasoningModes: ['bridge_crossing_trace'], doctrines: [] },
  { id: 'sanction_cluster_proximity' as never, displayName: 'Sanction-cluster proximity', describes: 'Counterparty within hops of sanctioned wallets.', redFlagIds: ['rfx_crypto_sanction_cluster_hop'], reasoningModes: ['sanction_wallet_cluster', 'chain_analysis'], doctrines: [] },
  { id: 'flash_loan_exploit' as never, displayName: 'Flash-loan exploit', describes: 'Flash loan preceding state manipulation.', redFlagIds: ['rfx_crypto_flash_loan_then_drain'], reasoningModes: ['flash_loan_exploit', 'smart_contract_static_analysis'], doctrines: [] },
  { id: 'approval_sprawl' as never, displayName: 'Token-approval sprawl', describes: 'Unrevoked approvals across many contracts.', redFlagIds: ['rfx_crypto_approval_sprawl'], reasoningModes: ['token_approval_audit'], doctrines: [] },
  { id: 'dark_vessel_stss' as never, displayName: 'Dark-vessel ship-to-ship', describes: 'STSS with AIS dark period.', redFlagIds: ['rfx_sanc_stss' as string], reasoningModes: ['stss_ais_dark', 'sanctions_maritime_stss'], doctrines: [] },
  { id: 'flag_of_convenience' as never, displayName: 'Flag-of-convenience obfuscation', describes: 'Vessel ownership hidden via flag-of-convenience jurisdictions.', redFlagIds: [], reasoningModes: ['flag_of_convenience', 'vessel_beneficial_owner'], doctrines: [] },
  { id: 'tf_route_deviation' as never, displayName: 'Route deviation', describes: 'Vessel AIS deviates from LC route.', redFlagIds: ['rfx_tf_route_deviation'], reasoningModes: ['vessel_ais_gap_analysis'], doctrines: [] },
  { id: 'tf_phantom_shipment_v2' as never, displayName: 'Phantom shipment v2', describes: 'Paper shipment with no cargo movement (refined detection).', redFlagIds: ['rfx_tf_phantom_buyer', 'rfx_tf_route_deviation'], reasoningModes: ['tbml_phantom_shipment'], doctrines: ['fatf_rba'] },
  { id: 'tf_third_party_settlement' as never, displayName: 'Third-party LC settlement', describes: 'Payment under LC from unrelated third party.', redFlagIds: ['rfx_tf_third_party_pay'], reasoningModes: ['ucp600_discipline'], doctrines: [] },
  { id: 'commodity_price_outlier' as never, displayName: 'Commodity price outlier', describes: 'Price-per-unit outlier for HS code.', redFlagIds: ['rfx_tf_unit_price_outlier'], reasoningModes: ['commodity_price_anomaly', 'regression'], doctrines: [] },
  { id: 're_rapid_flip' as never, displayName: 'Rapid property flip', describes: 'Property resold quickly at different price.', redFlagIds: ['rfx_re_rapid_flip'], reasoningModes: ['re_rapid_flip_detection'], doctrines: [] },
  { id: 're_opaque_buyer' as never, displayName: 'Opaque property buyer', describes: 'Buyer shell with no market nexus.', redFlagIds: ['rfx_re_opaque_buyer'], reasoningModes: ['re_shell_owner_check'], doctrines: [] },
  { id: 're_advance_overpay' as never, displayName: 'Advance overpayment refund', describes: 'Off-plan advance overpay with refund.', redFlagIds: ['rfx_re_advance_overpay'], reasoningModes: ['re_off_plan_advance_check'], doctrines: [] },
  { id: 'ins_early_surrender' as never, displayName: 'Early surrender', describes: 'High premium surrendered in cooling-off window.', redFlagIds: ['rfx_ins_early_surrender'], reasoningModes: ['ins_early_surrender_cash'], doctrines: [] },
  { id: 'ins_premium_overfund' as never, displayName: 'Premium overfund and refund', describes: 'Overfund followed by refund demand.', redFlagIds: ['rfx_ins_overfund'], reasoningModes: ['ins_premium_overfund'], doctrines: [] },
  { id: 'npo_conflict_zone' as never, displayName: 'NPO conflict-zone disbursement', describes: 'Concentrated disbursement in conflict zone.', redFlagIds: ['rfx_npo_conflict_zone_disbursement'], reasoningModes: ['npo_conflict_zone_flow'], doctrines: ['fatf_rba'] },
  { id: 'gambling_junket_layering' as never, displayName: 'Junket layering', describes: 'Junket proceeds layered across accounts.', redFlagIds: ['rfx_gam_junket_inflow'], reasoningModes: ['casino_junket_flow'], doctrines: [] },
  { id: 'art_provenance_gap' as never, displayName: 'Art provenance gap', describes: 'Provenance chain gap > 10 years.', redFlagIds: ['rfx_art_provenance_gap'], reasoningModes: ['art_provenance_chain', 'lineage'], doctrines: [] },
  { id: 'auction_ring' as never, displayName: 'Auction ring', describes: 'Price-escalation ring across related dealers.', redFlagIds: ['rfx_art_ring_price_escalation'], reasoningModes: ['art_auction_ring_detection'], doctrines: [] },
  { id: 'market_layering' as never, displayName: 'Order layering', describes: 'Rapid place-and-cancel across a price move.', redFlagIds: ['rfx_mkt_layering_orders'], reasoningModes: ['layering_detection'], doctrines: [] },
  { id: 'marking_the_close' as never, displayName: 'Marking the close', describes: 'Impact trades at closing print.', redFlagIds: ['rfx_mkt_marking_close'], reasoningModes: ['marking_the_close'], doctrines: [] },
  { id: 'insider_pre_disclosure' as never, displayName: 'Pre-disclosure insider trading', describes: 'Insider-linked trading before material disclosure.', redFlagIds: ['rfx_mkt_insider_prior_disclosure'], reasoningModes: ['insider_threat'], doctrines: [] },
  { id: 'bec_typosquat' as never, displayName: 'Typosquat BEC', describes: 'Invoice from typosquat domain.', redFlagIds: ['rfx_bec_typosquat_invoice'], reasoningModes: ['typosquat_domain_detection'], doctrines: [] },
  { id: 'bec_late_redirect' as never, displayName: 'Late bank-details redirect', describes: 'Bank-details change near payment date.', redFlagIds: ['rfx_bec_redirect_late'], reasoningModes: ['invoice_redirection_trace'], doctrines: [] },
  { id: 'account_takeover_sim_swap' as never, displayName: 'Account takeover via SIM swap', describes: 'ATO sequence following SIM-swap.', redFlagIds: ['rfx_ato_sim_swap'], reasoningModes: ['sim_swap_indicator', 'account_takeover_sequence'], doctrines: [] },
  { id: 'dpms_doré_origin_gap' as never, displayName: 'Doré origin documentation gap', describes: 'Doré input lacking origin provenance.', redFlagIds: ['rfx_bullion_unknown_origin'], reasoningModes: ['doré_origin_crosscheck'], doctrines: ['lbma_rgg'] },
  { id: 'dpms_assay_mismatch' as never, displayName: 'Assay vs. refinery mismatch', describes: 'Assay certificate purity differs from refinery measurement.', redFlagIds: ['rfx_bullion_assay_mismatch'], reasoningModes: ['assay_certificate_audit', 'reconciliation'], doctrines: [] },
  { id: 'dpms_recycled_roundtrip' as never, displayName: 'Recycled round-trip', describes: 'Recycled inputs trace to recent outputs.', redFlagIds: ['rfx_bullion_recycled_round_trip'], reasoningModes: ['recycled_input_audit', 'trade_round_tripping'], doctrines: [] },
  { id: 'governance_schema_drift' as never, displayName: 'Governance — schema drift', describes: 'Feed schema drift causes mis-binding.', redFlagIds: ['rfx_dq_schema_drift'], reasoningModes: ['schema_drift_detection'], doctrines: [] },
  { id: 'governance_freshness_breach' as never, displayName: 'Governance — freshness breach', describes: 'Sanctions feed freshness SLA breached.', redFlagIds: ['rfx_dq_freshness_breach'], reasoningModes: ['freshness_sla_breach'], doctrines: [] },
];
