// POST /api/reports/xml
//
// Generate a schema-valid, deterministic goAML 3.0 XML report for
// regulatory submission to the UAE FIU.
//
// This route:
//   1. Validates the incoming envelope with validateGoamlEnvelope()
//   2. Serialises to XML using the deterministic serialiseGoamlXml()
//   3. Embeds a SHA-256 integrity hash in an XML comment header
//   4. Returns application/xml with result-id + hash headers
//
// The output is byte-identical for the same input envelope, making it
// suitable for audit-chain anchoring and regulatory archive workflows.
//
// Body: GoAmlEnvelope (see src/brain/goaml-shapes.ts for full schema)
//
// Returns: application/xml

import { NextResponse } from "next/server";
import { createHash } from "node:crypto";
import { enforce } from "@/lib/server/enforce";
import { serialiseGoamlXml } from "../../../../../dist/src/integrations/goaml-xml.js";
import { validateGoamlEnvelope } from "../../../../../dist/src/brain/goaml-shapes.js";
import type { GoAmlEnvelope } from "../../../../../dist/src/brain/goaml-shapes.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 20;

const VALID_REPORT_CODES = new Set(["STR", "SAR", "AIF", "RFI", "FFR", "PNMR", "CTR", "EFT", "HRC"]);

function validateRequest(raw: unknown): { ok: true; value: GoAmlEnvelope } | { ok: false; errors: string[] } {
  if (typeof raw !== "object" || raw === null) {
    return { ok: false, errors: ["Request body must be a JSON object (GoAmlEnvelope)"] };
  }
  const env = raw as GoAmlEnvelope;
  if (!VALID_REPORT_CODES.has(String((env as Record<string, unknown>)["reportCode"] ?? ""))) {
    return { ok: false, errors: [`reportCode must be one of: ${[...VALID_REPORT_CODES].join(", ")}`] };
  }
  const errors = validateGoamlEnvelope(env);
  if (errors.length > 0) return { ok: false, errors };
  return { ok: true, value: env };
}

export async function POST(req: Request): Promise<NextResponse | Response> {
  const t0 = Date.now();
  const gate = await enforce(req);
  if (!gate.ok) return gate.response;

  let raw: unknown;
  try {
    raw = await req.json();
  } catch {
    return NextResponse.json({ ok: false, error: "invalid_json", message: "Request body is not valid JSON" }, { status: 400 });
  }

  const validation = validateRequest(raw);
  if (!validation.ok) {
    return NextResponse.json(
      {
        ok: false,
        error: "validation_error",
        message: "GoAML envelope validation failed",
        errors: validation.errors,
        hint: "See /api/goaml for the full goAML submission workflow with auto-population. This endpoint accepts a pre-built GoAmlEnvelope.",
      },
      { status: 400 },
    );
  }

  const envelope = validation.value;

  let xmlBody: string;
  try {
    xmlBody = serialiseGoamlXml(envelope);
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    console.error("[reports/xml] serialiseGoamlXml failed", { internalRef: envelope.internalReference, detail });
    return NextResponse.json(
      { ok: false, error: "xml_generation_failed", detail },
      { status: 500 },
    );
  }

  // Integrity hash of the XML output (SHA-256)
  const xmlHash = createHash("sha256").update(xmlBody).digest("hex");

  // Embed integrity comment at the top of the XML (after the declaration)
  const ts = new Date().toISOString();
  const integrityComment = [
    `<!-- Hawkeye Sterling — goAML XML Report`,
    `     internalReference : ${envelope.internalReference}`,
    `     reportCode        : ${envelope.reportCode}`,
    `     generatedAt       : ${ts}`,
    `     sha256            : ${xmlHash}`,
    `     Do not edit this file — any change will invalidate the hash -->`,
  ].join("\n");

  const finalXml = xmlBody.startsWith("<?xml")
    ? xmlBody.replace(/^(<\?xml[^?]*\?>)/, `$1\n${integrityComment}`)
    : `${integrityComment}\n${xmlBody}`;

  const filename = `goaml-${envelope.reportCode.toLowerCase()}-${envelope.internalReference.replace(/[^a-z0-9-]/gi, "-")}-${ts.slice(0, 10)}.xml`;

  return new Response(finalXml, {
    status: 200,
    headers: {
      ...gate.headers,
      "content-type": "application/xml; charset=utf-8",
      "content-disposition": `attachment; filename="${filename}"`,
      "content-length": String(Buffer.byteLength(finalXml, "utf8")),
      "x-internal-reference": envelope.internalReference,
      "x-report-code": envelope.reportCode,
      "x-xml-sha256": xmlHash,
      "x-generated-at": ts,
      "x-latency-ms": String(Date.now() - t0),
      "cache-control": "no-store",
    },
  });
}
