"use client";

import { useEffect, useState } from "react";

interface CompliancePrintHeaderProps {
  reportTitle?: string;
  reportModule?: string;
}

function pad2(n: number) { return String(n).padStart(2, "0"); }

function buildRef(module: string, d: Date) {
  const y = d.getFullYear();
  const m = pad2(d.getMonth() + 1);
  const day = pad2(d.getDate());
  const h = pad2(d.getHours());
  const min = pad2(d.getMinutes());
  const s = pad2(d.getSeconds());
  const code = (module || "RPT").toUpperCase().replace(/[^A-Z0-9]/g, "-").replace(/-+/g, "-").slice(0, 14);
  return `HS-${code}-${y}${m}${day}-${h}${min}${s}`;
}

const REGS = [
  "UAE FDL No. 20/2018 — Anti-Money Laundering & Combating Financing of Terrorism",
  "UAE FDL No. 10/2025 — Regulation of Artificial Intelligence",
  "UAE Cabinet Decision No. 10/2019 — Implementing Regulations",
  "FATF Recommendations & Methodology (2023 revision)",
  "CBUAE AML/CFT Standards for Licensed Financial Institutions",
];

const row: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 24 };
const label: React.CSSProperties = { fontSize: 9, fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", color: "#666", minWidth: 130, flexShrink: 0 };
const value: React.CSSProperties = { fontSize: 10, color: "#111", fontFamily: "monospace" };
const hr: React.CSSProperties = { border: "none", borderTop: "1px solid #ccc", margin: "8px 0" };

export function CompliancePrintHeader({ reportTitle, reportModule }: CompliancePrintHeaderProps) {
  const [ts, setTs] = useState<Date | null>(null);

  useEffect(() => { setTs(new Date()); }, []);

  if (!ts) return null;

  const ref       = buildRef(reportModule ?? "RPT", ts);
  const dateStr   = ts.toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" });
  const timeStr   = ts.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", second: "2-digit" }) + " UTC";
  const title     = reportTitle ?? reportModule ?? "Compliance Report";
  const url       = typeof window !== "undefined" ? window.location.pathname : "";

  return (
    <div
      className="compliance-print-header"
      style={{ display: "none", fontFamily: "Arial, Helvetica, sans-serif", marginBottom: 24, pageBreakAfter: "avoid", breakAfter: "avoid" }}
    >
      {/* ── Top bar ── */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", borderBottom: "3px solid #111", paddingBottom: 10, marginBottom: 10 }}>
        <div>
          <div style={{ fontSize: 18, fontWeight: 900, letterSpacing: "-0.02em", color: "#111", lineHeight: 1.1 }}>HAWKEYE STERLING</div>
          <div style={{ fontSize: 9.5, color: "#555", marginTop: 2, letterSpacing: "0.05em", textTransform: "uppercase" }}>
            AML · CFT · Sanctions · AI Governance Platform
          </div>
        </div>
        <div style={{ textAlign: "right" }}>
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.06em", textTransform: "uppercase", color: "#111" }}>Compliance Report</div>
          <div style={{ fontSize: 9, color: "#888", marginTop: 2, fontFamily: "monospace" }}>{ref}</div>
        </div>
      </div>

      {/* ── Module title ── */}
      <div style={{ fontSize: 15, fontWeight: 800, color: "#111", letterSpacing: "-0.01em", marginBottom: 10 }}>
        {title.toUpperCase()}
      </div>

      {/* ── Metadata rows ── */}
      <div style={{ border: "1px solid #ddd", borderRadius: 4, padding: "10px 14px", background: "#fafafa" }}>
        <div style={row}>
          <span style={label}>Generated</span>
          <span style={value}>{dateStr} · {timeStr}</span>
        </div>
        <div style={hr} />
        <div style={row}>
          <span style={label}>Reference</span>
          <span style={value}>{ref}</span>
        </div>
        <div style={hr} />
        <div style={row}>
          <span style={label}>Module</span>
          <span style={value}>{title}{url ? ` (${url})` : ""}</span>
        </div>
        <div style={hr} />
        <div style={row}>
          <span style={label}>Classification</span>
          <span style={{ ...value, fontWeight: 700, color: "#b91c1c" }}>CONFIDENTIAL — Authorised Compliance Personnel Only</span>
        </div>
        <div style={hr} />
        <div style={{ ...row, alignItems: "flex-start" }}>
          <span style={label}>Regulatory Basis</span>
          <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
            {REGS.map((r, i) => (
              <span key={i} style={{ fontSize: 9.5, color: "#333" }}>• {r}</span>
            ))}
          </div>
        </div>
      </div>

      {/* ── Disclaimer ── */}
      <div style={{ marginTop: 8, fontSize: 8.5, color: "#999", borderTop: "1px solid #eee", paddingTop: 6 }}>
        This report is generated by Hawkeye Sterling and is intended solely for the use of authorised compliance
        personnel. Any reproduction, distribution, or disclosure to unauthorised parties is strictly prohibited.
        The data contained herein is subject to the confidentiality obligations of the receiving institution under
        UAE FDL No.20/2018 Art.24 and Cabinet Decision No.10/2019. Printed: {dateStr}.
      </div>

      {/* ── Separator before content ── */}
      <div style={{ borderTop: "2px solid #111", marginTop: 14, marginBottom: 20 }} />
    </div>
  );
}
