// Hawkeye Sterling — Asana "Modules" status board.
//
// One Asana task per operational module, living in the project
// "Hawkeye Sterling — Modules" (team HAWKEYE STERLING V2). A daily
// scheduled function posts a module-specific compliance attestation
// (full audit-ready field set) to each task. The task GIDs and the
// per-module fields below are sourced from the Module Compliance
// Register (docs/MODULE-COMPLIANCE-REGISTER.md).
//
// Override the project GID via ASANA_MODULES_PROJECT_GID if the board
// is re-created in another workspace.

export const ASANA_MODULES_PROJECT_GID =
  process.env["ASANA_MODULES_PROJECT_GID"] ?? "1215399932870281";

export interface AsanaModuleTask {
  /** App module key (matches asanaConfig / module-report routing). */
  key: string;
  /** Display label / report subject. */
  label: string;
  /** Asana task GID. */
  taskGid: string;
  /** One-line description of what the module does (report "Description"). */
  description: string;
  /** Concise control statement (report "Control in force"). */
  control: string;
  /** MoE / UAE obligation citation (report "Legal basis"). */
  obligation: string;
  /** Responsible role (report "Module owner"). */
  owner: string;
  /** Evidence retention period, e.g. "5 yrs" or "10 yrs". */
  retention: string;
}

export const ASANA_MODULE_TASKS: AsanaModuleTask[] = [
  // Onboarding & CDD
  { key: "client-portal", label: "Client Portal", taskGid: "1215389795331655",
    description: "Self-service onboarding capturing legal identity, UBOs and directors, auto-screened before MLRO decision.",
    control: "Identification, verification and screening enforced as a hard gate; no activation without a recorded MLRO disposition (fail-closed).",
    obligation: "Risk-based CDD before a business relationship — FDL 20/2018 Art.16; Cabinet 10/2019 Art.4-8; FATF R.10.",
    owner: "Compliance Officer → MLRO", retention: "5 yrs (decision log 10 yrs)" },
  { key: "ubo-declaration", label: "UBO Declaration", taskGid: "1215395029376154",
    description: "Captures and risk-rates every natural-person beneficial owner ≥25%, including layered/nominee structures.",
    control: "Activation blocked where the true beneficial owner cannot be established; bearer-share/nominee triggers EDD.",
    obligation: "Beneficial-ownership identification — Cabinet 58/2020; FDL 10/2025 Art.19; MoE UBO filing.",
    owner: "Compliance Officer; MLRO on EDD", retention: "5 yrs" },
  { key: "pep-profile", label: "PEP Profiles", taskGid: "1215399933160720",
    description: "Establishes PEP tier, source of wealth/funds, relationship network and EDD measures.",
    control: "Senior-management approval required before onboarding/continuing a PEP; EDD measures mandatory.",
    obligation: "PEP identification + senior approval + enhanced monitoring — Cabinet 10/2019 Art.15; FATF R.12.",
    owner: "MLRO + senior management", retention: "5 yrs" },
  { key: "cdd-review", label: "CDD Review", taskGid: "1215389795005123",
    description: "Risk-tiered periodic re-KYC with AI adequacy checking of file completeness.",
    control: "Periodic re-KYC cadence enforced (high 3-mo / med 6-mo / low annual); overdue files flagged.",
    obligation: "Ongoing CDD, records kept current — Cabinet 10/2019 Art.7; FATF R.10.",
    owner: "Compliance Officer; MLRO escalation", retention: "5 yrs" },
  { key: "data-quality", label: "Data Quality", taskGid: "1215399932805477",
    description: "Monitors CDD completeness portfolio-wide with AI remediation planning.",
    control: "Deficient files flagged and routed to remediation before reliance for screening/reporting.",
    obligation: "Adequate, accurate, up-to-date records — Cabinet 10/2019; FDL 20/2018 Art.16; FATF R.10.",
    owner: "Compliance Officer", retention: "5 yrs" },
  { key: "ownership", label: "Ownership Explorer", taskGid: "1215395029619715",
    description: "Maps UBO/ownership chains and detects shell-company and jurisdiction-layering risk.",
    control: "Look-through to ultimate control; chains >4 layers or circular structures trigger EDD/legal review.",
    obligation: "Understanding ownership & control — Cabinet 58/2020; FATF R.24/25.",
    owner: "Compliance Officer; MLRO on complex", retention: "5 yrs" },
  { key: "employees", label: "Employees", taskGid: "1215395028651392",
    description: "Staff register with Emirates ID/passport expiry and AML/CFT training currency.",
    control: "Expiring/lapsed ID documents and overdue AML/CFT training auto-flagged (30 days pre-expiry).",
    obligation: "Fit-and-proper staffing & employee screening — Cabinet 10/2019 Art.21; FDL 10/2025 Art.16.",
    owner: "Compliance Officer / HR", retention: "5 yrs" },
  { key: "approvals", label: "Approvals", taskGid: "1215395029091103",
    description: "Onboarding approval tracker (status, risk score, approved destinations) under four-eyes.",
    control: "Dual authorisation required; both signatories recorded under four-eyes.",
    obligation: "Internal controls & segregation of duties — FDL 10/2025 Art.20; Cabinet 10/2019 Art.21.",
    owner: "Compliance Officer (maker) + MLRO (checker)", retention: "5 yrs" },
  { key: "vendor-dd", label: "Supplier / Vendor DD", taskGid: "1215391560293131",
    description: "Third-party/supplier due diligence with AI risk and tiered re-assessment.",
    control: "Risk-tiered re-assessment cadence (critical annual / significant 18-mo / standard 24-mo).",
    obligation: "Counterparty/third-party risk — FATF R.10; OECD DDG; MoE DPMS supply-chain expectations.",
    owner: "Compliance Officer", retention: "5 yrs" },
  { key: "onboarding", label: "Onboarding Wizard", taskGid: "1215391559365147",
    description: "Guided new-customer intake routing to CDD/screening/MLRO.",
    control: "No-gaps intake path; cannot complete without the required CDD fields.",
    obligation: "Controlled CDD intake — Cabinet 10/2019 Art.4; FDL 10/2025 Art.10.",
    owner: "Compliance Officer", retention: "5 yrs" },
  // Risk & AML Ops
  { key: "ewra", label: "EWRA / BWRA", taskGid: "1215389795092985",
    description: "Enterprise/business-wide ML/TF risk assessment with AI board report.",
    control: "Risk-based approach derived from the EWRA; Board approval required.",
    obligation: "Documented business-wide risk assessment — Cabinet 10/2019 Art.2-3; FATF R.1.",
    owner: "MLRO → Board", retention: "5 yrs" },
  { key: "sar-qa", label: "STR/SAR QA", taskGid: "1215389795331754",
    description: "Four-eyes quality review of STRs before filing, with goAML XML export.",
    control: "Dual-control QA gate before submission; report accuracy verified, then goAML XML export.",
    obligation: "STR reporting to the FIU — Cabinet 10/2019 Art.17-18; FDL 20/2018 Art.15; FATF R.20.",
    owner: "MLRO (sole filing authority)", retention: "5 yrs" },
  { key: "sar-narrative", label: "SAR Narrative", taskGid: "1215389794887438",
    description: "Generates STR/SAR narratives under a tipping-off egress gate.",
    control: "Tipping-off egress gate fail-closed — output withheld (held_review) on disclosure risk.",
    obligation: "Prohibition on tipping off — FDL 20/2018 Art.25; FDL 10/2025 Art.17.",
    owner: "MLRO", retention: "5 yrs" },
  { key: "supply-chain", label: "Supply Chain / Responsible Sourcing", taskGid: "1215399932942190",
    description: "Geographic and human-rights supply-chain risk via OECD 5-step due diligence.",
    control: "OECD five-step due diligence with CAHRA exposure assessment.",
    obligation: "Responsible sourcing for DPMS — MoE/OECD DDG; LBMA RGG v9; MD 68/2024.",
    owner: "Compliance Officer / DPMS compliance", retention: "5 yrs" },
  { key: "rmi", label: "RMI / RMAP", taskGid: "1215386943096738",
    description: "Responsible-minerals assurance with Step-4 audit history.",
    control: "RMAP audit status tracked per smelter/refiner.",
    obligation: "Upstream/downstream assurance — OECD DDG Annex II; LBMA RGG v9.",
    owner: "DPMS compliance", retention: "5 yrs" },
  { key: "oecd-ddg", label: "OECD DDG", taskGid: "1215386942786273",
    description: "Conformance tracking to OECD Due Diligence Guidance for minerals.",
    control: "OECD 5-step conformance checklist maintained.",
    obligation: "Recognised 5-step standard for DPMS supply chains — OECD DDG.",
    owner: "DPMS compliance", retention: "5 yrs" },
  { key: "reg-change", label: "Reg Changes", taskGid: "1215386942169607",
    description: "Regulatory-change roadmap with AI implementation calendar.",
    control: "Each regulatory change has an assigned owner and implementation deadline.",
    obligation: "Keeping the programme current — FDL 10/2025; FATF Methodology.",
    owner: "MLRO / Compliance Officer", retention: "5 yrs" },
  { key: "shipments", label: "Shipments", taskGid: "1215399932805511",
    description: "Bullion chain-of-custody origin→vault with AI TBML scan; holds trigger MLRO review.",
    control: "WORM-logged bullion custody transfers; held status pauses settlement pending MLRO.",
    obligation: "DPMS supply-chain integrity & TBML — MoE DPMS guidance; LBMA RGG v9; OECD 5-step.",
    owner: "DPMS compliance; MLRO on holds", retention: "5 yrs" },
  { key: "eocn", label: "EOCN", taskGid: "1215391559997416",
    description: "UAE targeted financial sanctions registration, NAS/ARS and local control-list screening.",
    control: "Freeze without delay on confirmed TFS match; 24-hour SLA.",
    obligation: "Mandatory TFS screening & freezing — Cabinet 74/2020; UNSC List; EOCN guidance.",
    owner: "MLRO", retention: "5 yrs" },
  { key: "tfs-alerts", label: "TFS Alerts", taskGid: "1215389795150803",
    description: "Monitors EOCN alert emails and auto-creates Asana tasks on new designations.",
    control: "New designations generate a tracked task and re-screen trigger; act ≤24h.",
    obligation: "Continuous monitoring of local terrorist & UN lists — Cabinet 74/2020.",
    owner: "MLRO / Compliance Officer", retention: "5 yrs" },
  { key: "cnmr", label: "CNMR / PNMR", taskGid: "1215386942276174",
    description: "Confirmed/potential name-match queue with FIU notification.",
    control: "Every potential name-match adjudicated; confirmed matches notified to the FIU.",
    obligation: "Adjudicate matches & notify — Cabinet 74/2020; Cabinet 10/2019.",
    owner: "MLRO", retention: "5 yrs" },
  { key: "dpmsr", label: "DPMSR", taskGid: "1215395029662814",
    description: "DPMS cash-transaction reporting at/above AED 55,000 to the FIU via goAML, regardless of suspicion.",
    control: "Amount-triggered filing for single/linked cash transactions ≥ AED 55,000; MLRO approval before submission.",
    obligation: "DPMS cash-threshold report — MoE Circular 08/AML/2021; CR 134/2025 Art.3; FATF R.20.",
    owner: "MLRO", retention: "5 yrs" },
  { key: "moe-survey", label: "MoE Survey", taskGid: "1215391560382846",
    description: "Tracks completion of the mandatory MoE AML/CFT supervisory survey.",
    control: "Survey completion tracked to the MoE submission deadline.",
    obligation: "MoE AML/CFT supervisory survey (MOEC/AML/001/2026) — mandatory for DNFBPs.",
    owner: "MLRO / Compliance Officer", retention: "5 yrs" },
  { key: "enforcement", label: "Enforcement", taskGid: "1215389794793877",
    description: "Regulatory deadline and corrective-action tracker to closure.",
    control: "Owner + due date per corrective action; overdue items escalate to MLRO.",
    obligation: "Remediation of supervisory findings — FDL 10/2025; SOC2 CC7.4.",
    owner: "MLRO / Compliance Officer", retention: "5 yrs" },
  { key: "oversight", label: "Oversight", taskGid: "1215386942712638",
    description: "Board/management four-eyes sign-off, committee minutes and circular disposition.",
    control: "Two independent signatories on sign-off; SLA breaches escalate to MLRO.",
    obligation: "Governance & senior oversight — FDL 10/2025 Art.20; Cabinet 10/2019 Art.21.",
    owner: "Board / senior management / MLRO", retention: "5 yrs" },
  { key: "maker-checker", label: "Maker-Checker", taskGid: "1215386943021777",
    description: "Dual-control workflow for regulated actions with TOCTOU protection.",
    control: "Second authorised user must approve; record re-read under write lock before commit (TOCTOU-safe).",
    obligation: "Segregation of duties — FDL 10/2025 Art.20; Cabinet 10/2019 Art.21.",
    owner: "Two authorised users", retention: "5 yrs" },
  { key: "goaml", label: "goAML Export / Submission", taskGid: "1215389795431515",
    description: "FIU goAML report generation/submission with entity-ID validation.",
    control: "Entity-ID validated before transmission; placeholder Rentity IDs blocked.",
    obligation: "FIU reporting via goAML — Cabinet 10/2019; FATF R.20.",
    owner: "MLRO", retention: "5 yrs" },
  { key: "batch-screening", label: "Batch Screening", taskGid: "1215391559453600",
    description: "Bulk portfolio screening on watchlist updates.",
    control: "Whole book re-screened when the consolidated lists change.",
    obligation: "Re-screening on watchlist change — FDL 20/2018 Art.18; Cabinet 74/2020; FATF R.6.",
    owner: "Compliance Officer; MLRO on hits", retention: "5 yrs" },
  // Governance & Audit
  { key: "responsible-ai", label: "Responsible AI", taskGid: "1215399933258068",
    description: "Governs AI under ethics principles with mandatory human oversight on adverse dispositions.",
    control: "Human-in-the-loop on every adverse decision; model registry carries risk tier + approval.",
    obligation: "AI governance & accountability — FDL 10/2025 Art.24; EU AI Act; ISO/IEC 42001.",
    owner: "MLRO / AI governance owner", retention: "10 yrs" },
  { key: "inspection-room", label: "Inspection Room", taskGid: "1215389795158260",
    description: "Regulator-ready evidence pack (policies, EWRA, cases, audit chain, training).",
    control: "One-click aggregated regulator evidence pack.",
    obligation: "Examination readiness & record production to MoE — Cabinet 10/2019 Art.24; FDL 10/2025.",
    owner: "MLRO", retention: "10 yrs" },
  { key: "regulatory", label: "Regulatory Library", taskGid: "1215386942915596",
    description: "Searchable UAE/FATF/MoE regulatory reference with framework tagging.",
    control: "Citations referenced in dispositions.",
    obligation: "Access to current obligations supporting decisions — FATF Methodology; MoE guidance.",
    owner: "Compliance Officer", retention: "5 yrs" },
  { key: "policies", label: "Policies & SOPs", taskGid: "1215395029252890",
    description: "AML programme charter and procedures, versioned and bound to the audit chain.",
    control: "Each decision references the policy version in force; reviewed at least annually.",
    obligation: "Documented, approved AML/CFT programme — Cabinet 10/2019 Art.21; FDL 10/2025 Art.24.",
    owner: "MLRO → Board", retention: "10 yrs" },
  { key: "typology-library", label: "Typology Library", taskGid: "1215386942278645",
    description: "500+ ML/TF typologies with AI search and UAE/DPMS context.",
    control: "Typology references attached to detections.",
    obligation: "Typology-informed detection — FATF Typologies; MoE DPMS red-flags.",
    owner: "Compliance Officer", retention: "5 yrs" },
  { key: "playbook", label: "Playbook", taskGid: "1215399931643642",
    description: "Step-by-step AML/CFT playbooks; each step writes an audit entry.",
    control: "Mandated procedure steps cannot be skipped silently; each step writes an audit entry.",
    obligation: "Consistent, evidenced execution — Cabinet 10/2019; FATF Methodology.",
    owner: "Compliance Officer / MLRO", retention: "10 yrs" },
  { key: "corrections", label: "Corrections", taskGid: "1215386942129039",
    description: "Data-subject access and correction request handling.",
    control: "Data-subject requests logged and resolved within the statutory window.",
    obligation: "Data-protection rights — UAE PDPL.",
    owner: "Compliance Officer / DPO", retention: "5 yrs" },
  { key: "ai-incident-playbook", label: "AI Incident Playbook", taskGid: "1215399933199811",
    description: "Structured response to AI failures, with Shadow-AI register and Vendor-AI audit.",
    control: "Containment + root-cause + mandatory reporting workflow; Shadow-AI register; Vendor-AI audit.",
    obligation: "AI incident governance & disclosure ≤72h — FDL 10/2025 Art.24.",
    owner: "MLRO / AI governance owner", retention: "10 yrs" },
  { key: "incident-runbook", label: "Incident Runbook", taskGid: "1215389795435804",
    description: "AML/security incident response runbook with retention.",
    control: "Defined response steps to closure.",
    obligation: "Documented incident handling — SOC2 CC7.4; FDL 10/2025 Art.24.",
    owner: "MLRO / security", retention: "10 yrs" },
  { key: "eval-kpi", label: "Eval KPI", taskGid: "1215395029330423",
    description: "Model/brain evaluation KPIs against governance thresholds (calibration, drift, mode effectiveness).",
    control: "Governance-threshold breaches flagged for review.",
    obligation: "Ongoing AI performance assurance — FDL 10/2025 Art.18.",
    owner: "AI governance owner", retention: "10 yrs" },
  { key: "audit-trail", label: "Audit Trail", taskGid: "1215389795047605",
    description: "Immutable, tamper-evident decision chain with FIU export.",
    control: "Hash-linked append-only chain; integrity verified; FIU export.",
    obligation: "Record-keeping & traceability — FDL 20/2018 Art.16; Cabinet 10/2019 Art.24; FDL 10/2025 Art.24.",
    owner: "MLRO / CTO", retention: "10 yrs (WORM)" },
  // Intelligence & KYC Tools
  { key: "intel", label: "Live Intelligence Feed", taskGid: "1215399933267769",
    description: "Live UAE regulatory + 7-language adverse-media feed with AI triage.",
    control: "HIGH/CRITICAL items surfaced and triaged from the live feed.",
    obligation: "Ongoing adverse-media/negative-news monitoring — FDL 20/2018 Art.18; FATF R.6.",
    owner: "Compliance Officer", retention: "5 yrs" },
  { key: "intelligence-hub", label: "Intelligence Hub", taskGid: "1215399932831938",
    description: "Unified AI-brain / security / governance / ops command centre.",
    control: "Consolidated, access-controlled intelligence workspace.",
    obligation: "Governed, transparent intelligence tooling — FDL 10/2025 Art.18.",
    owner: "Compliance Officer / MLRO", retention: "5 yrs" },
  { key: "osint", label: "OSINT", taskGid: "1215399932870318",
    description: "Open-source signal harvesting for enhanced due diligence.",
    control: "Open-source findings attached to the subject file.",
    obligation: "Enhanced due diligence — FATF R.10; Cabinet 10/2019 Art.15.",
    owner: "Compliance Officer / investigator", retention: "5 yrs" },
  { key: "gleif", label: "GLEIF / LEI", taskGid: "1215391560293145",
    description: "LEI lookup and counterparty name search for entity verification.",
    control: "LEI captured where available for counterparty verification.",
    obligation: "Counterparty identification — FATF R.16.",
    owner: "Compliance Officer", retention: "5 yrs" },
  { key: "entity-graph", label: "Entity Graph", taskGid: "1215395029681062",
    description: "Relationship/ownership network graph for opaque structures.",
    control: "Relationship/ownership graph used in EDD of complex entities.",
    obligation: "Understanding control structures — FATF R.24/25; Cabinet 58/2020.",
    owner: "Investigator / MLRO", retention: "5 yrs" },
  { key: "domain-intel", label: "Domain Intel", taskGid: "1215395029681133",
    description: "Domain/web-infrastructure intelligence with email-spoofing risk.",
    control: "Domain/web-infra and email-spoofing risk recorded in the subject file.",
    obligation: "EDD / fraud-risk signals — FATF R.10.",
    owner: "Investigator", retention: "5 yrs" },
  { key: "crypto-risk", label: "Crypto Risk / Exposure", taskGid: "1215386942784660",
    description: "Wallet / virtual-asset exposure risk scoring.",
    control: "Wallet/VA exposure score informs the risk rating.",
    obligation: "Virtual-asset exposure assessment — FATF R.15; VARA.",
    owner: "Compliance Officer", retention: "5 yrs" },
  { key: "vessel-check", label: "Vessel Check", taskGid: "1215386942588445",
    description: "Vessel sanctions and dark-fleet screening for trade exposure.",
    control: "Vessel sanctions / dark-fleet hits routed to MLRO.",
    obligation: "Sanctions screening — Cabinet 74/2020; OFAC SDN; FATF R.6.",
    owner: "Compliance Officer / MLRO", retention: "5 yrs" },
  { key: "benford", label: "Benford Analysis", taskGid: "1215391560085886",
    description: "Benford's-law anomaly testing on transactions.",
    control: "Benford's-law anomalies feed investigation.",
    obligation: "Transaction analytics for suspicion — FATF R.20.",
    owner: "Analyst", retention: "5 yrs" },
  { key: "investigation", label: "Investigation", taskGid: "1215391559142826",
    description: "Case workbench with evidence vault and timeline.",
    control: "Evidence vault + timeline captured per case.",
    obligation: "Structured, evidenced investigation supporting STR decisions — Cabinet 10/2019.",
    owner: "Investigator / MLRO", retention: "5 yrs" },
  { key: "country-risk", label: "Country & Geopolitical Risk", taskGid: "1215391559319047",
    description: "Country ML/TF risk (Basel AML Index, CPI, FATF lists, sanctions, stability) driving CDD level.",
    control: "Country score determines standard / enhanced / senior-approval CDD.",
    obligation: "Country/jurisdiction risk in the RBA — FATF R.19; Cabinet 10/2019; MoE high-risk guidance.",
    owner: "Compliance Officer / MLRO", retention: "5 yrs" },
  { key: "sanctions-evasion", label: "Sanctions Evasion", taskGid: "1215389795331770",
    description: "Sanctions-evasion typology detection.",
    control: "Evasion patterns flagged to MLRO.",
    obligation: "Sanctions compliance — Cabinet 74/2020; OFAC; FATF R.6.",
    owner: "MLRO", retention: "5 yrs" },
  { key: "intelligence-tools", label: "Intelligence Tools", taskGid: "1215399933189531",
    description: "UBO walker, crypto exposure and synthetic-ID detection tools.",
    control: "UBO walker / crypto exposure / synthetic-ID output attached to the subject.",
    obligation: "EDD / UBO verification — FATF R.10/24; Cabinet 58/2020.",
    owner: "Investigator", retention: "5 yrs" },
  { key: "adverse-media-live", label: "Adverse-Media (Live/Lookback)", taskGid: "1215389795006518",
    description: "Real-time and historical adverse-media screening across 7 languages.",
    control: "Hits classified by severity; HIGH/CRITICAL escalate.",
    obligation: "Negative-news due diligence — FATF R.6; FDL 20/2018 Art.18.",
    owner: "Compliance Officer", retention: "5 yrs" },
  { key: "analyst-behavior", label: "Analyst Behavior", taskGid: "1215395028703800",
    description: "UEBA over compliance staff (bulk exports, off-hours, override rates, audit recon).",
    control: "UEBA insider-threat alerts surfaced before findings; CSV evidence export.",
    obligation: "Internal controls / insider-threat monitoring — FDL 10/2025 Art.20; SOC2 CC7.4.",
    owner: "MLRO / security", retention: "5 yrs" },
  { key: "brain-map", label: "Brain Map", taskGid: "1215391559696335",
    description: "Reasoning-faculty catalogue and integrity view of the AI engine.",
    control: "Reasoning-faculty / version manifest exposed for integrity review.",
    obligation: "AI transparency/explainability — FDL 10/2025 Art.18.",
    owner: "AI governance owner", retention: "10 yrs" },
  { key: "intel-status", label: "Intel Status", taskGid: "1215389794362258",
    description: "Live intelligence-source and watchlist health monitoring.",
    control: "Intelligence-source and watchlist health surfaced; stale sources flagged.",
    obligation: "Assurance screening sources are current — FATF R.6; Cabinet 74/2020.",
    owner: "Compliance Officer", retention: "5 yrs" },
  // Screening, Monitoring & Core
  { key: "screening", label: "Screening", taskGid: "1215399932324435",
    description: "Name/entity screening vs UNSC/OFAC/EU CFSP/local lists with scoring and disambiguation.",
    control: "Name/entity screening at onboarding and ongoing; hits route to MLRO.",
    obligation: "Mandatory sanctions/PEP/adverse-media screening — FDL 20/2018 Art.18; Cabinet 74/2020; FATF R.6.",
    owner: "Compliance Officer; MLRO on hits", retention: "5 yrs" },
  { key: "transaction-monitor", label: "Transaction Monitor", taskGid: "1215389794939200",
    description: "Behavioural transaction monitoring with DPMS-threshold and typology flagging; auto-opens cases on critical alerts.",
    control: "Threshold/typology rules; critical alerts auto-open cases.",
    obligation: "Ongoing transaction monitoring — MoE Circular 08/AML/2021; Cabinet 10/2019 Art.7; FATF R.20.",
    owner: "Compliance Officer; MLRO on escalation", retention: "5 yrs" },
  { key: "ongoing-monitor", label: "Ongoing Monitor", taskGid: "1215395029307642",
    description: "Scheduled re-screening (high-risk twice-daily) plus AI pattern scan to the case timeline.",
    control: "Re-screening cadence enforced (high-risk twice-daily); results written to the case timeline.",
    obligation: "Ongoing/perpetual monitoring — Cabinet 10/2019 Art.7; FDL 10/2025 Art.12; FATF R.10.",
    owner: "Compliance Officer", retention: "5 yrs" },
  { key: "str-cases", label: "STR Cases", taskGid: "1215399932805525",
    description: "STR/SAR case lifecycle from screening → MLRO disposition → FIU filing.",
    control: "Full STR lifecycle with disposition + filing reference.",
    obligation: "Suspicious-activity case governance & reporting — Cabinet 10/2019 Art.17; FATF R.20.",
    owner: "MLRO", retention: "5 yrs" },
  { key: "mlro-advisor", label: "MLRO Advisor", taskGid: "1215391560330326",
    description: "AI advisory (executor/advisor/challenger) with full audit trail.",
    control: "AI advisory logged; MLRO retains decision authority.",
    obligation: "Decision support preserving MLRO independence — FDL 10/2025 Art.18/24; Cabinet 10/2019 Art.20.",
    owner: "MLRO", retention: "10 yrs" },
  { key: "access-control", label: "Access Control", taskGid: "1215399932334600",
    description: "Users/roles/module permissions with an immutable permission audit trail.",
    control: "RBAC enforced; every permission change logged immutably.",
    obligation: "Logical access control & segregation of duties — FDL 10/2025 Art.20; SOC2 CC6.1; Cabinet 10/2019 Art.21.",
    owner: "Administrator / MLRO", retention: "10 yrs" },
  { key: "analytics-dashboard", label: "Analytics Dashboard", taskGid: "1215386942464213",
    description: "MLRO digest, bias monitoring and risk forecast.",
    control: "Bias ratio monitored vs threshold; MLRO digest produced.",
    obligation: "Non-discrimination + management oversight — FATF R.10; FDL 10/2025.",
    owner: "MLRO", retention: "5 yrs" },
  { key: "kri-dashboard", label: "KRI Dashboard", taskGid: "1215389793489223",
    description: "Key risk indicators tracked against risk-appetite bands.",
    control: "Key risk indicators tracked vs risk-appetite bands; breaches escalate.",
    obligation: "Risk-appetite monitoring — FATF R.1.",
    owner: "MLRO / Board", retention: "5 yrs" },
  { key: "training", label: "Training", taskGid: "1215389794320590",
    description: "AML/CFT training completion, expiry and annual programme.",
    control: "Training completion tracked; lapses flagged (annual programme).",
    obligation: "Staff training — Cabinet 10/2019 Art.21; FDL 10/2025 Art.16; MoE DNFBP guidance.",
    owner: "Compliance Officer", retention: "5 yrs" },
];

// Per-module control frequency / SLA (report "Control frequency / SLA").
// Held separately to keep the task array stable; falls back to a sensible
// default for any key not listed.
export const MODULE_FREQUENCY: Record<string, string> = {
  "client-portal": "Every new customer, at onboarding, before activation",
  "ubo-declaration": "At onboarding and on any ownership change",
  "pep-profile": "At onboarding; re-assessed at each periodic review",
  "cdd-review": "Per risk tier — high 3-monthly, medium 6-monthly, low annually",
  "data-quality": "Continuous; remediation per SLA",
  "ownership": "At onboarding and on structure change",
  "employees": "Continuous; documents flagged 30 days pre-expiry",
  "approvals": "Per onboarding decision",
  "vendor-dd": "Per tier — critical annual, significant 18-monthly, standard 24-monthly",
  "onboarding": "Per new customer",
  "ewra": "At least annually and on material change",
  "sar-qa": "Per report; file without delay on suspicion",
  "sar-narrative": "Per report",
  "supply-chain": "Per supplier; annual review",
  "rmi": "Per supplier; annual",
  "oecd-ddg": "Annual",
  "reg-change": "Continuous horizon-scan",
  "shipments": "Per consignment / custody transfer",
  "eocn": "Every customer/transaction and on list updates; freeze ≤24h",
  "tfs-alerts": "Continuous; act on designation ≤24h",
  "cnmr": "On each alert; without delay",
  "dpmsr": "Per qualifying transaction; file ≤24h via goAML",
  "moe-survey": "Per MoE survey cycle",
  "enforcement": "Per finding/deadline",
  "oversight": "Per approval; periodic committee cadence",
  "maker-checker": "Per sensitive action",
  "goaml": "Per report; without delay",
  "batch-screening": "On list update / scheduled",
  "responsible-ai": "Continuous; per AI decision",
  "inspection-room": "On demand / examination",
  "regulatory": "Continuous",
  "policies": "Reviewed at least annually",
  "typology-library": "Continuous",
  "playbook": "Per procedure",
  "corrections": "Per request; statutory deadline",
  "ai-incident-playbook": "Per incident; report ≤72h",
  "incident-runbook": "Per incident",
  "eval-kpi": "Continuous / per evaluation window",
  "audit-trail": "Per event; continuous",
  "intel": "Live (5-minute refresh)",
  "intelligence-hub": "Continuous",
  "osint": "On EDD trigger",
  "gleif": "At onboarding / on demand",
  "entity-graph": "On complex-structure review",
  "domain-intel": "On EDD trigger",
  "crypto-risk": "On virtual-asset-linked subject",
  "vessel-check": "On trade-related screening",
  "benford": "On dataset analysis",
  "investigation": "Per case",
  "country-risk": "At onboarding & review; lists refreshed continuously",
  "sanctions-evasion": "Continuous",
  "intelligence-tools": "On EDD trigger",
  "adverse-media-live": "At onboarding, ongoing, and on demand",
  "analyst-behavior": "Continuous; configurable window",
  "brain-map": "Continuous",
  "intel-status": "Continuous",
  "screening": "At onboarding, on transactions, on list updates",
  "transaction-monitor": "Continuous / per transaction",
  "ongoing-monitor": "Per cadence — high-risk twice-daily, medium daily, low weekly",
  "str-cases": "Per case; file without delay",
  "mlro-advisor": "On demand",
  "access-control": "Per change; continuous",
  "analytics-dashboard": "Continuous / periodic digest",
  "kri-dashboard": "Continuous",
  "training": "At least annually",
};
