// GET /api/designation-alerts
//
// Returns recent sanctions designation alerts (new listings and delistings)
// generated by netlify/functions/designation-alert-check.mts.
//
// This is a read-only view of alerts with severity=critical|high posted to
// /api/alerts by the designation-alert-check scheduled function. Operators
// and the MCP `call_api` tool can use this endpoint to check for new
// OFAC/UN/EU/UK OFSI designations without reading the full alerts inbox.

import { NextResponse } from "next/server";
import { enforce } from "@/lib/server/enforce";
import { listAlerts, type DesignationAlert } from "@/lib/server/alerts-store";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 15;

export async function GET(req: Request): Promise<NextResponse> {
  const gate = await enforce(req);
  if (!gate.ok) return gate.response;

  const url = new URL(req.url);
  const limitParam = url.searchParams.get("limit");
  const limit = Math.min(100, Math.max(1, parseInt(limitParam ?? "50", 10) || 50));

  try {
    const all = await listAlerts(false);
    // Filter to designation-type alerts (from OFAC/UN/EU/UK OFSI/UAE EOCN)
    const sanctionsSources = new Set(["OFAC SDN", "UN 1267", "EU Consolidated", "UK OFSI", "UAE EOCN", "ofac_sdn", "un_1267", "eu_consolidated", "uk_ofsi", "uae_eocn"]);
    const designationAlerts: DesignationAlert[] = all.filter(
      (a) => sanctionsSources.has(a.listId ?? "") || a.severity === "critical" || a.severity === "high",
    );

    const recent = designationAlerts
      .sort((a, b) => (b.detectedAt ?? "").localeCompare(a.detectedAt ?? ""))
      .slice(0, limit);

    return NextResponse.json(
      {
        ok: true,
        total: designationAlerts.length,
        unread: designationAlerts.filter((a) => !a.read).length,
        alerts: recent,
        note: "Designation alerts posted by designation-alert-check.mts (hourly at :10 UTC). Full inbox: GET /api/alerts",
      },
      { headers: gate.headers },
    );
  } catch (err) {
    console.warn("[designation-alerts GET]", err instanceof Error ? err.message : String(err));
    return NextResponse.json(
      { ok: true, total: 0, unread: 0, alerts: [], note: "Could not read alerts store" },
      { headers: gate.headers },
    );
  }
}
