/**
 * goAML XML Export Generator.
 *
 * Generates valid goAML XML format for filing submissions to the UAE
 * Financial Intelligence Unit (FIU). Supports:
 *
 *   - STR  (Suspicious Transaction Report)
 *   - SAR  (Suspicious Activity Report)
 *   - CTR  (Cash Transaction Report / DPMSR)
 *   - CNMR (Confiscation/Non-Monetary Report)
 *
 * The XML follows the goAML v4.0 schema used by the UAE FIU platform.
 * Generated XML is a DRAFT — must be reviewed by the MLRO before
 * submission via the goAML web portal.
 *
 * Reference: goAML Documentation Guide v4.0 (UAE FIU)
 */

/**
 * Generate goAML-compatible XML for a filing.
 *
 * @param {object} filing - Filing data
 * @param {string} filing.type - STR, SAR, CTR, CNMR
 * @param {string} filing.reporterName - Reporting entity legal name
 * @param {string} filing.reporterLicense - DPMS license number
 * @param {string} filing.mlroName - MLRO full name
 * @param {string} filing.subjectName - Subject of the report
 * @param {string} filing.subjectType - person or entity
 * @param {string} filing.narrative - Suspicious activity description
 * @param {number} [filing.amount] - Transaction amount in AED
 * @param {string} [filing.transactionDate] - Date of transaction
 * @param {string} [filing.subjectDob] - Subject date of birth
 * @param {string} [filing.subjectNationality] - Subject nationality (ISO)
 * @param {string} [filing.subjectIdType] - ID document type
 * @param {string} [filing.subjectIdNumber] - ID document number
 * @param {string} [filing.subjectAddress] - Subject address
 * @returns {string} XML string
 */
export function generateGoAMLXml(filing) {
  const reportDate = new Date().toISOString().split('T')[0];
  const reportId = `HWK-${filing.type}-${Date.now().toString(36).toUpperCase()}`;

  const typeCode = {
    STR: 'STR',
    SAR: 'SAR',
    CTR: 'CTR',
    DPMSR: 'CTR',
    CNMR: 'CNMR',
  }[filing.type] || 'STR';

  const subjectTag = filing.subjectType === 'entity' ? 'entity' : 'person';

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- goAML XML Draft — Generated by Hawkeye-Sterling -->
<!-- DRAFT: Must be reviewed by MLRO before submission -->
<goAMLReport
  xmlns="http://www.goaml.org/schema"
  reportVersion="4.0"
  reportType="${typeCode}">

  <reportHeader>
    <reportId>${escapeXml(reportId)}</reportId>
    <reportDate>${reportDate}</reportDate>
    <reportingEntityName>${escapeXml(filing.reporterName || 'DPMS Entity')}</reportingEntityName>
    <reportingEntityLicense>${escapeXml(filing.reporterLicense || '')}</reportingEntityLicense>
    <reportingPersonName>${escapeXml(filing.mlroName || 'MLRO')}</reportingPersonName>
    <reportType>${typeCode}</reportType>
    <priority>HIGH</priority>
    <currency>AED</currency>
    <reportStatus>DRAFT</reportStatus>
  </reportHeader>

  <subjects>
    <${subjectTag}>
      <name>${escapeXml(filing.subjectName)}</name>
      ${filing.subjectDob ? `<dateOfBirth>${escapeXml(filing.subjectDob)}</dateOfBirth>` : ''}
      ${filing.subjectNationality ? `<nationality>${escapeXml(filing.subjectNationality)}</nationality>` : ''}
      ${filing.subjectIdType ? `<identification>
        <idType>${escapeXml(filing.subjectIdType)}</idType>
        <idNumber>${escapeXml(filing.subjectIdNumber || '')}</idNumber>
      </identification>` : ''}
      ${filing.subjectAddress ? `<address>${escapeXml(filing.subjectAddress)}</address>` : ''}
    </${subjectTag}>
  </subjects>

  ${filing.amount ? `<transactions>
    <transaction>
      <transactionDate>${escapeXml(filing.transactionDate || reportDate)}</transactionDate>
      <amount>${filing.amount}</amount>
      <currency>AED</currency>
      <transactionType>${typeCode === 'CTR' ? 'CASH' : 'OTHER'}</transactionType>
    </transaction>
  </transactions>` : ''}

  <narrative>
    <suspicionIndicators>
      ${escapeXml(filing.narrative)}
    </suspicionIndicators>
    <actionsTaken>
      Filing generated by Hawkeye-Sterling compliance automation system.
      Transaction ${filing.amount ? `of AED ${Number(filing.amount).toLocaleString()} ` : ''}flagged for review.
      Subject to MLRO review and approval before submission.
    </actionsTaken>
  </narrative>

  <reportFooter>
    <generatedBy>Hawkeye-Sterling v2.0.0</generatedBy>
    <generatedAt>${new Date().toISOString()}</generatedAt>
    <disclaimer>DRAFT — Not submitted to goAML. Requires MLRO review and approval.</disclaimer>
  </reportFooter>

</goAMLReport>`;

  return xml;
}

/**
 * Generate a CSV export of screening results.
 *
 * @param {Array} results - Array of screening results
 * @returns {string} CSV string
 */
export function generateScreeningCsv(results) {
  const headers = [
    'Case ID', 'Subject', 'Type', 'Decision', 'Top Band', 'Top Score',
    'Hit Count', 'Top Match Name', 'Top Match Source', 'Screened At',
  ];

  const rows = results.map(r => [
    r.caseId,
    csvEscape(r.query?.name || ''),
    r.query?.type || 'person',
    r.decision,
    r.topBand,
    r.hits?.[0]?.score || 0,
    r.hits?.length || 0,
    csvEscape(r.hits?.[0]?.matchedName || ''),
    r.hits?.[0]?.source || '',
    new Date().toISOString(),
  ]);

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}

/**
 * Generate a risk assessment PDF-compatible data object.
 *
 * @param {object} assessment - Risk assessment result
 * @returns {object} Structured data for PDF rendering
 */
export function generateRiskReport(assessment) {
  return {
    title: `ENTITY RISK ASSESSMENT: ${assessment.entity}`,
    date: new Date().toISOString().split('T')[0],
    sections: [
      {
        heading: 'Risk Summary',
        content: [
          `Entity: ${assessment.entity}`,
          `Country: ${assessment.country}`,
          `Risk Score: ${assessment.score}/25 (${assessment.band})`,
          `Likelihood: ${assessment.likelihood}/5`,
          `Impact: ${assessment.impact}/5`,
          `CDD Level: ${assessment.cddLevel}`,
          `Review Cycle: ${assessment.reviewCycle}`,
        ],
      },
      {
        heading: 'Likelihood Factors',
        content: assessment.likelihoodFactors.map(f =>
          `${f.factor}: ${f.detail} (weight: ${f.weight > 0 ? '+' : ''}${f.weight})`
        ),
      },
      {
        heading: 'Impact Factors',
        content: assessment.impactFactors.map(f =>
          `${f.factor}: ${f.detail} (weight: ${f.weight > 0 ? '+' : ''}${f.weight})`
        ),
      },
      {
        heading: 'Recommendations',
        content: assessment.recommendations,
      },
      {
        heading: 'Methodology',
        content: [
          assessment.methodology.formula,
          `Reference: ${assessment.methodology.reference}`,
        ],
      },
    ],
    footer: 'For review by the MLRO.',
  };
}

function escapeXml(s) {
  if (!s) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function csvEscape(s) {
  if (!s) return '';
  const str = String(s);
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}
