"use client";
// Batch Screening Audit Report — redesigned cover-style PDF.
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  PW, PH, ML, MR, CW, CONTENT_Y, BOTTOM_Y,
  BLACK, GRAY_D, GRAY_M, GRAY_L, WHITE, PINK,
  coverFrame, contentFrame, coverLogo, coverFooter,
  dropCapTitle, oneCard, metaGrid,
  partHeader, sigFooter,
} from "./pdfDesign";

export interface BatchRowResult {
  name: string;
  isDuplicate?: boolean;
  entityType?: string;
  jurisdiction?: string;
  severity: string;
  topScore: number;
  hitCount: number;
  listCoverage: string[];
  keywordGroups?: string[];
  checkpoints?: string[];
  error?: string;
}

export interface BatchSummary {
  total: number;
  critical: number;
  high: number;
  medium: number;
  low: number;
  clear: number;
  errors: number;
  duplicates: number;
  totalDurationMs: number;
}

type ATDoc = { lastAutoTable: { finalY: number } };

function disposition(sev: string): string {
  switch (sev.toLowerCase()) {
    case "critical": return "ESCALATE";
    case "high":     return "EDD REQUIRED";
    case "medium":   return "REVIEW";
    default:         return "CLEAR";
  }
}

function badgeColors(text: string): [number,number,number] {
  const t = text.toLowerCase();
  if (t.includes("critical") || t.includes("escalate")) return PINK;
  if (t.includes("high")     || t.includes("edd"))      return PINK;
  if (t.includes("medium")   || t.includes("review"))   return [100,100,100];
  return [150,150,150];
}

function guard(doc: jsPDF, y: number, needed: number): number {
  if (y+needed > BOTTOM_Y) { doc.addPage(); return CONTENT_Y; }
  return y;
}

export async function exportBatchPdf(results: BatchRowResult[], summary: BatchSummary): Promise<void> {
  const doc = new jsPDF({ unit:"pt", format:"a4" });
  const now = new Date();
  const dd   = String(now.getDate()).padStart(2,"0");
  const mm   = String(now.getMonth()+1).padStart(2,"0");
  const yyyy = now.getFullYear();
  const dateStr = `${dd}/${mm}/${yyyy}`;
  const timeStr = now.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",second:"2-digit",timeZone:"Asia/Dubai"})+" GST";
  const durationS = (summary.totalDurationMs/1000).toFixed(1);
  const ref = `HWK-BATCH-${String(now.getDate()).padStart(2,"0")}${String(now.getMonth()+1).padStart(2,"0")}${yyyy}`;
  const listsApplied = new Set(results.flatMap(r => r.listCoverage)).size || 8;
  const listNames = [...new Set(results.flatMap(r=>r.listCoverage))].slice(0,8).join("  ·  ") ||
    "UN Consolidated  ·  OFAC SDN  ·  OFAC Non-SDN  ·  EU CFSP  ·  UK OFSI  ·  UAE EOCN  ·  UAE LTL";

  // ── COVER ──────────────────────────────────────────────────────────────────
  coverFrame(doc, ref);
  coverLogo(doc, ML+22, 105);

  doc.setFont("helvetica","bold"); doc.setFontSize(22); doc.setCharSpace(6);
  doc.setTextColor(BLACK[0],BLACK[1],BLACK[2]);
  doc.text("HAWKEYE  ·  STERLING", PW/2, 147, {align:"center"}); doc.setCharSpace(0);

  doc.setFont("helvetica","normal"); doc.setFontSize(8); doc.setCharSpace(2);
  doc.setTextColor(GRAY_D[0],GRAY_D[1],GRAY_D[2]);
  doc.text("BATCH SCREENING ENGINE", PW/2, 163, {align:"center"}); doc.setCharSpace(0);

  doc.setFont("helvetica","normal"); doc.setFontSize(7.5); doc.setCharSpace(0.5);
  doc.setTextColor(GRAY_D[0],GRAY_D[1],GRAY_D[2]);
  doc.text(ref, PW-MR, 147, {align:"right"}); doc.setCharSpace(0);

  doc.setFont("helvetica","normal"); doc.setFontSize(7); doc.setCharSpace(2.5);
  doc.setTextColor(GRAY_M[0],GRAY_M[1],GRAY_M[2]);
  doc.text("DOCUMENT TYPE", PW/2, 210, {align:"center"}); doc.setCharSpace(0);

  dropCapTitle(doc, "B", "atch Screening Audit Report", 250);

  doc.setFont("helvetica","normal"); doc.setFontSize(8.5); doc.setTextColor(GRAY_D[0],GRAY_D[1],GRAY_D[2]);
  doc.text(doc.splitTextToSize(
    "Aggregate screening results for the current batch run. Records list coverage, severity distribution, and per-subject disposition. Generated by the Hawkeye Sterling screening engine.",
    380
  ), PW/2, 272, {align:"center"});

  // Single card (batch info)
  oneCard(doc, 308, {
    label: "BATCH IDENTIFIER",
    title: `Batch ${ref}`,
    tags: `${summary.total} SUBJECTS  ·  ${listsApplied} LISTS APPLIED  ·  ${ref}`,
  });

  metaGrid(doc, 568, [
    { label:"DATE GENERATED",    value:dateStr,             sub:timeStr },
    { label:"ENGINE",            value:"Sonnet-4.6 / Opus-4.7", sub:"Multi-modal Advisor" },
    { label:"DURATION",          value:`${durationS} s`,    sub:`${summary.total} Subjects` },
    { label:"OFFICER",           value:"L. Fernanda",        sub:"CO/MLRO" },
    { label:"REPORT IDENTIFIER", value:ref,                 sub:"Immutable  ·  Signed" },
    { label:"RETENTION",         value:"10 years",          sub:"FDL 10/2025" },
  ]);
  coverFooter(doc);

  // ── CONTENT PAGE ───────────────────────────────────────────────────────────
  doc.addPage();
  let y = CONTENT_Y;

  doc.setFont("helvetica","bold"); doc.setFontSize(16); doc.setTextColor(BLACK[0],BLACK[1],BLACK[2]);
  doc.text("Batch Screening Audit Report", ML, y); y+=12;

  doc.setFont("helvetica","normal"); doc.setFontSize(8.5); doc.setTextColor(GRAY_M[0],GRAY_M[1],GRAY_M[2]);
  doc.text(`${summary.total} subjects  ·  ${summary.critical} critical hits  ·  run duration ${durationS} s`, ML, y); y+=20;

  // Stats bar — 5 bordered cells
  const CELL_W = CW/5, CELL_H=52;
  const stats: Array<{num:string;label:string;color:[number,number,number]}> = [
    { num:String(summary.total),   label:"TOTAL SCREENED", color:BLACK },
    { num:String(summary.critical),label:"CRITICAL HITS",  color:PINK },
    { num:String(summary.high),    label:"HIGH RISK",      color:PINK },
    { num:String(summary.clear),   label:"CLEAR",          color:BLACK },
    { num:`${durationS}S`,         label:"DURATION",       color:BLACK },
  ];
  stats.forEach((stat,i) => {
    const sx = ML + i*CELL_W;
    doc.setDrawColor(GRAY_L[0],GRAY_L[1],GRAY_L[2]); doc.setLineWidth(0.4);
    doc.rect(sx, y, CELL_W, CELL_H, "S");
    doc.setFont("helvetica","bold"); doc.setFontSize(22); doc.setTextColor(stat.color[0],stat.color[1],stat.color[2]);
    doc.text(stat.num, sx+CELL_W/2, y+30, {align:"center"});
    doc.setFont("helvetica","normal"); doc.setFontSize(6.5); doc.setCharSpace(0.5); doc.setTextColor(GRAY_M[0],GRAY_M[1],GRAY_M[2]);
    doc.text(stat.label, sx+CELL_W/2, y+44, {align:"center"}); doc.setCharSpace(0);
  });
  y += CELL_H+18;

  // Part 1 — Screening results
  y = guard(doc,y,60); y = partHeader(doc,"PART ONE","01","Screening results",y);

  const today = dateStr;
  autoTable(doc, {
    startY: y,
    head: [["ID","SUBJECT","SCORE","SEVERITY","DISPOSITION","SCREENED"]],
    body: results.map((r,i) => [
      `HS-${10043+i}`,
      r.name+(r.isDuplicate?" [DUP]":""),
      String(r.topScore),
      r.severity.toUpperCase(),
      disposition(r.severity),
      today,
    ]),
    margin: { left:ML, right:MR, top:CONTENT_Y },
    styles: { fontSize:8, cellPadding:4, overflow:"linebreak", textColor:[30,30,30] as [number,number,number] },
    headStyles: { fillColor:WHITE, textColor:BLACK, fontStyle:"bold", fontSize:7, lineWidth:0.3, lineColor:GRAY_L },
    bodyStyles: { lineWidth:0.3, lineColor:GRAY_L },
    columnStyles: {
      0:{cellWidth:60}, 1:{cellWidth:120}, 2:{cellWidth:42},
      3:{cellWidth:72}, 4:{cellWidth:85}, 5:{cellWidth:CW-379},
    },
    theme:"plain",
    willDrawCell: (data: { section:string; column:{index:number}; cell:{text:string[]} }) => {
      if (data.section==="body" && (data.column.index===3 || data.column.index===4)) {
        // suppress default text — draw badge manually in didDrawCell
        data.cell.text = [];
      }
    },
    didDrawCell: (data: { section:string; column:{index:number}; cell:{raw:unknown;x:number;y:number;width:number;height:number} }) => {
      if (data.section==="body" && (data.column.index===3 || data.column.index===4)) {
        const text = String(data.cell.raw||"").toUpperCase();
        if (!text) return;
        const [r,g,b] = badgeColors(text);
        doc.setFont("helvetica","bold"); doc.setFontSize(7);
        const tw = doc.getTextWidth(text);
        const bw=tw+8, bh=9;
        const bx=data.cell.x+(data.cell.width-bw)/2;
        const by=data.cell.y+(data.cell.height-bh)/2;
        doc.setDrawColor(r,g,b); doc.setLineWidth(0.5); doc.rect(bx,by,bw,bh,"S");
        doc.setTextColor(r,g,b); doc.text(text, bx+bw/2, by+bh-2.5, {align:"center"});
      }
    },
  });
  y = (doc as unknown as ATDoc).lastAutoTable.finalY+16;

  // Part 2 — List coverage
  y = guard(doc,y,60); y = partHeader(doc,"PART TWO","02","List coverage applied",y);
  doc.setFont("helvetica","normal"); doc.setFontSize(9); doc.setTextColor(GRAY_D[0],GRAY_D[1],GRAY_D[2]);
  const ll = doc.splitTextToSize(listNames, CW); doc.text(ll, ML, y); y+=ll.length*12+16;

  // Signature footer
  y = guard(doc,y,90);
  sigFooter(doc, Math.max(y+20,BOTTOM_Y-60), ref, [
    { name:"L. Fernanda",    role:"CO/MLRO  ·  REVIEWER",  id:"HS-MLRO-0428", date:dateStr },
    { name:"Engine Operator",role:"BATCH ENGINE",            id:"HWK-ENG-0042",  date:dateStr },
    { name:"QA Reviewer",    role:"SAMPLE AUDIT 5%",        id:"HS-QA-0019",    date:dateStr },
  ]);

  // Final pass — content page headers
  const total = doc.getNumberOfPages()-1;
  for (let p=2; p<=doc.getNumberOfPages(); p++) {
    doc.setPage(p);
    contentFrame(doc, ref, "FDL 10/2025 ART.9  ·  FATF R.10  ·  CBUAE AML","STANDARDS §4", p-1, total);
  }

  doc.save(`hawkeye-batch-${ref}.pdf`);
}
